### ISSUE TITLE
Allow for use of SSE-KMS encryption with a specified KMS Key ARN

### ISSUE THREAD

**Issue by robparrott** [kahing/goofys#102]
We'd like to be able to mount a goofy volume with parameters that specify that all writes are encrypted using a specified KMS key (provided by ARN).

It also needs to be able to read any object from S3 that are SSE-KMS encrypted with the specified KMS key.

**Comment by robparrott** [comment]
This feature would be a follow up to #105 since it involves setting the appopriate header to "aws:kms" and optionally setting a KMS key ARN id.

**Comment by robparrott** [comment]
PR Submitted: https://github.com/kahing/goofys/pull/107

**Comment by kahing** [comment]
55c235cf0dec33bd5c0542e5c0ed4fe2ced7628f

**Comment by robparrott** [comment]
Thanks for merging this so fast!

Any chance of cutting a new release with this set of new features and fixes?

**Comment by kahing** [comment]
only if you guys tell me what you are up to with goofys ;-)

**Comment by robparrott** [comment]
Sure,

We're using it to provide volume mounts to docker containers so that import/export and diagnostics capture will use a centralized object store, and not a local or shared filesystem. In the future we plan to add features to the product to write directly to S3 for some of this, but for now this provides a technology bridge.
