### ISSUE TITLE
Add option to Suppress HeadBucket verification

### ISSUE THREAD

**Issue by limbo127** [kahing/goofys#103]
hello,
fs.testBucket() call headbucket fonction to verify Bucket presence.
However, Headbucket needs some specific  policie, authorize ListBucket , which is problematic is our case. 
Can you provide an option to disable this verification 
Regards, 
Nicolas Prochazka.

**Comment by kahing** [comment]
yup this is a problem. In fact some policies don't even support HeadObject (and only allow GetObject for example). agreed that goofys need to handle this better.
