### ISSUE TITLE
Add multipart actions

### ISSUE THREAD

**Issue by limbo127** [kahing/goofys#104]
Hello, 
During multipart process , it will be very interesting for us to make action when part upload is finished.
For example, a simple progress bar in file ..
How can add a new function to do that in goofys code ?

Regards, 
Nicolas Prochazka

**Comment by andrewgaul** [comment]
goofys cannot support this since it works at the file system level, underneath the application.  You can use something like `pv`, or pipe viewer:

http://linux.die.net/man/1/pv

**Comment by limbo127** [comment]
goofys knows when it sends new parts of multipart content, is it possible to call a function at this time, 
a go fonction, for exemple that calls a lambda function.

Regards, 
Nicolas

**Comment by andrewgaul** [comment]
goofys has no way to interact with the terminal; it works at the file system level.

**Comment by limbo127** [comment]
I do not interact with terminal, I want to execute a Go funtion when a part
is finishing to upload.
Regards,
Nicolas Prochazka

2016-09-06 18:51 GMT+02:00 Andrew Gaul <notifications@github.com>:

**Comment by kahing** [comment]
Are you embedding goofys into your own go process? Goofys isn't quite designed for that, any reason why you don't use the aws sdk directly?

**Comment by limbo127** [comment]
hello,
before using goofys, we are using s3cmd . We have modify s3cmd code, so
when a part of multipart upload finish, s3cmd send some command ( example:
an sns message, a sqs message ) , so we can log the progress of uploading
file with an other application.
Now we like do the same thing with goofys, when a copy is progressing, when
a part of multipart is finished, send a new message,
so we think that a "trigger function" when a part ip finished , in goofys
is a good thing for us :)
Regards,


2016-09-06 23:16 GMT+02:00 Ka-Hing Cheung <notifications@github.com>:

**Comment by kahing** [comment]
this sounds like a very niche use case of the already pretty niche goofys :-P could you describe more about what you do on these notifications on every part upload? I need to understand this better before I can figure out what to do with this.

also, could you describe what's the motivation behind moving from s3cmd to goofys? This is more for my curiousity

**Comment by limbo127** [comment]
When a part of a multipart upload is finished, is interesting to send this information.
The idea is to create a "callback" function in goofys , so dev can  easily implement this callback, 
In our case, we send a sns notification, so our product can be informe that file is in progress.

S3cmd does not implement filesystem mount, and we need it because our software open file.

Regards, 
Nicolas

**Comment by kahing** [comment]
If you need to modify goofys for the callbacks anyway, adding the callbacks at the right place isn't that hard. Doesn't sound like it's something that I want to do anything about
