### ISSUE TITLE
Enable SSE-S3 encryption as an option

### ISSUE THREAD

**Issue by robparrott** [kahing/goofys#105]
Basically set the appropriate header to enable SSE-S3 server side encryption for all put/upload operations.

Docs here: http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingServerSideEncryption.html

Header is defined in appropriate Input params here: https://docs.aws.amazon.com/sdk-for-go/api/service/s3/  by setting the input parameter:

`ServerSideEncryption` = `AES-256`

Am working towards a PR.

**Comment by robparrott** [comment]
PR: https://github.com/kahing/goofys/pull/106

**Comment by kahing** [comment]
55c235cf0dec33bd5c0542e5c0ed4fe2ced7628f
