### ISSUE TITLE
Feature Request: Machine readable output

### ISSUE THREAD

**Issue by cspray** [kahing/goofys#108]
I am currently using your tool to automate some processes through a series of bash scripts. It would be helpful if I could pass a flag, `--machine-readable`, that would output JSON-encoded text or some other output that I could parse programatically. Right now I'm relying on a regex on the human-friendly output and it doesn't feel like a very good permanent solution.

I would do the work necessary for this myself but I'm not familiar enough with Go to contribute at that level. Thanks for the great tool, it has worked out very well so far.

**Comment by kahing** [comment]
What output are you referring to?

**Comment by cspray** [comment]
I am incredibly sorry. This was meant for a different tool I'm using in the same process and I opened up the issues on the wrong repo. I'll close this as it is not relevant.
