### ISSUE TITLE
./main.go:215: cannot use func literal (type func(*cli.Context) error) as type func(*cli.Context) in assignment

### ISSUE THREAD

**Issue by minty** [kahing/goofys#112]
Hi there,

Bug report for you:

* Ubuntu 14.04 fully patched running in AWS

Installed with:

```
$ rm -rf $GOPATH/src/github.com/kahing/goofys
$ go get -d github.com/kahing/goofys
$ cd $GOPATH/src/github.com/kahing/goofys/
$ git checkout -b f071ec5b5eaec515542f37c3bd4356b23a33941b f071ec5b5eaec515542f37c3bd4356b23a33941b
$ go install github.com/kahing/goofys
```

Failed with:

`./main.go:215: cannot use func literal (type func(*cli.Context) error) as type func(*cli.Context) in assignment`

We were previously building against commit a01c2a3274bbbc9ddeb0e34e8a148ccd72247d94 which I re-installed with succesfully.

Any suggestions?

**Comment by kahing** [comment]
What version of go are you building with?

**Comment by minty** [comment]
We were using https://storage.googleapis.com/golang/go1.6.linux-amd64.tar.gz

I upgraded (which did not fix this error) to https://storage.googleapis.com/golang/go1.7.1.linux-amd64.tar.gz

```
$ go version
go version go1.6 linux/amd64

$ cd /tmp
$ wget https://storage.googleapis.com/go1.7.1.linux-amd64.tar.gz
$ cd /usr/local
$ rm -rf go
$ tar xzf /tmp/go1.7.1.linux-amd64.tar.gz
$ rm /tmp/go1.7.1.linux-amd64.tar.gz
$ GOPATH=/usr/local/gopath
$ mkdir -p $GOPATH
$ cat <<-HEREDOC > /etc/profile.d/golang.sh
    export PATH=$PATH:/usr/local/go/bin
    export GOPATH=$GOPATH
HEREDOC

$ go version
go version go1.7.1 linux/amd64
```

Same error when upgrading goofys:

```
$ rm -rf $GOPATH/src/github.com/kahing/goofys
$ go get -d github.com/kahing/goofys
$ cd $GOPATH/src/github.com/kahing/goofys/
$ git checkout -b f071ec5b5eaec515542f37c3bd4356b23a33941b f071ec5b5eaec515542f37c3bd4356b23a33941b
$ go install github.com/kahing/goofys

./main.go:215: cannot use func literal (type func(*cli.Context) error) as type func(*cli.Context) in assignment
```

Is there something else `go` related that I might need to upgrade?  

The problem is repeatable and I can "fix" it by downgrading `go` to version 1.6 and downgrading goofys to the older commit `a01c2a3`

**Comment by kahing** [comment]
I am not able to reproduce this problem when I start out with a clean `$GOPATH`. I think the problem is you need `-u` too update the dependencies too.

**Comment by minty** [comment]
Just to follow up, our install involves first `go get` then `got install`.  We do this so we can ensure we are building against a specific commit.

In any event, adding `-u` as you suggested to the `go get` appears to have resolved the issue for us.  It upgraded cleanly.

Thanks for your help & the excellent goofys 👍 
```
rm -rf $GOPATH/src/github.com/kahing/goofys
go get -u -d github.com/kahing/goofys
cd $GOPATH/src/github.com/kahing/goofys/
git checkout -b f071ec5b5eaec515542f37c3bd4356b23a33941b f071ec5b5eaec515542f37c3bd4356b23a33941b
go install github.com/kahing/goofys
```

**Comment by billyh** [comment]
I had this same problem, go 1.7.4 on MacOS.  -u fixed it for me, too.
