### ISSUE TITLE
Goofys as a samba share

### ISSUE THREAD

**Issue by gadhamak** [kahing/goofys#115]
Hello. I mounted an s3 bucket using goofys and made the mount location a samba share. In Windows explorer, I can read the contents of the bucket and can delete files but when I try to add files using Windows Explorer, it says I do not have permission. On the linux server I can add files using the command line with no issues.  Any thoughts? 
Thanks

**Comment by kahing** [comment]
This sounds like a samba issue. Does the samba log say anything interesting?

**Comment by gadhamak** [comment]
Thanks Kahing. I restarted samba and I am able to add drag and drop files to the bucket but with the following settings on the /etc/fstab:
--dir-mode=0777,--filemode=0777
If I exclude --dir-mode from /etc/fstab, I am not able to copy files and perform right-click new file. Filemode has to be 0777 for it to work. If I use 0666 it won't work at least during my tests.

**Comment by gadhamak** [comment]
I am currently comparing s3fs and goofys mounted on different buckets and setup as samba shares. I would transfer the same files to both buckets. I notice that on goofys, would when I drag and drop .zip and .pdf files, some of them would fail while on s3fs it does no. I had the same result if I drag and drop just one of the failing .zip or .pdf file on goofys.
I am using v0.0.8.

**Comment by kahing** [comment]
It's probably failing due to random writes. It's been a while since I dealt with samba but it's pretty typical that they (smb/nfs) can generate out of order writes when they flush files. I realize using s3 as cheap file share is a popular use case but I am not sure if I will have time soon to address this.
