### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by monken** [kahing/goofys#125]
Could you please cut a new release? I'm currently using my own built because of #123 and #121 

Thanks!

**Comment by kahing** [comment]
sure I can do this tonight/tomorrow night. Does goofys have enough users to warrant a mailing list yet?

**Comment by monken** [comment]
Awesome, thanks!
Personally, I'd prefer a twitter account that I could follow.

**Comment by kahing** [comment]
I already have a twitter account (@kahingcheung) but understandably it's a bit noisy. I can look into having one specific for goofys. Sadly @goofys is taken

**Comment by kahing** [comment]
I've signed up for @s3goofys

**Comment by kahing** [comment]
fixed via f8d668c29bbf43aa36acea68e05b493f16f5e990
