### ISSUE TITLE
Possibility of embedding gops agent?

### ISSUE THREAD

**Issue by fsouza** [kahing/goofys#141]
I've been seeing some intermittent issues after running goofys for a while (some weeks, with a bunch of read-only operations). Debugging the issue is hard because goofys doesn't expose much information.

gops (https://github.com/google/gops) can help with debugging go programs, would you consider embedding it on goofys?

It would be something like that in the first line of ``main()``:

```go
agent.Listen(&agent.Options{NoShutdownCleanup: true})
defer agent.Close()
```

"agent" comes from ``import "github.com/google/gops/agent"``.

**Comment by kahing** [comment]
Without knowing much about gops, just glancing its README suggests it's a replacement for jps/jstack? Did it help you debug this problem?

More importantly, there's very little information beyond the README that I can find. What are the security implications for example?

**Comment by fsouza** [comment]
I don't know what jps/jstack is, so I googled it. It does look like the answer is yes, even the names seems to be inspired by jps :)

It didn't help _yet_ in debugging this problem, because I haven't been able to reproduce it consistently, I'm currently waiting for it to happen (literally wishing for the worst). But I'm confident it can help, because I'd be able to at least see what goofys is doing to use all the CPU (strace didn't help much).

re: security implications. gops runs an agent that listens on ``127.0.0.1:0``, so other users in the host are able to introspect internals of a running go process. Are you looking for something else specifically?

**Comment by kahing** [comment]
I was hoping that it would use unix domain socket so at least other users won't be able to probe it. It doesn't seem like a good idea to enable this for everyone? Definitely an interesting tool though.

**Comment by fsouza** [comment]
@kahing makes sense! I have a forked version with gops enabled running at the moment. I'll post the results of my experience here, and with that data we can decide whether making it optional makes sense.

Thank you!
