### ISSUE TITLE
Can goofys be used to connect a S3 compatible object storage(Not AWS S3)?

### ISSUE THREAD

**Issue by weinick** [kahing/goofys#142]
Hi Ka-Hing,
I'm trying to use your powerful tool to connect to a S3 compatible object storage but not S3 service itself. As my understanding, I should use --endpoint parameter to choose connection url and --region parameter to choose region. It doesn't work...I tried to connect the same url with S3FS, it works. So is there any limitation of your parameters?
Thanks.

**Comment by kahing** [comment]
using --endpoint should be sufficient since most non-AWS S3 do not take region parameters. Which S3 are you using and could you post the output of goofys --debug_s3?

**Comment by kahing** [comment]
closing as there's no update from reporter
