### ISSUE TITLE
invalid argument with `-o allow_other`

### ISSUE THREAD

**Issue by AndydeCleyre** [kahing/goofys#152]
This is not the same as #33.

`0.0.10.1.geb7963e`, tested on Arch Linux

```bash
$ goofys --use-content-type --uid "$(id -u andy)" --gid "$(id -g andy)" -o allow_other awesome_bucket awesome_mountpoint
invalid argument
```

```bash
$ goofys --use-content-type --uid "$(id -u andy)" --gid "$(id -g andy)" awesome_bucket awesome_mountpoint
# works!
```

**Comment by kahing** [comment]
if you use `-f` as well you should see better error messages, or check your syslog. In this case I suspec it's because you need to add user_allow_other to /etc/fuse.conf

**Comment by AndydeCleyre** [comment]
100% correct and helpful, thank you.
