### ISSUE TITLE
Goofys DIR Freezes for Magento images

### ISSUE THREAD

**Issue by woggo85** [kahing/goofys#156]
Hi,

This is a bit of a curly one. As of yesterday my Goofys mounted FS freezes when the Magento site tries to insert a new image. Magent opens a JS dialog box to select the images, but doing so, the folder it uses in the mount freezes. All other folders still work OK in the bucket.

I mounted the FS in debug mode and this is the output I get before the freeze.

Feb 24 04:44:03 ip-10-0-0-159 /usr/local/bin/goofys[17033]: fuse.DEBUG Op 0x00000092        connection.go:395] <- GetInodeAttributes (inode 15)
Feb 24 04:44:03 ip-10-0-0-159 /usr/local/bin/goofys[17033]: fuse.DEBUG GetAttributes 15 media/wysiwyg []
Feb 24 04:44:03 ip-10-0-0-159 /usr/local/bin/goofys[17033]: fuse.DEBUG Op 0x00000092        connection.go:474] -> OK ()
Feb 24 04:44:03 ip-10-0-0-159 /usr/local/bin/goofys[17033]: fuse.DEBUG Op 0x00000093        connection.go:395] <- LookUpInode (parent 15, name "\xae\x8a-")
Feb 24 04:44:03 ip-10-0-0-159 /usr/local/bin/goofys[17033]: [46B blob data]

For some reason the parent name is encoded... This seemed odd, as I have confirmed there are no unicode in the folder or file names.

Here is some process information I got when it failed.

root@ip-10-0-0-159:[~]: cat /proc/12579/status 
Name: httpd
State: D (disk sleep)
Tgid: 12579
Ngid: 0
Pid: 12579
PPid: 1
TracerPid: 0
Uid: 48 48 48 48
Gid: 48 48 48 48
FDSize: 64
Groups: 48 
VmPeak:  791452 kB
VmSize:  791256 kB
VmLck:       0 kB
VmPin:       0 kB
VmHWM:   88280 kB
VmRSS:   88280 kB
RssAnon:   81392 kB
RssFile:    6876 kB
RssShmem:      12 kB
VmData:   79748 kB
VmStk:     136 kB
VmExe:     468 kB
VmLib:   59596 kB
VmPTE:     984 kB
VmSwap:       0 kB
Threads: 1
SigQ: 3/59357
SigPnd: 0000000000000100
ShdPnd: 0000000000020300
SigBlk: 0000000000000000
SigIgn: 0000000001001002
SigCgt: 000000018c0046e9
CapInh: 0000000000000000
CapPrm: 0000000000000000
CapEff: 0000000000000000
CapBnd: 0000001fffffffff
CapAmb: 0000000000000000
Seccomp: 0
Cpus_allowed: 7fff
Cpus_allowed_list: 0-14
Mems_allowed: 00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000001
Mems_allowed_list: 0
voluntary_ctxt_switches: 14407
nonvoluntary_ctxt_switches: 6

Looking deeper into the process shows the kernel call it is stuck on:

root@ip-10-0-0-159:[~]: cat /proc/12579/syscall 
6 0x7ffe269b3ca0 0x7ffe269b3b90 0x7ffe269b3b90 0x2d 0x58af7829 0x2 0x7ffe269b6478 0x7f4549c78615

6 == sys_lstat

The below confirms that fuse is waiting for the sys_lstat to return...

root@ip-10-0-0-159:[~]: cat /proc/12579/stack 
[<ffffffffa03f753d>] __fuse_request_send+0x13d/0x2c0 [fuse]
[<ffffffffa03f76d2>] fuse_request_send+0x12/0x20 [fuse]
[<ffffffffa03fd76a>] fuse_lookup_name+0x13a/0x2d0 [fuse]
[<ffffffffa03fd94e>] fuse_lookup+0x4e/0x130 [fuse]
[<ffffffff8120853d>] lookup_real+0x1d/0x50
[<ffffffff81208eb2>] __lookup_hash+0x42/0x60
[<ffffffff816834ab>] lookup_slow+0x42/0xa7
[<ffffffff8120c3d3>] path_lookupat+0x773/0x7a0
[<ffffffff8120c42b>] filename_lookup+0x2b/0xc0
[<ffffffff8120fe47>] user_path_at_empty+0x67/0xc0
[<ffffffff8120feb1>] user_path_at+0x11/0x20
[<ffffffff81203323>] vfs_fstatat+0x63/0xc0
[<ffffffff812038f1>] SYSC_newlstat+0x31/0x60
[<ffffffff81203b7e>] SyS_newlstat+0xe/0x10
[<ffffffff816967c9>] system_call_fastpath+0x16/0x1b
[<ffffffffffffffff>] 0xffffffffffffffff

Now we look where the goofys process is upto in the kernel:

root@ip-10-0-0-159:[~]: cat /proc/16787/stack 
[<ffffffff810f4f34>] futex_wait_queue_me+0xc4/0x120
[<ffffffff810f5aa9>] futex_wait+0x179/0x280
[<ffffffff810f7bae>] do_futex+0xfe/0x5b0
[<ffffffff810f80e0>] SyS_futex+0x80/0x180
[<ffffffff816967c9>] system_call_fastpath+0x16/0x1b
[<ffffffffffffffff>] 0xffffffffffffffff

Just to say again, this issue started out of the blue. No upgrades to the system has been done, and it occurs over my two Dev servers, so it's not isolated to one server. I have upgraded goofys from 0.0.9 to 0.0.10, and it still occurs.

Any ideas how I can track this issue down further please?

**Comment by woggo85** [comment]
Hey,

We have downgraded to version 0.0.8 and it has fixed the issue for now. However we need the --cheap option. Very happy to work with you to debug and solve this issue.

**Comment by kahing** [comment]
how easy is it to reproduce it? having a bit more debug log would be nice. Also, sending SIGQUIT to goofys would force it to quit and dump its stacktraces.

**Comment by woggo85** [comment]
Hey Kahing,

It's easy to reproduce with the Magento software. However I have been unsuccessful in writing my own code to crash it the way Magento does. I wrote various C and PHP to try, but I can't.

I will get a dump fro you today. Thanks so much.

**Comment by kahing** [comment]
Sounds good. If you have a test site where this problem happens, I am happy to do some live debugging at some point too. My email is on my github profile page.

**Comment by woggo85** [comment]
Hello Kahing,

I have finally had time to revisit this issue. I can confirm the issue is occurring on all my instances with 0.0.9 goofys. 

I have issued a kill -3 to the goofys process, but can't find where it dumps the stack to. Any help here?
