### ISSUE TITLE
Mount google cloud storage?

### ISSUE THREAD

**Issue by peixotorms** [kahing/goofys#158]
Any idea on how to mount google cloud storage using goofys?

**Comment by kahing** [comment]
it should just work if you set --endpoint to the S3 endpoint after you enable it in the google dashboard.

**Comment by peixotorms** [comment]
I see, thanks.

There's some info here for future reference: 
https://cloud.google.com/storage/docs/migrating
https://cloud.google.com/storage/docs/interoperability

**Comment by kahing** [comment]
Thanks for the links!

**Comment by forrie** [comment]
Could someone post a CLI example of mounting Google Drive using goofys?   Where do we need to adjust or set something on our Google Dashboard, for example (not everyone will know this).

**Comment by dotslash** [comment]
I dont think goofys works with google drive. This issue is about https://cloud.google.com/storage.
