### ISSUE TITLE
missing uid, giud support ?

### ISSUE THREAD

**Issue by lrkwz** [kahing/goofys#163]
Hello I wish to benefit of uid,gid support but this fails

```sh
$ goofys -f -o allow_other,uid=1000 bucketname /mnt/s3/localbucket
2017/03/13 18:20:26.080288 s3.INFO Switching from region 'us-east-1' to 'eu-central-1'
2017/03/13 18:20:26.276935 main.FATAL Mounting file system: Mount: mount: running fusermount: exit status 1

stderr:
fusermount: mount failed: Invalid argument
```

I see that I can add ```--uid 1000``` but I also need to specify this in /etc/fstab

**Comment by kahing** [comment]
You can't mix goofys flags with -o (the latter are fuse flags). Does specifying --uid=1000 not work in fstab? Note that you need to follow the format in README:

```
goofys#bucket   /mnt/mountpoint        fuse     _netdev,allow_other,--file-mode=0666    0       0
```

**Comment by lrkwz** [comment]
thank you

    goofys#bucket   /mnt/mountpoint        fuse     _netdev,allow_other,--uid=1000    0       0

works fine!
