### ISSUE TITLE
Obvious slow down than s3fs

### ISSUE THREAD

**Issue by karltaidev** [kahing/goofys#164]
I am currently using php cms called Processwire for my project. I have used s3fs to mount the asset folder and found it slowed down the page load from 100-200ms to 300-500ms. And then I switched to goofys but the page load time became 1-5s. The settings are pretty much the same except s3fs with one more option -o use_cache=/tmp.

**Comment by kahing** [comment]
That's very vague. Could you dig deeper to see which operations are slower? Note that goofys does not have an ondisk cache

**Comment by karltai** [comment]
I would like to find the issue out, but I have no idea how do I dig deeper right now, sorry. What I have tried is to disable the debug mode of Processwire and the page load become around 300-400ms while s3fs keeps the speed when debug mode on. If I have further findings I will report here.

**Comment by kahing** [comment]
How many assets are you loading? Are the assets loaded in parallel? How does goofys compare if you disable s3fs cache? Some of these questions can be answered by turning on goofys' debug log.

**Comment by kahing** [comment]
closing, not actionable
