### ISSUE TITLE
can't write 0-byte files 

### ISSUE THREAD

**Issue by andypern** [kahing/goofys#168]
Sometime between `851335aa2c19dd8a36f8a5ce94af7babde6d440f` and now it seems that the ability to write 0-byte files has gone away.  851335aa2c19dd8a36f8a5ce94af7babde6d440f seems to work fine to do a 'touch myfilename', however here's what I get when I do the same with the current commit:

```
# touch file
touch: closing `bug': Input/output error
```

In /var/log/syslog:

```
Apr  3 15:26:48 ubu-12-01 /home/ubuntu/goofys.default.new[28133]: s3.ERROR code=Content Length: header is missing msg=411 request=#012

```

This doesn't seem to occur if I copy a file in place that has data in it.  I can also verify that this error did not surface in the `851335aa2c19dd8a36f8a5ce94af7babde6d440f` commit.

**Comment by kahing** [comment]
I can't reproduce this. Can you post a less abbreviated log and include --debug_fuse as well?

**Comment by andypern** [comment]
Sorry, should have started with all that stuff.  Full debug log from /var/log/syslog here; 

https://gist.github.com/andypern/958eec76750cfda6dfe9a9a56771be98


Environment:

- AWS_ec2 instance ( c3.4xlarge in us-west-2a)
	* Ubuntu 14.04.5 LTS
	* go version go1.8 linux/amd64

- bucket in us-west-2	



My steps:

1.  Build (from master):
```go get github.com/kahing/goofys```

2.  As root, mount:
```./goofys --debug_fuse --endpoint https://s3.amazonaws.com andypern /goofy```

3.  Descend into a 'directory' that already existed in the bucket:
```cd /goofy/cdh```

4.  Create a 0-byte file via 'touch':
```touch issue```
error:
```touch: failed to close ‘issue’: Input/output error```

5.  Test copying a file that has some data to the same location (which succeeds):
```cp /var/log/syslog.1 .```

The debug log is a little messy (since it includes the successful copy of the syslog file), but the highlighted lines here should isolate the issue;

https://gist.github.com/andypern/958eec76750cfda6dfe9a9a56771be98#file-gistfile1-txt-L13-L29

Let me know if additional info is needed..

**Comment by kahing** [comment]
dup of https://github.com/kahing/goofys/issues/157
