### ISSUE TITLE
Question: Encryption of data in motion

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [kahing/goofys#173]
Does goofys support encryption of data in motion between the Linux system and AWS S3. 
If yes, how to set it up?

**Comment by VinayaSathyanarayana** [comment]
@kahing - Your views please.

**Comment by andrewgaul** [comment]
If you use HTTPS your data is encrypted in-flight.

**Comment by kahing** [comment]
goofys by default uses https for S3, so data is encrypted in flight by default
