### ISSUE TITLE
Unable to mount S3 bucket

### ISSUE THREAD

**Issue by janibashamd** [kahing/goofys#179]
Hi Team,

I am unable to mount S3 bucket on local client machine, please check and let me know the issue.

Steps done - 
Server side - Installed Openstack Swift and Swift3

Client side -
1. Installed go and then goofys
[root@gluster ~]# $GOPATH/bin/goofys  --version
goofys version 0.0.10
2. Tried to mount above S3 bucket but no go.
[root@gluster ~]# $GOPATH/bin/goofys  --profile s3 --debug_fuse --debug_s3  --endpoint  http://192.168.12.75:8080/ test /mnt/goofys
main.FATAL invalid argument

Extra info is as below-
[root@vda ~]# swift list
admin-openrc
dhanu
jani
**test**
[root@vda ~]# openstack ec2 credentials list
+----------------------------------+----------------------------------+----------------------------------+----------------------------------+
| Access                           | Secret                           | Project ID                       | User ID                          |
+----------------------------------+----------------------------------+----------------------------------+----------------------------------+
| a60b5b02e3b942bd8dd15a89ed3ba035 | aa834cd38a3d4c18a18eda8597374c0b | 6f48b37e2d98472ba32ae948c76a2a75 | 5fb49a3078ee42798c299fd0717d95f0 |
+----------------------------------+----------------------------------+----------------------------------+----------------------------------+
[root@vda ~]# openstack endpoint list
+----------------------------------+-----------+--------------+--------------+---------+-----------+-------------------------------------------------+
| ID                               | Region    | Service Name | Service Type | Enabled | Interface | URL                                             |
+----------------------------------+-----------+--------------+--------------+---------+-----------+-------------------------------------------------+
| 19e7e79bb11e4180aee93f095666975b | RegionOne | keystone     | identity     | True    | admin     | http://192.168.12.75:35357/v2.0                 |
| 3d31fd50aa424263b6541f9928674fc7 | RegionOne | swift        | object-store | True    | admin     | http://192.168.12.75:8080/v1                    |
| 3ef0929853994a0b9efcdad31612f989 | RegionOne | swift        | object-store | True    | internal  | http://192.168.12.75:8080/v1/AUTH_$(tenant_id)s |
| 456bd8ebd0094f34ba66704a47796b55 | RegionOne | swift        | object-store | True    | public    | http://192.168.12.75:8080/v1/AUTH_$(tenant_id)s |
| 6a72cd536c5f434c9186161884dce3d4 | RegionOne | keystone     | identity     | True    | public    | http://192.168.12.75:5000/v2.0                  |
| 78cfd1ee9ad24a4e902c8d0ba4e430aa | RegionOne | keystone     | identity     | True    | internal  | http://192.168.12.75:5000/v2.0                  |
+----------------------------------+-----------+--------------+--------------+---------+-----------+-------------------------------------------------+

[root@gluster ~]# cat .aws/credentials
[s3]
aws_access_key_id=a60b5b02e3b942bd8dd15a89ed3ba035
aws_secret_access_key=aa834cd38a3d4c18a18eda8597374c0b
[root@gluster ~]#
[root@gluster ~]# ls /mnt/
Apr13  Apr20   glusterfs **goofys**  praclient    veda
[root@gluster ~]#

I tried multiple options still no go.. Not getting even debugs !!!

**Comment by janibashamd** [comment]
Hi,

Any update on this.. Please it's a critical requirement..

**Comment by kahing** [comment]
The error is likely in syslog. Or you can run goofys with ``-f` to see the error message
