### ISSUE TITLE
goofys mount command hangs. 

### ISSUE THREAD

**Issue by prattalu** [kahing/goofys#181]
It just hangs.
Below is the error stack.
[root@hforg-app-i-2112-3 ~]# $GOPATH/bin/goofys --debug_fuse --debug_s3 -f bucket-name:bucket/transfer/files /goofys/transfer
2017/05/15 15:43:56.405831 s3.DEBUG HEAD https://s3.amazonaws.com/bucket-name = 200 [us-east-1]
2017/05/15 15:43:56.405927 s3.INFO anonymous bucket detected
2017/05/15 15:43:56.406450 s3.DEBUG DEBUG: Request s3/HeadObject Details:
---[ REQUEST POST-SIGN ]-----------------------------
HEAD /bucket-name/bucket/transfer/files/0tz6x6k5ewmjn8f1nhefubicnug7j0gp HTTP/1.1
Host: s3.amazonaws.com
User-Agent: aws-sdk-go/1.8.16 (go1.7; linux; amd64)

-----------------------------------------------------
2017/05/15 15:43:56.414120 s3.DEBUG DEBUG: Response s3/HeadObject Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 404 Not Found
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Mon, 15 May 2017 15:43:55 GMT
Server: AmazonS3
X-Amz-Id-2: YXDw1cinUn1gUvlyj0BoMdBc03qAeEWNPIoAyxX6UzXA0C3mMJPPjizDr3X59Ljf+1NouHtvY7c=
X-Amz-Request-Id: 9E6B02A07CF230D1

-----------------------------------------------------
2017/05/15 15:43:56.414303 s3.DEBUG DEBUG: Validate Response s3/HeadObject failed, not retrying, error NotFound: Not Found
        status code: 404, request id: 9E6B02A07CF230D1, host id: YXDw1cinUn1gUvlyj0BoMdBc03qAeEWNPIoAyxX6UzXA0C3mMJPPjizDr3X59Ljf+1NouHtvY7c=
2017/05/15 15:43:56.417347 s3.DEBUG DEBUG: Request s3/ListMultipartUploads Details:
---[ REQUEST POST-SIGN ]-----------------------------
GET /bucket-name?uploads= HTTP/1.1
Host: s3.amazonaws.com
User-Agent: aws-sdk-go/1.8.16 (go1.7; linux; amd64)
Accept-Encoding: gzip

-----------------------------------------------------
2017/05/15 15:43:56.428880 s3.DEBUG DEBUG: Response s3/ListMultipartUploads Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Mon, 15 May 2017 15:43:57 GMT
Server: AmazonS3
X-Amz-Id-2: nQ4/ermwsXJ6VsttBeormgS4WEY8uo8jN4SVbealHlZId1akosmy85US7T+ylUUxWaQcFIgwmrA=
X-Amz-Request-Id: 60AB06FC7C01B885

-----------------------------------------------------
2017/05/15 15:43:56.429219 s3.DEBUG {
  Bucket: "bucket-name",
  IsTruncated: false,
  KeyMarker: "",
  MaxUploads: 1000,
  NextKeyMarker: "",
  NextUploadIdMarker: "",
  UploadIdMarker: ""
}

Any thoughts?

goofys version 0.0.10
fusermount version: 2.9.7
All necessary permissions are there for the bucket. credentials file was updated properly

**Comment by kahing** [comment]
is this the full log? Is the mount accessible? I don't see any error here

**Comment by prattalu** [comment]
yes, this is the full stack. Post this it hangs. I do not see a mount point though df command.

there is a 404 error in response , no other clue

2017/05/15 15:43:56.414120 s3.DEBUG DEBUG: Response s3/HeadObject Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 404 Not Found

**Comment by prattalu** [comment]
Below process runs in backgroud, which run for ever.
ps -ef|grep goofys
root     12228     1  0 15:13 ?        00:00:00 /root/go/projects/goofys/bin/goofys bucket-name /root/goofys
root     12240 12228  0 15:13 ?        00:00:00 fusermount -o fsname=hf-pega-test,default_permissions -- /root/goofys

**Comment by kahing** [comment]
the 404 is normal, we make up a random key just to check if we can access the bucket. What environment are you running this in?

**Comment by prattalu** [comment]
It is on centOS 6.3

**Comment by kahing** [comment]
You may have to investigate a little more. For ex: try stracing the fusermount process to see where it's stuck. Do you use any other fuse-based filesystems and do they work? Is this a fresh install of centos 6.3?

**Comment by prattalu** [comment]
I figured out the issue. Looks like it was being blocked by the antivirus.
Thanks for your support.

**Comment by kahing** [comment]
Could you elaborate more so the next person cam figure it out? Thanks
