### ISSUE TITLE
Need to update aws-sdk-go to fix HTTP/2 protocol error on S3 mock server written in Go

### ISSUE THREAD

**Issue by takadasho** [kahing/goofys#182]
When using goofys to connect S3 mock server written in Go. I was faced with a problem that HEAD request sending by aws-sdk-go is interpreted as HTTP/2 protocol error by server written in Go. This problem was fixed by https://github.com/aws/aws-sdk-go/pull/1266.
This PR is included v1.8.24 release. I'd like you to update aws-sdk-go to v1.8.24.

**Comment by kahing** [comment]
done. just curious, which go s3 mock server is this?

**Comment by takadasho** [comment]
Thank you for handling this issue.

> done. just curious, which go s3 mock server is this?

We made go s3 mock server for testing. This is not open to the public.
