### ISSUE TITLE
Can't rsync to mounted goofys filesystem

### ISSUE THREAD

**Issue by ruffle-b** [kahing/goofys#183]
Weird.....

I have an S3 bucket mounted via Goofys 0.0.11 and I can't rsync files to it :-(

The bucket's on /mnt/pdfdata and I run:

rsync -Havx . /mnt/pdfdata/blah/

from a directory with a bunch of files in it. Rsync generates no errors, says it's copied the files but nothing appears on the mounted bucket.

If I "cp * /mnt/pdfdata/blah/" then the files appear as expected.

**Comment by ruffle-b** [comment]
Updating old version of rsync and changing the way it's checking has made this go away.

**Comment by andrewgaul** [comment]
Could you share which versions of rsync have and address this issue?
