### ISSUE TITLE
Permission denied when attempting to mount s3

### ISSUE THREAD

**Issue by discentem** [kahing/goofys#186]
How might I troubleshoot this? Is `bucket-name` supposed to be a full url?

`sudo $GOPATH/bin/goofys bk-munki /
May 27 17:40:31 Brandons-MBP /Users/brandon/work/bin/goofys[7079]: main.ERROR Unable to access '<bucket-name>': permission denied
May 27 17:40:31 Brandons-MBP /Users/brandon/work/bin/goofys[7079]: main.FATAL Mounting file system: Mount: initialization failed`

Thanks in advance.

**Comment by kahing** [comment]
This means s3 is returning 403, which likely means your credential is not setup correctly. Why are you running goofys under sudo?

**Comment by discentem** [comment]
i'm trying to investigate the credential right now. i can't even list the directory in cyberduck. at first I thought permission denied had something to do with lack of sudo... so no reason for sudo.

**Comment by discentem** [comment]
Okay, I fixed the credential policy to have `AmazonS3ReadOnlyAccess` and I now get:

`Brandons-MBP:~ brandon$ $GOPATH/bin/goofys bk-munki /
2017/05/27 18:04:39.537065 main.FATAL Unable to mount file system, see syslog for details`
and 
`May 27 18:04:39 Brandons-MBP /Users/brandon/work/bin/goofys[7142]: main.FATAL Mounting file system: Mount: newConnection: Init: Reading init op: EOF`

**Comment by discentem** [comment]
with `AmazonS3FullAccess`

`May 27 18:14:11 Brandons-MBP /Users/brandon/work/bin/goofys[7176]: main.ERROR Unable to access 'https': permission denied
May 27 18:14:11 Brandons-MBP /Users/brandon/work/bin/goofys[7176]: main.FATAL Mounting file system: Mount: initialization failed`

**Comment by kahing** [comment]
The second error is because you are specifying https when you only need the bucket name. The first one I am not sure, are you using homebrew build or building from source?

**Comment by discentem** [comment]
not entirely sure which version i am using. i think i've installed both

**Comment by andrewgaul** [comment]
You are trying to mount the bucket `bk-munki` with the root path `/`.  This is unlikely to work for a variety of reasons; try making a directory then using it as the path.

**Comment by discentem** [comment]
My end goal is mount the entire bucket, though when i specify a particular folder, either `./folderA`, `folderA`, or `/folderA`, I get: 

`May 27 22:21:17 Brandons-MBP /Users/brandon/work/bin/goofys[7483]: main.FATAL Mounting file system: Mount: stat ./amazon_s3: no such file or directory`

So, I suppose this is progress.

**Comment by discentem** [comment]
Woo. Works with `$GOPATH/bin/goofys bk-munki .`

Crashes finder for a bit before the actual mount works though.

**Comment by discentem** [comment]
I think I understand now. Thank you for the help!

**Comment by discentem** [comment]
Where is a proper place to mount? Everywhere I have tried breaks finder in odd ways.

**Comment by andrewgaul** [comment]
`/mnt` is the canonical mount directory for temporary mounts if you have root access.  I mount in my home directory with directories named after the bucket name, e.g., `/home/gaul/gaulbackup`.

**Comment by discentem** [comment]
Have you experience any strange behavior with finder crashing due to fuse or this application? I had a lot of trouble with that... though maybe because I mounted in bad places

**Comment by kahing** [comment]
finder problem is beyond the scope of goofys, feel free to continue discussing here though
