### ISSUE TITLE
Question: Minimal permissions needed

### ISSUE THREAD

**Issue by fmunteanu** [kahing/goofys#187]
Hi,

I would like to create an IAM role for an EC2 instance where I mount goofys automatically, as part of a ClodFormation setup. Can you please let me know what are the minimal permissions I need to set?

Regards,

Floren

**Comment by kahing** [comment]
do you want read only or read-write?

**Comment by fmunteanu** [comment]
Read only, I want to mount the bucket and serve static images through Nginx. I plan to create an IAM role with all Get* and List* permissions that I will attach to EC2 instance. Will this suffice?

**Comment by kahing** [comment]
That should be sufficientOn Jun 9, 2017 00:26, Floren Munteanu <notifications@github.com> wrote:Read only, I want to mount the bucket and serve static images through Nginx. I plan to create an IAM role with all Get* and List* permissions that I will attach to EC2 instance. Will this suffice?
