### ISSUE TITLE
Files unable to be accessed via Apache

### ISSUE THREAD

**Issue by Uniblue-FrancescoD** [kahing/goofys#189]
I have mounted the files on /mnt/site/ folder using:

cd / && ./root/go/bin/goofys --uid 1000 --dir-mode 0777 --file-mode 0777 --gid 1 --region MYREGION --profile default BUCKETNAME /mnt/site/

the bucket is mounted perfectly and I am able to read files using the VI and also write.
Apache is able to read another dir but not the dir the bucket is mounted on.

**Comment by kahing** [comment]
you need to use -o allow_other
