### ISSUE TITLE
how to configure swifts3 hostname as --endpoint ?

### ISSUE THREAD

**Issue by chianingwang** [kahing/goofys#194]
Hi Ka-Hing Cheung

I check the previous questions haven't found the relative answer yet.

Here is my question: Does goofys works with swift s3 ? and How can I configure swifts3 host as s3 --endpoint to allow to use goofys ?

For s3cmd
This is my s3cmd ~/.s3cfg
```
[default]
access_key = s3
host_base = cloud.swift.com
host_bucket = cloud.swift.com
secret_key = xxx
signature_v2 = False
```

This is s3 emulation layer test
```
$ s3cmd ls
2009-02-03 16:45  s3://testbucket

$ s3cmd ls s3://testbucket
2017-06-13 23:03     11358   s3://testbucket/LICENSE
2017-06-13 23:02       196   s3://testbucket/Makefile
2017-06-13 22:56      4365   s3://testbucket/NEWS
2017-06-08 23:42      1509   s3://testbucket/PKG-INFO
2017-06-13 22:57      4365   s3://testbucket/README.md
2017-06-13 23:08      6022   s3://testbucket/main.go
```

For goofys
This is my  ~/.aws/credentials
```
[default]
aws_access_key_id = s3
aws_secret_access_key = xxx
```

This is the goofys cmd I tried
```
$ goofys --endpoint http://cloud.swift.com/ testbuckets ~/goofys
2017/06/19 14:44:08.614494 main.FATAL Unable to mount file system, see syslog for details
```

This is tail syslog
```
$ tail /var/log/system.log
Jun 19 14:54:04 MacBook-Pro /usr/local/bin/goofys[22085]: main.ERROR Unable to access 'testbuckets': %!v(PANIC=runtime error: invalid memory address or nil pointer dereference)
Jun 19 14:54:04 MacBook-Pro /usr/local/bin/goofys[22085]: main.ERROR Unable to access 'testbuckets': invalid argument
Jun 19 14:54:04 MacBook-Pro /usr/local/bin/goofys[22085]: main.FATAL Mounting file system: Mount: initialization failed
```

Sorry if the question is too basic and I'm really appreciated your advice.

Thanks,
Johnny

**Comment by charudut** [comment]
Hi @chianingwang , just to clarify, in s3cmd I see your bucket name is *testbucket* but when you are mounting through goofys, you are specifying testbucket*s*, have you tried with testbucket?

**Comment by chianingwang** [comment]
@charudut ~ nice catch, sorry for the typo, i think i just paste it wrong.
```
$ goofys --endpoint http://cloud.swift.com/ testbucket ~/goofys
2017/06/19 20:36:19.378239 main.FATAL Unable to mount file system, see syslog for details
```
syslog
```
Jun 19 20:36:19 MacBook-Pro /usr/local/bin/goofys[33087]: main.ERROR Unable to access 'testbucket': RequestError: send request failed
	caused by: Head http://cloud.swift.com/testbucket/2z04ojkup4j70it7qu8fm9g10anfg6x4: dial tcp 38.140.31.133:80: i/o timeout
Jun 19 20:36:19 MacBook-Pro /usr/local/bin/goofys[33087]: main.FATAL Mounting file system: Mount: initialization failed
```
Since i'm using swift s3, does it work for aws go sdk ? and what's endpoint should be in `--endpoint`

**Comment by kahing** [comment]
does cloud.swift.com support path-based requests instead of virtual host? Is there any reference on their swift implementation? (note that swift.com has nothing to do with openstack swift)

**Comment by chianingwang** [comment]
@kahing Thanks for your response, cloud.swift.com is our swift endpoint but running [s3 emulation middleware](https://www.swiftstack.com/docs/admin/middleware/s3_middleware.html) to support s3 api. I think our swift s3 is supporting both , example as below.
```
### path style
host_bucket = 192.168.190.21
host_base = 192.168.190.21
### virtual hosted-style
host_bucket = %(bucket)s.swift.com
host_base = swift.com
```

**Comment by kahing** [comment]
is cloud.swift.com supposed to resolve to 192.168.190.21 or 38.140.31.133? Note that in your earlier comment:

```
Jun 19 20:36:19 MacBook-Pro /usr/local/bin/goofys[33087]: main.ERROR Unable to access 'testbucket': RequestError: send request failed
	caused by: Head http://cloud.swift.com/testbucket/2z04ojkup4j70it7qu8fm9g10anfg6x4: dial tcp 38.140.31.133:80: i/o timeout
```

**Comment by chianingwang** [comment]
I think it's just external ip and internal ip, I'm in vpn now. Sorry for confusing.

**Comment by kahing** [comment]
from the error, it would seem that goofys is not able to connect to 38.140.31.133:80. Have you tried again with VPN?

**Comment by chianingwang** [comment]
@kahing ya , I try it again and configure /etc/host as well to make sure `testbucket.cloud.swift.com` align with internal ip `192.168.190.21`

```$ goofys --endpoint http://testbucket.cloud.swift.com/ --region US testbucket ~/goofys
2017/06/20 22:21:10.249643 main.FATAL Unable to mount file system, see syslog for details```

 ```Jun 20 22:21:10 MacBook-Pro /usr/local/bin/goofys[51444]: s3.ERROR code=RequestError msg=send request failed, err=Head http://testbucket.cloud.swiftstack.com/testbucket/m26wtde48bsjltwdadiyyrsjwco9k15p: dial tcp 192.168.190.21:80: getsockopt: connection refused
Jun 20 22:21:10 --- last message repeated 1 time ---
Jun 20 22:21:10 MacBook-Pro /usr/local/bin/goofys[51444]: main.ERROR Unable to access 'testbucket': RequestError: send request failed
    caused by: Head http://testbucket.cloud.swiftstack.com/testbucket/m26wtde48bsjltwdadiyyrsjwco9k15p: dial tcp 192.168.190.21:80: getsockopt: connection refused
Jun 20 22:21:10 MacBook-Pro /usr/local/bin/goofys[51444]: main.FATAL Mounting file system: Mount: initialization failed```

I might try to setup a test environment w/o `https` see whether I can make it work. Thanks for your kindly response.

**Comment by kahing** [comment]
```
dial tcp 192.168.190.21:80: getsockopt: connection refused
```
Is the problem here

**Comment by chianingwang** [comment]
I setup a local swift with s3 emulation layer w/o https. It's working ! 
```
goofys --endpoint http://ss02.swiftstack.idv/ --region US jwangtest ~/goofys
```
![image](https://user-images.githubusercontent.com/1863416/27406199-02b02bd6-5689-11e7-992d-7f0410df0bbb.png)
@kahing and @charudut 
Thanks all the helps

**Comment by kahing** [comment]
great! please update if you figured out why production wasn't working so maybe it will help other people

**Comment by charudut** [comment]
@chianingwang, glad you were able to get it to work!
