### ISSUE TITLE
permission denied by reading

### ISSUE THREAD

**Issue by AlexFinn** [kahing/goofys#195]
I use goofys to mount GS bucket.

Command:

`goofys -o allow_other --uid=1001 --gid=1002 --dir-mode=0755 --file-mode=0644 --profile=gs2 -f --endpoint https://storage.googleapis.com bucket-on-gs /mnt/folder`

I get:

`main.INFO File system has been successfully mounted`

I can list files in mounted folder successfully.
But when I try to open file (for example, with `file`) or copy it from mounted folder to the other place I get:

`ERROR: cannot read /mnt/folder/file (Permission denied)`

**Comment by kahing** [comment]
Do you have permission to read the object from the gcs side? What does goofys print out if you enable --debug_s3?

**Comment by AlexFinn** [comment]
Yes, I have permissions to read and write. Other places these credentials work well.
goofys print out with `--debug_s3`: https://gist.github.com/AlexFinn/e567e0c7062ae46bac58398921642f7a

**Comment by kahing** [comment]
looking into this, looks like a problem with GCS' v4 signing

**Comment by AlexFinn** [comment]
yes, I saw all my logs... I'm trying to understand why there is the problems with signing if in another place all works well with the same credentials

**Comment by kahing** [comment]
I think the problem is with the Accept-Encoding header that we add, sending a bug report over to GCS now and will probably try to downgrade to V2 signing for now for GCS

**Comment by AlexFinn** [comment]
thanks :)

**Comment by AlexFinn** [comment]
@kahing 
works well now :)

**Comment by pkerpedjiev** [comment]
I seem to be getting the same error. Log output is here:

https://gist.github.com/pkerpedjiev/2682a7e065663e53fa5e8116395b536f

It strikes my that none of the requests have the Authorization header, although my credentials are in ~/.aws/credentials as expected.

**Comment by kahing** [comment]
this is not the same problem (you are not even using GCS). Note that commenting in old, closed issues means that I am likely to miss them. Please open a new issue.

Your problem is that goofys thinks bucket is public-read:

```
2017/08/31 03:59:33.510178 s3.INFO anonymous bucket detected
```

and we can submit some operations to this bucket (we can head the bucket, list the bucket, but not read the objects). This is probably a case of mis-configured IAM policy, which should be fixed on the S3 side.

To workaround that in goofys, use `--profile default` or some other profile.

**Comment by pkerpedjiev** [comment]
Thanks for the reply! I've opened a new issue here: https://github.com/kahing/goofys/issues/221
