### ISSUE TITLE
AWS go get error "undefined: url.PathUnescape"

### ISSUE THREAD

**Issue by KawasakiJunBusiness** [kahing/goofys#196]
I m trying install at aws ec2.
but not success go get command.

[ec2-user@ip-x-x-x-x ~]$ go get github.com/kahing/goofys
# github.com/kahing/goofys/internal
go/src/github.com/kahing/goofys/internal/handles.go:409: undefined: url.PathUnescape

**Comment by kahing** [comment]
you need go 1.8 or above
