### ISSUE TITLE
Not able to mount with non-root users under /etc/fstab

### ISSUE THREAD

**Issue by ajmsh** [kahing/goofys#202]
In our Continuous Integration System,  Non-root user needs write access to the mount where s3-bucket is mounted. We would like to mount an S3 bucket on startup for a non-root user. I tried following as suggested in README.md

goofys#bucket   /mnt/mountpoint        fuse     _netdev,allow_other,--file-mode=0666    0       0

This mounts as root and I can not find a way to mount for a non-root user under /etc/fstab.

Tried:
goofys#bucket   /mnt/mountpoint        fuse     users,uid=4000,gid=4001_netdev,allow_other,--file-mode=0666    0       0
 which resulted into Invalid arguments.

Error:
/root/gocode/bin/goofys[51916]: main.FATAL Mounting file system: Mount: mount: running fusermount: exit status 1#012#012stderr:#012fusermount: mount failed: Invalid argument#012

**Comment by kahing** [comment]
your second command is malformed:

```
 goofys#bucket /mnt/mountpoint fuse users,uid=4000,gid=4001_netdev,allow_other,--file-mode=0666 0 0
```

Did you mean:
```
 goofys#bucket /mnt/mountpoint fuse --uid=4000,--gid=4001,_netdev,allow_other,--file-mode=0666 0 0
```

Probably also want to use something other than 0666 as the default permission. I should change the README...

**Comment by ajmsh** [comment]
@kahing This worked. Thank you so much for your prompt reply.
#bucket /mnt/mountpoint fuse --uid=4000,--gid=4001,_netdev,allow_other,--file-mode=0755 0 0
