### ISSUE TITLE
E297: Write error in swap file

### ISSUE THREAD

**Issue by expitly** [kahing/goofys#209]
Hello,

When creating a file in the mounted path, [**E297: Write error in swap file**] occurs.

Is it impossible to modify a file in a mounted path?

Thanks,

**Comment by kahing** [comment]
Did the error happen during create or modify? Only sequential write is supported so this depends on how the file was written. I don't know what kind of swap file you are trying to create or the kind of application is creating it so I can't tell if this is supposed to work.

Please include the output of --debug_fuse and also describe what you are doing

**Comment by expitly** [comment]
debug_fuse output 
=====================================
2017/08/01 20:38:07.575782 fuse.DEBUG Op 0x0000460d        connection.go:395] <- WriteFile (inode 7, handle 26, offset 2018503, 43 bytes)
2017/08/01 20:38:07.575878 fuse.DEBUG WriteFile 7 logs/tomcat1/user_log/ets_user.log [2018503 43]
2017/08/01 20:38:07.575899 fuse.DEBUG Op 0x0000460d        connection.go:476] -> Error: "invalid argument"
2017/08/01 20:38:07.576092 fuse.DEBUG Op 0x0000460e        connection.go:395] <- WriteFile (inode 7, handle 26, offset 2018503, 43 bytes)
2017/08/01 20:38:07.576408 fuse.DEBUG WriteFile 7 logs/tomcat1/user_log/ets_user.log [2018503 43]
2017/08/01 20:38:07.576448 fuse.DEBUG Op 0x0000460e        connection.go:476] -> Error: "invalid argument"
2017/08/01 20:38:07.576633 fuse.DEBUG Op 0x0000460f        connection.go:395] <- WriteFile (inode 7, handle 26, offset 2018503, 43 bytes)
2017/08/01 20:38:07.576914 fuse.DEBUG WriteFile 7 logs/tomcat1/user_log/ets_user.log [2018503 43]
2017/08/01 20:38:07.576935 fuse.DEBUG Op 0x0000460f        connection.go:476] -> Error: "invalid argument"
2017/08/01 20:38:07.577081 fuse.DEBUG Op 0x00004610        connection.go:395] <- WriteFile (inode 7, handle 26, offset 2018503, 43 bytes)
2017/08/01 20:38:07.577424 fuse.DEBUG WriteFile 7 logs/tomcat1/user_log/ets_user.log [2018503 43]
2017/08/01 20:38:07.577443 fuse.DEBUG Op 0x00004610        connection.go:476] -> Error: "invalid argument"
.
.
.
=====================================

Hello.

I use it to take logs. I want to use log4j to store the spring log in the mounted location.

**Comment by kahing** [comment]
closing, probably a use case that goofys doesn't support
