### ISSUE TITLE
special charactor(&) in filename cause v2  signing failed

### ISSUE THREAD

**Issue by hit1943** [kahing/goofys#210]
hi, kahing, thanks for your good job in goofys

i use goofys for my own s3 compatible storage.
i found a bug:special charactor('@') in filename cause v2  signing failed

for example:
[root@tc-server data2]# touch b@.txt
touch: cannot touch ‘b@.txt’: Permission denied

for a filename： "b@.txt"，the string used for signing is "b@.txt"，but the uri sended by aws-sdk-go is "b%40.txt"
then our storage gateway receives the  uri and calc the signature by "b%40.txt"

my solution is : 
v2signer.go

import (
        .......
	**"github.com/aws/aws-sdk-go/private/protocol/rest"**
)

func (v2 *signer) Sign() error {
        ......
	uri := v2.Request.URL.Opaque
	if uri != "" {
		if questionMark := strings.Index(uri, "?"); questionMark != -1 {
			uri = uri[0:questionMark]
		}
		uri = "/" + strings.Join(strings.Split(uri, "/")[3:], "/")
	} else {
		uri = v2.Request.URL.Path
	}
	**path := rest.EscapePath(uri, false)**
        ......
}

**Comment by kahing** [comment]
thanks @hit1943 !
