### ISSUE TITLE
how to set 'region' option in /etc/fstab 

### ISSUE THREAD

**Issue by ryanking8215** [kahing/goofys#211]
My s3 is in `cn-north-1` region. `--region` option must be set when mounting the s3 through goofys, otherwise it takes long time to detect automatically.

Could you please give the suggestion that how to set `region` option in file `/etc/fstab` , which can mount at startup. I didn't find any documents refer to. 

Thanks a lot -).

**Comment by kahing** [comment]
you set it like any other options:

```
goofys#bucket   /mnt/mountpoint        fuse     _netdev,allow_other,--file-mode=0644,--region=cn-north-1    0       0
```
