### ISSUE TITLE
Is it possible to expose goofys as a go package instead?

### ISSUE THREAD

**Issue by ruiyang2015** [kahing/goofys#214]
We are using Go in our env, and would like to directly use goofys as a package instead of wrapping in a syscall, is it possible for Goofys to open the package? currently it is an internal package we can not directly use.

**Comment by kahing** [comment]
What functionalities do you need exposed?

**Comment by ruiyang2015** [comment]
we will only need to programmatically mount a s3 prefix

**Comment by kahing** [comment]
Could you try out dev/api branch? There's an example in example/

**Comment by ruiyang2015** [comment]
thanks so much, will give it a try, really appreciate it.

**Comment by kahing** [comment]
any updates?

**Comment by ruiyang2015** [comment]
seems working for us. thanks so much. one minor thing, the cli package you used "github.com/codegangsta/cli" is renamed to "https://github.com/urfave/cli", we use glide, and sometimes the glide install will failed to following the 301 redirect from github to install the cli package. you might want to update to the new package name.
