### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by arielsalvo** [kahing/goofys#215]
Hi!

I'm currently trying to sync an AWS S3 bucket (in sa-east-1) to a Softlayer S3c bucket with some 70GBs and a big number of files using goofys to mount the source bucket and `aws s3 sync` to write to the destination.
I chose this method because both buckets have different endpoints and I couldn't use just one tool plus awscli seems to be the only one treating directories the right way.

During the sync, everything seems to be fine except goofys' memory use keeps slowly rising until it reaches about 92% and the sync freezes.
If I try to do anything to the mount directory (`ls`, `du`, etc.) the console freezes.

I can only kill goofys and I get this:
```
^C2017/08/17 13:47:28.714976 main.INFO Received interrupt, attempting to unmount...
2017/08/17 13:47:29.527759 main.ERROR Failed to unmount in response to interrupt: fork/exec /bin/fusermount: cannot allocate memory
```

The problem seems to be even without downloading a huge amount of files but only the metadata to compare. In reruns, not many files are copied because I managed to sync about 15GB before everything dies on me.

I'll try to split the work on different subdirs but I thought it could be useful to point this one out to you.

**Comment by kahing** [comment]
How big are these directories? How many files does the 15GB sync represent? What version of goofys?

**Comment by arielsalvo** [comment]
I managed to copy about 100k files, goofys version is 0.0.15-b37d4f8b5fc0a0314a7b7ed66ff76ffa7a365c09

**Comment by kahing** [comment]
About how many files are there total? Also, do you know how much memory goofys was using? 

Optimizing inode memory usage hasn't been a focus so there are probably lots of low hanging fruits.

**Comment by kahing** [comment]
There was a readdir bug in 0.0.15 so you probably want to upgrade to 0.0.16. I just pushed a series of commits that reduced a straightforward `find` memory usage by ~30% or so. Certainly still using too much memory per inode but maybe is sufficient for now?

**Comment by arielsalvo** [comment]
Hi!

Just a followup. I had to use a staging area to sync from one bucket to the other and was able to do it. 
I couldn't use goofys because it kept hanging up, but it did take longer with 0.0.16 when I tried.

I think there is no way the implementation will scale up to a few 100k of files if the metadata is kept in memory. You'll probably need to use a DB.... maybe sqlite, if you want to keep it simple.

**Comment by kahing** [comment]
metadata for inode should only be in memory until the kernel tells us to forget them, that's not any different from other filesystems (like ext4). There's probably a goofys issue here that require more investigations.

Also, when I measured the per-inode usage, according to the struct size it should only be about 200-300 bytes per inode, but in reality (as measured by `top`) it's an order of magnitude higher. need to investigate that more as well.

**Comment by kahing** [comment]
https://github.com/kahing/goofys/issues/64#issuecomment-325984801 is another possible case of this

**Comment by stevebma** [comment]
Hi There,

I'm also experiencing memory leaks.
I have a (single) mounted bucket with approximately 2M objects, totalling to around 1.3 TB.
My application does modest reading / writing on the bucket.

During 'normal' usage (on an instance with 2GB RAM) goofys will currently last around 1 day, after that all available memory (roughly 1.8 GB) is consumed. While running, goofys does release memory back to the OS, but still it appears there is a leak somewhere.

This issue is easily recreated by running **du** on the mountpoint e.g.

`du --apparent-size -h /mnt/mymountpoint`

goofys consumes all memory and crashes after parsing about 1/3 of the directory tree (this takes just a few minutes). Currently I'm using 0.0.17, but with version 0.0.10 I was also losing the mountpoint on a daily basis.

I was able to collect this debug output by running goofys in foreground:

```
...
goroutine 1541024 [semacquire]:
sync.runtime_SemacquireMutex(0xc42013c7dc)
	/usr/local/go/src/runtime/sema.go:62 +0x34
sync.(*Mutex).Lock(0xc42013c7d8)
	/usr/local/go/src/sync/mutex.go:87 +0x9d
github.com/kahing/goofys/internal.(*Goofys).ForgetInode(0xc42013c750, 0x7f29c2b05ff0, 0xc52df8e810, 0xc455f8c890, 0x0, 0x0)
	/home/ec2-user/go/src/github.com/kahing/goofys/internal/goofys.go:677 +0x58
github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).handleOp(0xc4203f2860, 0xc4203f1d40, 0x7f29c2b05ff0, 0xc52df8e810, 0x8c69e0, 0xc455f8c890)
	/home/ec2-user/go/src/github.com/jacobsa/fuse/fuseutil/file_system.go:141 +0x97a
created by github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).ServeOps
	/home/ec2-user/go/src/github.com/jacobsa/fuse/fuseutil/file_system.go:112 +0x12a

goroutine 1543107 [runnable]:
github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).handleOp(0xc4203f2860, 0xc4203f1d40, 0x7f29c2b05ff0, 0xc518898510, 0x8c69e0, 0xc45d943e90)
	/home/ec2-user/go/src/github.com/jacobsa/fuse/fuseutil/file_system.go:119
created by github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).ServeOps
	/home/ec2-user/go/src/github.com/jacobsa/fuse/fuseutil/file_system.go:112 +0x12a
...
```

Many thanks for your help!

**Comment by kahing** [comment]
is this a flat directory with 2M objects?

**Comment by kahing** [comment]
we do seem to be using more memory than expected, looking into this again

**Comment by stevebma** [comment]
No, it's not a flat directory. I have a few hundred directories in my root, each with a bunch of subdirs (max depth about 6). The max number of files in one dir is approximately 10K.

**Comment by kahing** [comment]
Found two problems so far, one is that there's a deadlock in the ForgetInode code path, which led to the backtrace you posted above. After fixing that the next puzzling thing is releasing all the inodes actually didn't reduce memory usage at all.

**Comment by kahing** [comment]
I think the above commits plus https://github.com/jacobsa/fuse/pull/30 should fix the problem. Leaving this open until that PR is merged

**Comment by stevebma** [comment]
Many thanks, I can confirm that the deadlock appears to be resolved with this fix.
