### ISSUE TITLE
Parent directory modification time not updated

### ISSUE THREAD

**Issue by pbrisbin** [kahing/goofys#219]
When I create a new file on S3, it's visible instantly in the mounted filesystem, but the modification time of the new file's parent directory is not updated. When I un/re-mount, the parent's modification time is correct.

```
[xbmc@htpc ~]$ ls -lR /mnt/media/testing
/mnt/media/testing:
total 4
drwxr-xr-x 2 root root 4096 Aug 26 16:03 dir

/mnt/media/testing/dir:
total 1
-rw-r--r-- 1 root root 10 Aug 26 16:02 one.txt
[xbmc@htpc ~]$ # dir/ and dir/one.txt were created together, these timestamps are accurate
[xbmc@htpc ~]$ # in another terminal I'm now going to upload two.txt
[xbmc@htpc ~]$ ls -lR /mnt/media/testing
/mnt/media/testing:
total 4
drwxr-xr-x 2 root root 4096 Aug 26 16:03 dir

/mnt/media/testing/dir:
total 1
-rw-r--r-- 1 root root 10 Aug 26 16:02 one.txt
-rw-r--r-- 1 root root 10 Aug 26 16:04 two.txt
[xbmc@htpc ~]$ # you can see two.txt has a timestamp of 16:04, but dir/'s timestamp didn't change
[xbmc@htpc ~]$ # if i unmount and remount, dir/'s timestamp will be corrected at that point
[xbmc@htpc ~]$ sudo systemctl restart media.service 
[xbmc@htpc ~]$ ls -lR /mnt/media/testing
/mnt/media/testing:
total 4
drwxr-xr-x 2 root root 4096 Aug 26 16:05 dir

/mnt/media/testing/dir:
total 1
-rw-r--r-- 1 root root 10 Aug 26 16:02 one.txt
-rw-r--r-- 1 root root 10 Aug 26 16:04 two.txt
```

This causes a problem with Kodi which looks at directory modification times to know if it should ignore a given directory as part of library-update. When I add new media on S3, even though they're visible in the directory tree right away, I have to un/re-mount it before Kodi will find it.

**Comment by kahing** [comment]
how did you create the file in s3? through the same goofys mountpoint or uploading directly?

**Comment by pbrisbin** [comment]
Uploading directly, `aws s3 cp` in another terminal (on another machine, actually).

**Comment by kahing** [comment]
not sure if there's much goofys can do here. It's possible for us to return a newer mtime, but only if we notice there's a new file, which would mean that you still need to do a `ls` before the mtime on the dir would change. On the other hand, if a new file is written to the mountpoint via goofys, it makes sense that we should update the mtime then.

**Comment by pbrisbin** [comment]
How/when is the mtime of a directory computed now? As a naive user, I would expect an explicit `stat` of the directory to return a correct mtime, even in the face of changes made remotely. Assuming Kodi is doing some (probably C-equivalent) of this operation, that would suit my needs.

However, as someone who understands S3, I know that that would require finding the max mtime of the directory's contents (recursively), I assume, so that could be too slow to be a viable action to take at any time other than initial mount.

**Comment by kahing** [comment]
expecting `stat` to always return the correct mtime is unrealistic, since even a non-recurisve listing of a directory can take a very long time, and goofys can't do that every time someone does a `stat`. Right now goofys always return the mount time as the mtime for directories but we can do better. ie: if a readdir is done and we noticed there are newer files, or if someone had written a file via goofys.
