### ISSUE TITLE
Unable to access mount point as other user with `-o allow_other`

### ISSUE THREAD

**Issue by lrowe** [kahing/goofys#22]
I'm running goofyfs 6c5cf92 on Ubuntu 14.04 on EC2, run with:

    sudo goofys -o allow_other --dir-mode 0555 --file-mode 0444 <bucket> /mnt

I'm not able to access the directory as another user:

    $ sudo ls -dl /mnt
    dr-xr-xr-x 2 root root 4096 Oct 21 21:54 /mnt
    $ ls -dl /mnt
    ls: cannot access /mnt: Permission denied
    $ ls -l /
    ...
    d?????????   ? ?    ?        ?            ? mnt
    ...

Perhaps this is because the fuse option is not set:

    $ mount
    ...
    <bucket> on /mnt type fuse (rw,nosuid,nodev,default_permissions)

With riofs this works and I see:

    $ mount
    ...
    /dev/fuse on /mnt type fuse (rw,nosuid,nodev,default_permissions,allow_other)

**Comment by gugahoi** [comment]
Is this flag `allow_others` still operational? At the moment I have the same problem described by OP where `ec2-user` cannot read an s3 bucket mounted by root via the `user-data` script. The goofys command line help never mentions such a flag in `v0.0.5` tho.

**Comment by cr-solutions** [comment]
Hello,

for me also allow_others not works. How to solve this?
