### ISSUE TITLE
Multiple profiles in ~/.aws/credentials

### ISSUE THREAD

**Issue by soichih** [kahing/goofys#222]
Hello. I have multiple AWS profiles under ~/.aws/credentials. By default, goofys seems to use [default] profile, but is there a way to specify which profile I need to use to access our S3 bucket? Is there an option that I can pass on /etc/fstab?

I currently have following on my /etc/fstab

```
goofys#hcp-openaccess /mnt/hcp-openaccess fuse _netdev,allow_other,--file-mode=0666    0       0
```

**Comment by kahing** [comment]
use `--profile`

**Comment by soichih** [comment]
Where should I add it? I tried this but it doesn't seem to be working

```
goofys#hcp-openaccess,--profile=hcp /mnt/hcp-openaccess fuse _netdev,allow_other,--file-mode=0666    0       0
```

**Comment by kahing** [comment]
```
goofys#hcp-openaccess /mnt/hcp-openaccess fuse _netdev,allow_other,--file-mode=0666,--profile=hcp    0       0
```

**Comment by soichih** [comment]
Thanks. That's what I tried initially, and I am still getting "permission denied" error

> main.ERROR Unable to access 'hcp-openaccess': permission denied

I just tried pkgcloud with the same credential, and I was able to download file. But I couldn't do getFiles() on the root directory. I think the bucket that I am trying to access doesn't allow enumerating files at the root leve, which I believe goofys does when it first gets mounted. If so, it would be nice if goofys can output more specific error message to distinguish between bad credential v.s. valid credential with insufficient authorization to the bucket..

**Comment by kahing** [comment]
goofys does not list objects before the bucket is mounted. Note that when you are mounting via fstab /root/.aws/credentials is read instead of your regular user's ~/.aws/credentials

**Comment by soichih** [comment]
Yes, I have my credentials under /root/.aws/credentials. 

I am seeing similar problem when I try to list files via pkgcloud module.
```
client.getFiles("hcp-openaccess", (err,files)=>{
        if(err) throw err;
        console.dir(files);
});

AccessDenied: Access Denied
    at Request.extractError (/home/hayashis/test/s3/node_modules/aws-sdk/lib/services/s3.js:577:35)
```

But, I can download files if I konw the file name. Following works.

```
client.download({
container: 'hcp-openaccess',
remote: 'HCP/959574/T1w/Diffusion/bvecs'
}).pipe(fs.createWriteStream('bvecs'));

```

Also, downloading file list via public URL doesn't work either.
> http://hcp-openaccess.s3.amazonaws.com/

However, I can list files if I use aws cli
```
 $ aws s3 ls "s3://hcp-openaccess/" --profile=hcp
                           PRE HCP/
                           PRE HCP_1200/
                           PRE HCP_900/
```

I am not sure why file listing doesn't work with goofys / pkgcloud but works fine with aws CLI.

**Comment by kahing** [comment]
well lets rule out the problems one by one. Does it work if you mount goofys from the command line directly instead of through fstab? Also, what's the IAM setting for that bucket?
