### ISSUE TITLE
Empty mounted S3 bucket

### ISSUE THREAD

**Issue by Trashmonk** [kahing/goofys#223]
I have mounted a s3 bucket using the following command:

`sudo ./goofys -v -o "allow_other" --debug_fuse --debug_s3 janoschtestbucket /mnt/s3/`

I get no errors, only the following message, 'goofys version 0.0.17-3d40e98b163a797e800550a30e950dc06f7229b1'. When I go to the mounted folder it is empty. The bucket has files in it and I have been able to successfully mount the bucket using both s3fs and roifs. I have my credentials in the .aws folder. Any help would be great!

**Comment by kahing** [comment]
-v means print the version

**Comment by Trashmonk** [comment]
Ah, I missed that, for some reason I thought that meant verbose. I must have copy pasted it from riofs. It still doesn't explain why the files are no showing up in the mounted folder. Where does goofys write log files, to see if any errors are present.

**Comment by kahing** [comment]
Have you tried without -v? If you use that it prints the version and then exits. Also, by default logging goes to syslog, unless -f is given

**Comment by Trashmonk** [comment]
Thanks that worked! Out of interest where is the syslog written too?

**Comment by kahing** [comment]
/var/log/syslog in most distros
