### ISSUE TITLE
Cannot see mount in df -h if I use cache

### ISSUE THREAD

**Issue by cblackuk** [kahing/goofys#224]
Hi All,

When I mount goofys without cache like this (same via fstab so that is not the problem)

./goofys -f --debug_fuse --debug_s3 -o allow_other --gid "999" --uid "999" --endpoint https://x bucket /opt/x/x

I can see the mount with df -h no problem however... if I add the cache option I can see it twice and only in df -a... but I can still use the mount as if it was mounted properly...

./goofys -f --debug_fuse --debug_s3 --cache "-oallow_other:-ononempty:--free:10%:/opt/zimbra/backup_old/cache" -o allow_other --gid "999" --uid "999" --endpoint https://x bucket /opt/x/x

Sample of df -a:
"bucket                                  -          -          -    - /opt/x/x
/dev/fuse                               0          0          0    - /opt/x/x
"

Any idea why cache is mounting it "twice"? Also if I do it with the -f as I am showing and then cancel it... by doing Ctr + C it will stop the cache and mount it properly and it can be seen via df -h at this point.

I cannot understand why it does it...

**Comment by kahing** [comment]
cache is implemented as another fuse filesystem that's mounted on top of goofys. `df -h` should include the mountpoint, could you paste its output here?

**Comment by cblackuk** [comment]
There is nothing to paste... df -h just shows all the normal mounts whilst df -a will show the bucket mount and /dev/fuse additional mounts. Without cache the bucket mount will show in df -h as normal.

**Comment by kahing** [comment]
I am not sure why it works fine for me. Either way, is there actually an issue here? You can just use `df -ah`?

**Comment by cblackuk** [comment]
@kahing It is not an issue per se but it just looks weird that I have two mounts instead of one... and I also cannot see how much space is taken as it shows everything as 0.

**Comment by kahing** [comment]
S3 doesn't have an API to tell how much space is used. The two mountpoint thing is not something that can be fixed.

**Comment by cblackuk** [comment]
Thanks for clarifying, if it is the way it should be then all good.
