### ISSUE TITLE
Panic on 403 response

### ISSUE THREAD

**Issue by porterjamesj** [kahing/goofys#228]
Hi! Thank you for writing this; it's been both faster and pleasantly more stable than s3fs in my testing for my use case. One issue I've run into with goofys is that sometimes, while processing a 403 response, it panics for reasons that are not clear to me. I am using goofys with [Digital Ocean Spaces](https://blog.digitalocean.com/introducing-spaces-object-storage/), their new S3-compatible storage product, so it's possible it has a bug or is behaving in some weird way that goofys hasn't seen before because real S3 doesn't do it.

In any case though, it should probably handle the error gracefully and not panic :) and I figured you might be interested to see the logs / traceback so you can fix it if you like.

I've uploaded a debug log (with just `--debug_s3`) and the traceback in a [gist](https://gist.github.com/porterjamesj/491023f6f4eb1cc98ac8ada9735fa398). Let me know if any more info would be helpful!

**Comment by kahing** [comment]
how would I reproduce this? Do you know why it's returning 403 during UploadPart? (instead of CreateMultipartUpload)

**Comment by porterjamesj** [comment]
Unfortunately I can't even reproduce it reliably :/ It happens when running [youtube-dl](https://github.com/rg3/youtube-dl) against goofys. Feel free to close! Definitely not expecting a fix, just figured you might want to know. The 403 thing is very weird—it's possible its a Digital Ocean bug.

**Comment by kahing** [comment]
please reopen if it happens again
