### ISSUE TITLE
Directory listings missing `.` and `..` directory entries

### ISSUE THREAD

**Issue by lrowe** [kahing/goofys#23]
I'm running goofyfs 6c5cf92 on Ubuntu 14.04 on EC2.

When I list the fuse mount point or subdirectory I do not see the `.` or `..` directory entries.

    $ sudo ls -la /mnt
    total 0
    dr-xr-xr-x 2 root root 4096 Oct 21 21:54 subdirectory
    ...

I do see these when the bucket is mounted with riofs.

**Comment by kahing** [comment]
thanks for the bug reports!
