### ISSUE TITLE
Inconsistent reads

### ISSUE THREAD

**Issue by abhik** [kahing/goofys#231]
Running `md5sum --check` repeatedly gives different results.

- The error only occurs when there are many processes reading from goofys but doesn't occur every time that is the case. I had to try multiple times to reproduce the error. 
- The files were uploaded many hours prior to this; don't think it's an S3 eventual-consistency issue.

I'd rather not post the logs publicly but can email presigned S3 URL.

```sh
## Mounting read-only
$ goofys --version
goofys version 0.0.17-3d40e98b163a797e800550a30e950dc06f7229b1
$ goofys -o ro --debug_s3 --debug_fuse XXX /s3/XXX

## Step1: same file md5sum OK and FAILED!!
$ cd /s3/XXX/YYY/ZZZ
$ for i in `seq 5`; do md5sum --check MD5.txt; done;
BLIB00331_USPD16082603-3_H3HGGCCXY_L3_1.fq.gz: FAILED  # <---
BLIB00331_USPD16082603-3_H3HGGCCXY_L3_2.fq.gz: OK
BLIB00331_USPD16082603-3_H3HFWCCXY_L6_1.fq.gz: OK
BLIB00331_USPD16082603-3_H3HFWCCXY_L6_2.fq.gz: OK
md5sum: WARNING: 1 computed checksum did NOT match
BLIB00331_USPD16082603-3_H3HGGCCXY_L3_1.fq.gz: OK      # <---
BLIB00331_USPD16082603-3_H3HGGCCXY_L3_2.fq.gz: OK
BLIB00331_USPD16082603-3_H3HFWCCXY_L6_1.fq.gz: OK
BLIB00331_USPD16082603-3_H3HFWCCXY_L6_2.fq.gz: OK
BLIB00331_USPD16082603-3_H3HGGCCXY_L3_1.fq.gz: OK
BLIB00331_USPD16082603-3_H3HGGCCXY_L3_2.fq.gz: OK
BLIB00331_USPD16082603-3_H3HFWCCXY_L6_1.fq.gz: OK
BLIB00331_USPD16082603-3_H3HFWCCXY_L6_2.fq.gz: OK
BLIB00331_USPD16082603-3_H3HGGCCXY_L3_1.fq.gz: OK
BLIB00331_USPD16082603-3_H3HGGCCXY_L3_2.fq.gz: OK
BLIB00331_USPD16082603-3_H3HFWCCXY_L6_1.fq.gz: OK
BLIB00331_USPD16082603-3_H3HFWCCXY_L6_2.fq.gz: OK
BLIB00331_USPD16082603-3_H3HGGCCXY_L3_1.fq.gz: OK
BLIB00331_USPD16082603-3_H3HGGCCXY_L3_2.fq.gz: OK
BLIB00331_USPD16082603-3_H3HFWCCXY_L6_1.fq.gz: OK
BLIB00331_USPD16082603-3_H3HFWCCXY_L6_2.fq.gz: OK

## Step2: while the above command was running, I also ran other md5sum processes in parallel
## The error in Step1 doesn't occur if not running Step2
## Confirmed (via serial calls to md5sum) that all md5s should be OK.
$ ls /s3/XXX/YYY | parallel -j 12 "cd /s3/XXX/YYY/{}/ && md5sum --check MD5.txt" :::
BLIB00318_USPD16082603-2_H3HGGCCXY_L3_1.fq.gz: OK
BLIB00318_USPD16082603-2_H3HGGCCXY_L3_2.fq.gz: OK
BLIB00318_USPD16082603-2_H3HFWCCXY_L6_1.fq.gz: OK
BLIB00318_USPD16082603-2_H3HFWCCXY_L6_2.fq.gz: OK
BLIB00320_USPD16082603-5_H3HGGCCXY_L3_1.fq.gz: OK
BLIB00320_USPD16082603-5_H3HGGCCXY_L3_2.fq.gz: OK
BLIB00320_USPD16082603-5_H3HFWCCXY_L6_1.fq.gz: OK
BLIB00320_USPD16082603-5_H3HFWCCXY_L6_2.fq.gz: OK
BLIB00329_USPD16082603-19_H3HGGCCXY_L3_1.fq.gz: OK
BLIB00329_USPD16082603-19_H3HGGCCXY_L3_2.fq.gz: OK
BLIB00329_USPD16082603-19_H3HFWCCXY_L6_1.fq.gz: OK
BLIB00329_USPD16082603-19_H3HFWCCXY_L6_2.fq.gz: OK
BLIB00324_USPD16082603-13_H3HGGCCXY_L3_1.fq.gz: OK
BLIB00324_USPD16082603-13_H3HGGCCXY_L3_2.fq.gz: OK
BLIB00324_USPD16082603-13_H3HFWCCXY_L6_1.fq.gz: OK
BLIB00324_USPD16082603-13_H3HFWCCXY_L6_2.fq.gz: FAILED
md5sum: WARNING: 1 computed checksum did NOT match
BLIB00327_USPD16082603-16_H3HGGCCXY_L3_1.fq.gz: OK
BLIB00327_USPD16082603-16_H3HGGCCXY_L3_2.fq.gz: OK
BLIB00327_USPD16082603-16_H3HFWCCXY_L6_1.fq.gz: FAILED
BLIB00327_USPD16082603-16_H3HFWCCXY_L6_2.fq.gz: OK
md5sum: WARNING: 1 computed checksum did NOT match
BLIB00321_USPD16082603-6_H3HGGCCXY_L3_1.fq.gz: OK
BLIB00321_USPD16082603-6_H3HGGCCXY_L3_2.fq.gz: OK
BLIB00321_USPD16082603-6_H3HFWCCXY_L6_1.fq.gz: OK
BLIB00321_USPD16082603-6_H3HFWCCXY_L6_2.fq.gz: OK
BLIB00323_USPD16082603-12_H3HGGCCXY_L3_1.fq.gz: OK
BLIB00323_USPD16082603-12_H3HGGCCXY_L3_2.fq.gz: OK
BLIB00323_USPD16082603-12_H3HFWCCXY_L6_1.fq.gz: FAILED
BLIB00323_USPD16082603-12_H3HFWCCXY_L6_2.fq.gz: OK
md5sum: WARNING: 1 computed checksum did NOT match
BLIB00322_USPD16082603-7_H3HGGCCXY_L3_1.fq.gz: OK
BLIB00322_USPD16082603-7_H3HGGCCXY_L3_2.fq.gz: FAILED
BLIB00322_USPD16082603-7_H3HFWCCXY_L6_1.fq.gz: OK
BLIB00322_USPD16082603-7_H3HFWCCXY_L6_2.fq.gz: OK
md5sum: WARNING: 1 computed checksum did NOT match
BLIB00326_USPD16082603-15_H3HGGCCXY_L3_1.fq.gz: FAILED
BLIB00326_USPD16082603-15_H3HGGCCXY_L3_2.fq.gz: OK
BLIB00326_USPD16082603-15_H3HFWCCXY_L6_1.fq.gz: OK
BLIB00326_USPD16082603-15_H3HFWCCXY_L6_2.fq.gz: OK
md5sum: WARNING: 1 computed checksum did NOT match
BLIB00330_USPD16082603-1_H3HGGCCXY_L3_1.fq.gz: OK
BLIB00330_USPD16082603-1_H3HGGCCXY_L3_2.fq.gz: OK
BLIB00330_USPD16082603-1_H3HFWCCXY_L6_1.fq.gz: OK
BLIB00330_USPD16082603-1_H3HFWCCXY_L6_2.fq.gz: OK
BLIB00325_USPD16082603-14_H3HGGCCXY_L3_1.fq.gz: OK
BLIB00325_USPD16082603-14_H3HGGCCXY_L3_2.fq.gz: OK
BLIB00325_USPD16082603-14_H3HFWCCXY_L6_1.fq.gz: OK
BLIB00325_USPD16082603-14_H3HFWCCXY_L6_2.fq.gz: OK
BLIB00328_USPD16082603-18_H3HGGCCXY_L3_1.fq.gz: FAILED
BLIB00328_USPD16082603-18_H3HGGCCXY_L3_2.fq.gz: OK
BLIB00328_USPD16082603-18_H3HFWCCXY_L6_1.fq.gz: OK
BLIB00328_USPD16082603-18_H3HFWCCXY_L6_2.fq.gz: OK
md5sum: WARNING: 1 computed checksum did NOT match
BLIB00319_USPD16082603-4_H3HGGCCXY_L3_1.fq.gz: FAILED
BLIB00319_USPD16082603-4_H3HGGCCXY_L3_2.fq.gz: OK
BLIB00319_USPD16082603-4_H3HFWCCXY_L6_1.fq.gz: OK
BLIB00319_USPD16082603-4_H3HFWCCXY_L6_2.fq.gz: OK
md5sum: WARNING: 1 computed checksum did NOT match
BLIB00331_USPD16082603-3_H3HGGCCXY_L3_1.fq.gz: OK
BLIB00331_USPD16082603-3_H3HGGCCXY_L3_2.fq.gz: OK
BLIB00331_USPD16082603-3_H3HFWCCXY_L6_1.fq.gz: OK
BLIB00331_USPD16082603-3_H3HFWCCXY_L6_2.fq.gz: OK
```

**Comment by kahing** [comment]
I tried but am not able to reproduce this with the above test case. Could you modify that or let me know how what you are doing is different?

**Comment by abhik** [comment]
The error doesn't occur every time and I haven't been able to come up with a test case that reproduces the error consistently. Note that Step1 and Step2 need to be running concurrently. Also, each file is between 1.5GB to 2.5GB and I was running this on an m4.2xlarge instance.

**Comment by kahing** [comment]
I am still not able to reproduce this even with bigger files (2GB). Could you email me your logs? You can find my email on my github profile

**Comment by kahing** [comment]
Got your logs. Does this happen if you use `--cheap`?

**Comment by abhik** [comment]
> Does this happen if you use --cheap?

I've been testing without `--cheap` but will try with it. I still don't have a way to consistently reproduce this.

**Comment by abhik** [comment]
Some more observations:

I am able to reproduce the bug with test files generated by this [script]( 
https://gist.github.com/abhik/55ac66c09fafdca913310a3e4d1c0621) which creates 4 directories, each with 4 1.5G files and a MD5.txt file. To test, I run `ls -d /path/* | parallel -j <N> "cd {} and md5sum -c MD5.txt"` on a `m4.large` instance.

Note: I can't reproduce the bug 100% consistently; so a negative could be a false-negative.

Can reproduce the bug:

1. Using goofys v.0.0.7 and the latest HEAD (7722712)
2. On bucket with and without S3 Versioning (initial test was on a versioned bucket)
3. With ro and rw mount (initial test was on ro mount)
4. With GNU parallel concurrency (`-j`) same as NCPUS and greater
5. With both `md5sum --check` (output OK or FAILED) and `md5sum` (output md5). 

Cannot reproduce error:

1. Running serially (`parallel -j 1`)
2. Running md5sum many times on one file, even with concurrency far larger than NCPUs.
3. With `--cheap`

**Comment by kahing** [comment]
I looked at this a couple days ago and suspected that there's some error handling problems with the non `--cheap` read. Could you workaround by using `--cheap` for now? I am pretty busy the rest of this week and won't have time to look at this much. non `--cheap` doesn't give much IO benefits if you are doing parallel read yourself anyway.

**Comment by abhik** [comment]
Not all of our workloads are parallel but using `--cheap` is a fine workaround for now.

**Comment by abhik** [comment]
I ran `cat /on-goofys/file | tee file | md5sum` in parallel (w/o `--cheap`) and then diffed one of the files that failed MD5. The diff was a single ~115K block that was all zeros (binary) in the output file. An improper handling of `ErrUnexpectedEOF`?

But, after adding some check in goofys, I couldn't detect it actually returning invalid data. The files used were specially-constructed with incrementing longs (uint32) from 0 to 384 million. Thus, I knew what data to expect at every 4-byte offset. I added the following to `Goofys.ReadData` and it didn't output anything:

```go
if strings.Contains(*fh.inode.Name, "magic") == true {
    for i := int64(0); i <= int64(op.BytesRead) - 4; i += 4 {
        if uint32((op.Offset+i)/4) != binary.BigEndian.Uint32(op.Dst[i:i+4]) {
            fmt.Println("@INVALID DATA", *fh.inode.Name, op.Offset, (op.Offset+i)/4, binary.BigEndian.Uint32(op.Dst[i:i+4]))
        }
    }
}
```

**Comment by kahing** [comment]
I am kind of able to reproduce this locally by faking IO errors, although the behavior I see is perplexing:

```
2017/10/22 12:42:51.662246 fuse.DEBUG ReadFile 17 test_dir/file1 [21954560 131072]
2017/10/22 12:42:51.662310 fuse.DEBUG < readFromReadAhead 17 test_dir/file1 [65536 connection reset by peer]
2017/10/22 12:42:51.662325 fuse.DEBUG < readFile 17 test_dir/file1 [65536 connection reset by peer 1000000000]
2017/10/22 12:42:51.662415 fuse.DEBUG < ReadFile 17 test_dir/file1 [65536 connection reset by peer]
2017/10/22 12:42:51.662653 fuse.DEBUG ReadFile 17 test_dir/file1 [22085632 131072]
2017/10/22 12:42:51.662675 fuse.DEBUG out of order read 17 test_dir/file1 [22085632 22020096]
2017/10/22 12:42:51.664927 fuse.DEBUG < readFromStream 17 test_dir/file1 [3772 <nil>]
2017/10/22 12:42:51.664944 fuse.DEBUG < readFile 17 test_dir/file1 [3772 <nil> 1000000000]
2017/10/22 12:42:51.665018 fuse.DEBUG < readFromStream 17 test_dir/file1 [94532 <nil>]
2017/10/22 12:42:51.665035 fuse.DEBUG < readFile 17 test_dir/file1 [94532 <nil> 1000000000]
2017/10/22 12:42:51.665058 fuse.DEBUG < readFromStream 17 test_dir/file1 [32768 <nil>]
2017/10/22 12:42:51.665072 fuse.DEBUG < readFile 17 test_dir/file1 [32768 <nil> 1000000000]
2017/10/22 12:42:51.665085 fuse.DEBUG < ReadFile 17 test_dir/file1 [131072 <nil>]
2017/10/22 12:42:51.665821 fuse.DEBUG ReadFile 17 test_dir/file1 [22216704 131072]
```

Notice that ReadFile was called at `21954560` for `131072` bytes but we only returned `65536` bytes because an IO error. The missing 64K was never requested again.

This only seems to happen for partial reads. If the failure is at the beginning (0 bytes read) then the offset will be requested again. This surfaced once for #177 but it's not obvious that md5sum is failing here (`lib/md5.c` in `coreutils`):

```C
while (1)
        { 
          n = fread (buffer + sum, 1, BLOCKSIZE - sum, stream);

          sum += n;

          if (sum == BLOCKSIZE)
            break;

          if (n == 0)
            { 
              /* Check for the error flag IFF N == 0, so that we don't
                 exit the loop after a partial read due to e.g., EAGAIN
                 or EWOULDBLOCK.  */
              if (ferror (stream))
                { 
                  free (buffer);
                  return 1;
                }
              goto process_partial_block;
            }

          /* We've read at least one byte, so ignore errors.  But always
             check for EOF, since feof may be true even though N > 0.
             Otherwise, we could end up calling fread after EOF.  */
          if (feof (stream))
            goto process_partial_block;
        }
```

It's true that `md5sum` doesn't check for error if `fread` returns non-zero, but at least the next read offset should be correct. It's possible that `fread` is doing something flunky here, but it's hard to verify since there are too many levels of indirections in glibc. And then there's interaction with the page cache.

The odd thing that goofys is doing here is that it can return a short-read, and but the next read could still be normal. This is probably unexpected outside of EAGAIN or EINTR.

**Comment by kahing** [comment]
duh, that's because I have a defer handler that set the err to nil. it doesn't make a lot of sense and I don't remember why it's there anymore, so I am just going to assume it's a bug when I try to unset EOF (which is necessary since otherwise many tools would complain).

there are more improvements to be made here. for example we should retry the request if we get a disconnect instead of just failing. That's slightly complicated since it's a range get so we will need to retry with the correct range param. We will need to do that regardless of `--cheap`.

As to why you weren't able to reproduce this with `--cheap`, I can only assume that's because without `--cheap`, we use many more connections and so more chance of failure. Locally if I induce read errors I can reproduce the problem with just one thread.

**Comment by kahing** [comment]
(please report back to see if this works for you, hoping to make a release next week)

**Comment by abhik** [comment]
Latest commit has solved the problem for us. Thanks so much!
