### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by segator** [kahing/goofys#238]
I have some questions,
can you limit max cache size? if the cache is full, do you delete older file accesed on the cache drive?
If you umount and remount the cache persist?
How mcachefs check if the cache is still in sync with the backend? (think about sshfs) you cache a file but modified from remote server.
Other question, do you cache the entire file or only accessed blocks?

Thanks!

**Comment by kahing** [comment]
goofys does not use mcachefs, did you mean catfs? `catfs --help`, `goofys --help | grep cache`, and https://github.com/kahing/catfs should answer most of your questions but I will try to address them here.

> can you limit max cache size?

no directly but you can specify amount of free space via `--cache "--free:20G:CACHE_DIR"`

>  if the cache is full, do you delete older file accesed on the cache drive?

yes, catfs uses atime to evict the cache directory

> How catfs check if the cache is still in sync with the backend? (think about sshfs) you cache a file but modified from remote server.

every time a file is opened, it checks the mtime and file size to see if it is the same as when it was cached

> do you cache the entire file or only accessed blocks?

only entire files. if you don't read the entire file it may not be cached
