### ISSUE TITLE
Permission Denied to Mount S3bucket

### ISSUE THREAD

**Issue by mangeshgholap** [kahing/goofys#239]
Hello Everyone,
i am new to this aws setup and just its my start-up project.
Successfully mounted the S3 bucket using goofys. ( Thanks for write-up )
But this Bucket I can create delete files folder using aws console webpage.
Same bucket i have mounted for rendering using Deadline client but its gives me access denied message.
Can anyone send simple policy to read write to all users ?
Bucket mounted via fstab
goofys#fwxdata   /Shares/Y/        fuse     _netdev,allow_other   0       0

Guys need help ..

Thanks

**Comment by kahing** [comment]
This isn't really the right place to ask about IAM but https://github.com/kahing/goofys/issues/136 may help
