### ISSUE TITLE
About Directory permission

### ISSUE THREAD

**Issue by redbox-cdn** [kahing/goofys#240]
Hi I would like to set the 770 Directory permission to mount point.
Is it possible?

```
/usr/local/goofys#bucketname /mnt/data/ fuse _netdev,allow_other,--file-mode=0777,-uid=14,--gid=50 0 0

ls -lah /mnt/data/
drwxr-xr-x  2 ftp  ftp  4.0K Oct  9 03:12 user1
```

I try  this command  but dir permission does not changed.

`chmod 777 /mnt/data/user1`

**Comment by kahing** [comment]
by design goofys does not store permission of objects. You can use `--dir-mode` and `--file-mode` to control what's being returned.

**Comment by gawinwong** [comment]
how to use --dir-mode and --file-mode, the complete order is ?
