### ISSUE TITLE
auto mount fstab or rc.local

### ISSUE THREAD

**Issue by redbox-cdn** [kahing/goofys#242]
Hi I would like to auto mount when Linux server reboot.
Manual mount is OK but it does not auto mount.

I tried rc.local or fstab but it does not solved.
Error message is below (Already set the 2 debug mode) 
```

Oct 11 19:51:22 rbx100 /usr/local/goofys[2014]: s3.INFO Switching from region 'us-east-1' to 'ap-northeast-1'
Oct 11 19:51:29 rbx100 /usr/local/goofys[2014]: s3.ERROR code=NoCredentialProviders msg=no valid providers in chain. Deprecated.#012#011For verbose messaging see aws.Config.CredentialsChainVerboseErrors, err=<nil>#012
Oct 11 19:51:29 rbx100 /usr/local/goofys[2014]: s3.ERROR code=NoCredentialProviders msg=no valid providers in chain. Deprecated.#012#011For verbose messaging see aws.Config.CredentialsChainVerboseErrors, err=<nil>#012
Oct 11 19:51:29 rbx100 /usr/local/goofys[2014]: main.ERROR Unable to access 'bucket': NoCredentialProviders: no valid providers in chain. Deprecated.#012#011For verbose messaging see aws.Config.CredentialsChainVerboseErrors
Oct 11 19:51:29 rbx100 /usr/local/goofys[2014]: main.FATAL Mounting file system: Mount: initialization failed
```

rc.local

```
MOUNT_POINT=/mnt/1/
BUCKET=bucket
OPTION="-o allow_other --file-mode=0777 --dir-mode=0777 -uid=14 --gid=50 --use-content-type --debug_fuse --debug_s3"
/bin/umount ${MOUNT_POINT}
/usr/local/goofys ${OPTION} ${BUCKET} ${MOUNT_POINT}
```

Could you please advice me ?

Best regards.

**Comment by kahing** [comment]
```
Oct 11 19:51:29 rbx100 /usr/local/goofys[2014]: s3.ERROR code=NoCredentialProviders msg=no valid providers in chain. Deprecated.#012#011For verbose messaging see aws.Config.CredentialsChainVerboseErrors, err=<nil>#012
```

do you have `/root/aws/credentials` setup or are you running in EC2 and using IAM?

**Comment by redbox-cdn** [comment]
Hi .

 Yes it already setup /root/.aws/credentials(our Linux is not EC2)
If I logged into console and then,bash /etc/rc.local,  the volume is mount.

here is the credentials 

```
ll /root/.aws/credentials 
-rwx------ 1 root root 116 Oct  5 15:40 /root/.aws/credentials

[default]
aws_access_key_id = xxxxxxxxxx
aws_secret_access_key = yyyyyyyyy
```

**Comment by kahing** [comment]
does this happen if you use `--profile default`?

**Comment by redbox-cdn** [comment]
Hi
 I just tried --profile option but it does not mount.

**Comment by kahing** [comment]
Do you have the new log?

**Comment by redbox-cdn** [comment]
Hi 
The new logs are below
```

Oct 12 11:38:47 rbx100 /usr/local/goofys[2014]: s3.INFO Switching from region 'us-east-1' to 'ap-northeast-1'
Oct 12 11:38:47 rbx100 /usr/local/goofys[2014]: s3.ERROR code=UserHomeNotFound msg=user home directory not found., err=<nil>#012
Oct 12 11:38:47 rbx100 /usr/local/goofys[2014]: s3.ERROR code=UserHomeNotFound msg=user home directory not found., err=<nil>#012
Oct 12 11:38:47 rbx100 /usr/local/goofys[2014]: main.ERROR Unable to access 'bucket': UserHomeNotFound: user home directory not found.
Oct 12 11:38:47 rbx100 /usr/local/goofys[2014]: main.FATAL Mounting file system: Mount: initialization failed
```

It seems that $HOME Environment variable issue??

**Comment by kahing** [comment]
yup that's the problem. try doing `export HOME=/root` in your rc.local. After that, removing `--profile default` should work too

**Comment by redbox-cdn** [comment]
THANKS! Its WORKS!!

**Comment by jl45621** [comment]
Oh man, export HOME=/root bit me too. Cost a few hours. I totally understand its a ridiculous edge case to not have $HOME setup, but could you please add a specific error message for this, eg: main.ERROR Missing HOME folder ? Also -- fantastic tool you have here. Really well done. Couple of off topic things -- 1) I really really like how everything just compiles down to 1 binary 2) I've been using this with AWS Batch and originally had multiple goofys instance's running per machine connected to the same s3 endpoint. This was because I was using it inside docker and had multiple docker per machine. Had some performance problems that way, unsurpisngly, and now I am running it outside of docker on the host and sharing the folder to the docker containers. So far so good. 3) thanks for the tool

**Comment by JaneSoo** [comment]
@kahing I am trying to mount inside ec2 instance and I have set credentials in both /root/.aws/credentials and ~/.aws/credentials. Do you know what the issue is?
I kept getting the same error `NoCredentialProviders`
