### ISSUE TITLE
mount with minio and macFUSE unusable after a few seconds

### ISSUE THREAD

**Issue by D43m0n** [kahing/goofys#252]
I've built `goofys` v0.0.18 from source and try mounting a minio bucket.

When I mount this bucket using that built version, I can see the mount on my desktop and in Terminal. When I create a folder or upload a file, that seems to work ok, but after a few seconds the newly created folder or uploaded file seems to disappear. The mount still seems active at that point, but I don't see any content in the mounted bucket anymore.

When I unmount that bucket and remount it again, I can see the file I uploaded earlier. But here's the funny thing: I've been trying various ways to mount that bucket since things didn't work as expected. I've been using a prefix `bucket:prefix` and have uploaded a file with a prefix. When I try mounting the bucket using the same prefix, I don't see the file anymore. But when I mount the bucket without using that prefix, I can see a folder with the name of that prefix and in that folder I see the file I uploaded earlier. In the Finder I can see the `Textwrangler` icon for the uploaded `.xml` for a brief second and then it turns into a white icon and the mount is useless again.

Weird.

I've built `goofys` from source using:
```$ export GOPATH=$HOME/work
$ go get github.com/kahing/goofys
$ go install github.com/kahing/goofys
```

I even tried a trick by getting the repository first (`go get`) and then checked out the v0.0.18 tag and ran the `go get` and `go install` commands again. I did this since I wasn't sure how to check wether the HEAD was newer than the prerelease of v0.0.18. The behavior is the same, so that trick didn't change anything on that.

I'm running minio `2017-08-05T00:00:53Z` behing a Nginx reverse proxy with Let's Encrypt. I'm running several minio "tenants" exactly the same way for a backup target, they all work fine (which for me rules out a problem with Nginx and minio).

macFUSE v3.7.1 is installed on macOS High Sierra 10.13.1 (17B1003). I don't have homebrew installed.

I can provide logfiles ofcourse. I've been running `goofys` in debug and in foreground mode:
```
./goofys -f --debug_fuse --endpoint https://s3.example.com:443 s3disk ~/s3
```

[goofys_and_macfuse_debug.txt](https://github.com/kahing/goofys/files/1524879/goofys_and_macfuse_debug.txt)

**Comment by kahing** [comment]
minio has strange behavior wrt directories when I last tested it, so I am not entirely surprised that something is broken there. Could you post a step by step reproduction using minio's public instance? I am currently traveling so probably won't be able to verify this until Jan.

**Comment by D43m0n** [comment]
No problem, I'm busy/occupied too at the moment and upcoming weeks, but I'll post a step by step production. Safe travels, and have fun 👍

**Comment by D43m0n** [comment]
Alright, here's wat I've done:

I haven't updated `goofys` on my MacBook, I also didn't update macFUSE. I have updated macOS however to `macOS 10.13.2 (17C88)` but the behaviour with `goofys` and `minio` is the same.

What I did was:

1. Add the minio play credentials to `~/.aws/credentials`: ```[play]
aws_access_key_id = Q3AM3UQ867SPQQA43P2F
aws_secret_access_key = zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG```
2. picked an existing bucket via the browser from https://play.minio.io:9000, `123` in my case.
3. I started `goofys` with the following command line: ```./goofys -f --debug_fuse --endpoint https://play.minio.io:9000 --profile play 123 ~/s3```
4. On my Desktop, the mounted macFUSE  disk appears. I can see in the browser this bucket should contain a file called `jquery.svg` (someone put that there, not me). But in the Finder I don't see that file.
5. I create a new folder in that mount, my MacBook is set to Dutch, which makes it: `naamloze map`. I can briefly see that folder. When I try to change it's name, it disappears. In the browser I can see it exists. When I check my Terminal in which I started `goofys`, it crashed:
```2017/12/21 07:52:45.694887 fuse.DEBUG <-- LookUpInode 1 naamloze map <nil>
2017/12/21 07:52:45.694909 fuse.DEBUG Op 0x00000002        connection.go:479] -> OK (inode 5)
2017/12/21 07:52:45.695011 fuse.DEBUG Op 0x00000005        connection.go:396] <- StatFS
2017/12/21 07:52:45.695068 fuse.DEBUG Op 0x00000005        connection.go:479] -> OK ()
2017/12/21 07:52:45.695173 fuse.DEBUG Op 0x00000006        connection.go:396] <- LookUpInode (parent 1, name "new")
2017/12/21 07:52:45.695217 fuse.DEBUG Inode.LookUp 1  [new]
2017/12/21 07:52:45.855812 fuse.DEBUG <-- LookUpInode 1 new no such file or directory
2017/12/21 07:52:45.855854 fuse.DEBUG Op 0x00000006        connection.go:481] -> Error: "no such file or directory"
2017/12/21 07:52:45.856061 fuse.DEBUG Op 0x00000004        connection.go:396] <- LookUpInode (parent 1, name "new")
2017/12/21 07:52:45.856120 fuse.DEBUG Inode.LookUp 1  [new]
2017/12/21 07:52:46.016917 fuse.DEBUG <-- LookUpInode 1 new no such file or directory
2017/12/21 07:52:46.016960 fuse.DEBUG Op 0x00000004        connection.go:481] -> Error: "no such file or directory"
2017/12/21 07:52:46.017128 fuse.DEBUG Op 0x00000008        connection.go:396] <- LookUpInode (parent 1, name "new")
2017/12/21 07:52:46.017277 fuse.DEBUG Inode.LookUp 1  [new]
2017/12/21 07:52:46.177905 fuse.DEBUG <-- LookUpInode 1 new no such file or directory
2017/12/21 07:52:46.177947 fuse.DEBUG Op 0x00000008        connection.go:481] -> Error: "no such file or directory"
2017/12/21 07:52:46.178115 fuse.DEBUG Op 0x00000003        connection.go:396] <- LookUpInode (parent 1, name "new")
2017/12/21 07:52:46.178178 fuse.DEBUG Inode.LookUp 1  [new]
2017/12/21 07:52:46.338234 fuse.DEBUG <-- LookUpInode 1 new no such file or directory
2017/12/21 07:52:46.338275 fuse.DEBUG Op 0x00000003        connection.go:481] -> Error: "no such file or directory"
2017/12/21 07:52:46.338355 fuse.DEBUG Op 0x00000007        connection.go:396] <- LookUpInode (parent 1, name "naamloze map")
2017/12/21 07:52:46.338443 fuse.DEBUG Ref 5 naamloze map [35]
2017/12/21 07:52:46.338458 fuse.DEBUG <-- LookUpInode 1 naamloze map <nil>
2017/12/21 07:52:46.338482 fuse.DEBUG Op 0x00000007        connection.go:479] -> OK (inode 5)
2017/12/21 07:52:46.338543 fuse.DEBUG Op 0x00000002        connection.go:396] <- LookUpInode (parent 1, name "new")
2017/12/21 07:52:46.338589 fuse.DEBUG Inode.LookUp 1  [new]
2017/12/21 07:52:46.498182 fuse.DEBUG <-- LookUpInode 1 new no such file or directory
2017/12/21 07:52:46.498224 fuse.DEBUG Op 0x00000002        connection.go:481] -> Error: "no such file or directory"
2017/12/21 07:52:46.498325 fuse.DEBUG Op 0x00000005        connection.go:396] <- Rename
2017/12/21 07:52:46.498398 fuse.DEBUG Rename 1  [naamloze map new]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x5c pc=0x4463915]

goroutine 340 [running]:
github.com/kahing/goofys/internal.(*Goofys).Rename(0xc42019c000, 0x488c140, 0xc4202d51a0, 0xc4202a04b0, 0x4888800, 0x461d0c8)
	/Users/me/Documents/workspace/go/src/github.com/kahing/goofys/internal/goofys.go:1103 +0x3e5
github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).handleOp(0xc4202760a0, 0xc420146d00, 0x488c140, 0xc4202d51a0, 0x44bc100, 0xc4202a04b0)
	/Users/me/Documents/workspace/go/src/github.com/jacobsa/fuse/fuseutil/file_system.go:170 +0x203
created by github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).ServeOps
	/Users/me/Documents/workspace/go/src/github.com/jacobsa/fuse/fuseutil/file_system.go:122 +0x176``` 
6. When I rerun `goofys` I can see `naamloze map` in the Finder, but not the `jquery.svg` file in that bucket.

These are the steps I tried using Minio's public instance. If there's anything else you'd like me to try, don't hesitate.
👍

**Comment by kahing** [comment]
I can reproduce the rename crash but not the jquery.svg issue
