### ISSUE TITLE
memory leak during read files from GCS

### ISSUE THREAD

**Issue by AlexFinn** [kahing/goofys#253]
Our app reads files from bucket on GCS.
Folder in bucket has 1001 files, every file is 25535414 bytes... All files in this folder are 23.78 GiB.

When reading is started goofys binary eats more and more memory and crash at the end.
Log: https://gist.github.com/AlexFinn/0b603c95b33608b699e630aa4ece0379

Bucket is mounted as:
`goofys -o allow_other --uid=1001 --gid=1002 -f --profile=gcs --endpoint https://storage.googleapis.com bucket /folder`

**Comment by AlexFinn** [comment]
Also I tested by building the binary with golang 1.9... As I see it works more better.
I will test it some times and maybe it's the solution.

**Comment by kahing** [comment]
What version are you using?

**Comment by AlexFinn** [comment]
0.0.18

**Comment by AlexFinn** [comment]
I built working binary with `go version go1.9.2`

**Comment by kahing** [comment]
did that solve your problem?

**Comment by AlexFinn** [comment]
memory is more spent with time, but still it's much better with golang 1.9.2
maybe later I'll try to find out separately on which it takes a lot of memory
