### ISSUE TITLE
Issue of auto mount using fstab after reboot.

### ISSUE THREAD

**Issue by tonnychang** [kahing/goofys#254]
Hello Kahing,

I got a problem.

I follow this article to install goofys:
http://techiescorner.in/?p=335

After that, I can manually executing: 
/go/projects/goofys/bin/goofys -o nonempty wpgtwspam01 /mnt/s3
works fine.

vi /etc/fstab
/go/projects/goofys/bin/goofys#wpgtwspam01 /mnt/s3 fuse _netdev,allow_other,nonempty,--region=ap-northeast-1,--profile=default,--file-mode=0666 0 0

and then 
mount -a  works fine as well.

but everytime after reboot, the df -h didn't show up the S3.

I've try many different possible methods online, but still got some problems.

the instance is centos 6
default ssh login username is centos, and then sudo su - to root 

is there any way to debug where goes wrong?
Please feel free to tell me if anything I could help, whether to provide information or test.

thanks!

**Comment by kahing** [comment]
Could you add --debug_s3 and see if there's anything interesting in syslog?

**Comment by tonnychang** [comment]
For syslog (centos6 is /var/log/messages), what keyword should I grep?

I couldn't find any related info for either fstab or goofys during reboot.

[1054messages.txt](https://github.com/kahing/goofys/files/1570173/1054messages.txt)

Here is my /etc/fstab

UUID=b48e599f-bd30-4876-9a63-ecd015ba7454 /                       ext4    defaults        1 1
tmpfs                   /dev/shm                tmpfs   defaults        0 0
devpts                  /dev/pts                devpts  gid=5,mode=620  0 0
sysfs                   /sys                    sysfs   defaults        0 0
proc                    /proc                   proc    defaults        0 0
/go/projects/goofys/bin/goofys#wpgtwspam01 /mnt/s3 fuse _netdev,allow_other,nonempty,--region=ap-northeast-1,--profile=default,--debug_s3,--file-mode=0666 0 0

**Comment by kahing** [comment]
Could you try using a wrapper script and redirect the output to a file? For some reason nothing goofys related is in syslog

**Comment by stevebma** [comment]
Are you manually mounting as root? (sudo) 
if not, is your credentials file in /root/.aws/credentials?

(this could explain why manual mount works, and why fstab doesn't)

You could also try running
`umount -a -t fuse && mount -a -t fuse` 

which will try to remount all your fuse fstab entries without requiring a reboot.

**Comment by tonnychang** [comment]
> Could you try using a wrapper script and redirect the output to a file? For some reason nothing goofys related is in syslog

I have no idea how to do that.

> Are you manually mounting as root? (sudo)
not sure, my instance is CentOS release 6.9 (Final)
As AWS suggested, I ssh to it using putty with username 'centos', and then I input sudo su - to get root permissions.

> if not, is your credentials file in /root/.aws/credentials?

yes, I have /root/.aws/credentials:

#cat /root/.aws/credentials
[default]
aws_access_key_id = AKIAIM5*********
aws_secret_access_key = hYpKAJJh3Gl6EuhiH******************




Anyway, i got the solution from aws official, that is creating a script using AWS CLI to achieve auto mount.

# cat /usr/sbin/automount-s3
fusermount -u /mnt/s3
/go/projects/goofys/bin/goofys -o nonempty wpgtwspam01 /mnt/s3

and using crontab to run the script, which works fine.

I think the problem related to permissions, fstab may need some permission while executing, either for root / user, or for fusemount.

**Comment by kahing** [comment]
Could you link to this aws thing where you got the solution from? Also, could you elaborate more about the permission problem?

**Comment by tonnychang** [comment]
I got the solution from aws official by email, which is creating a AWS CLI script as I mentioned.
Actually, the permission problem is just my guess only, since I can manually executing the 'mount -a', which means the fstab can be successfully executed.

**Comment by razielvamp666** [comment]
So, what correct solution for this problem? I don't like to run some custom scripts at startup and test working boot order, etc.

fstab: 
```
# Goofys [S3] FIRST
/opt/go/bin/goofys#first /data/first fuse _netdev,allow_other,--file-mode=0666,--uid=1000,--gid=1000,--debug_s3,--debug_fuse,--region=ap-northeast-2 0 0

# Goofys [S3] SECOND
/opt/go/bin/goofys#second /data/second fuse _netdev,allow_other,--file-mode=0666,--uid=1000,--gid=1000,--debug_s3,--debug_fuse,--region=ap-northeast-2 0 0
```

OS: CentOS 8

Error log:
```
Nov 26 09:29:08 hostname /opt/go/bin/goofys[1088]: s3.INFO Falling back to v2 signer
Nov 26 09:29:08 hostname /opt/go/bin/goofys[1087]: s3.INFO Falling back to v2 signer
Nov 26 09:29:08 hostname /opt/go/bin/goofys[1087]: main.ERROR Unable to access 'first': permission denied
Nov 26 09:29:08 hostname /opt/go/bin/goofys[1087]: main.FATAL Mounting file system: Mount: initialization failed
Nov 26 09:29:08 hostname /opt/go/bin/goofys[1088]: main.ERROR Unable to access 'second': permission denied
Nov 26 09:29:08 hostname /opt/go/bin/goofys[1088]: main.FATAL Mounting file system: Mount: initialization failed
```

I can mount both buckets manually (`mount -a`), but mount at reboot don't working.

Is goofys support fstab?

**Comment by hogagatech** [comment]
For those facing similar problem, I was able to solve mine alternatively with crontab (ubuntu)

`@reboot mount -a`
