### ISSUE TITLE
rsync seems to hang after a while

### ISSUE THREAD

**Issue by mattgodbolt** [kahing/goofys#257]
I'm rsyncing between an NFS mount and a goofys mount. I'm using `rsync --size-only -pLvr src dest` to work around some of the more interesting issues with this.

After a while, the rsync process just hangs. `strace` suggests it's stuck in select:

```
ubuntu@ip-172-30-0-97 ~/compiler-explorer-image> sudo strace -f -p 7667
strace: Process 7667 attached
select(5, [], [4], [], {1, 504421})     = 0 (Timeout)
select(5, [], [4], [], {60, 0}
```

though without further clues I'm not sure if this is a problem on the read side (from NFS) or the write side (to goofys).

Any thoughts on what I might do to diagnose this? It seems somewhat reproducible (this is a 60+GB rsync). Restarting it always seems to carry on, so it doesn't look like I'm hitting any AWS throttles.

I'll strace the whole thing when I next restart.

**Comment by mattgodbolt** [comment]
Also I notice after I ctrl-C the rsync process, I get a huge spam of rename errors of the form:

```
rsync: rename "/opts3/compiler-explorer/OracleDeveloperStudio12.5-linux-x86-bin/developerstudio12.5/lib/compilers/CC-gcc/include/c++/5.1.0/ext/pb_ds/detail/pairing_heap_/.constructors_destructor_fn_imps.hpp.uq9kji" -> "OracleDeveloperStudio12.5-linux-x86-bin/developerstudio12.5/lib/compilers/CC-gcc/include/c++/5.1.0/ext/pb_ds/detail/pairing_heap_/constructors_destructor_fn_imps.hpp": No such file or directory (2)
```

**Comment by jkiebzak** [comment]
I found using "--inplace" helps.

**Comment by mattgodbolt** [comment]
Thanks for the tip about `--inplace` - will use that!

Also, it seems my woes are on the NFS read side and unrelated to goofys. Please close this bug.

(Aside: strace revealed:

```
12305 close(1)                          = 0
12305 lstat("OracleDeveloperStudio12.5-linux-x86-bin/developerstudio12.5/lib/compilers/CC-gcc/include/c++/5.1.0/ext/pb_ds/detail/resize_policy/.hash_load_check_resize_trigger_size_base.hpp.OsHkSn", {st_mode=S_IFREG|0644, st_size=2970, ...}) = 0
12305 rename("OracleDeveloperStudio12.5-linux-x86-bin/developerstudio12.5/lib/compilers/CC-gcc/include/c++/5.1.0/ext/pb_ds/detail/resize_policy/.hash_load_check_resize_trigger_size_base.hpp.OsHkSn", "OracleDeveloperStudio12.5-linux-x86-bin/developerstudio12.5/lib/compilers/CC-gcc/include/c++/5.1.0/ext/pb_ds/detail/resize_policy/hash_load_check_resize_trigger_size_base.hpp") = -1 ENOENT (No such file or directory)
12305 select(5, [0], [4], [0], {60, 0}) = 1 (in [0], left {59, 999997})
12305 read(0, ".\n\n/**\n * @file splay_tree_/eras"..., 1419) = 1419
12305 select(5, [0], [4], [0], {60, 0}) = 1 (in [0], left {59, 999999})
12305 read(0, "_ASSERT(p_nd != 0);\n  splay(p_nd"..., 1571) = 1571
12305 select(5, [], [4], [], {60, 0} <unfinished ...>
12304 <... select resumed> )            = 0 (Timeout)
12304 select(2, [], [1], [], {60, 0} <unfinished ...>
12303 <... select resumed> )            = 0 (Timeout)
```

so I blame NFS/EFS. Which is partly why I'm looking to move to goofys from EFS. But that's another story).

**Comment by kahing** [comment]
indeed https://github.com/kahing/goofys/issues/251#issuecomment-347763099 has more rsync recommendations. S3 is already atomic so not using `--inplace` could cause eventual consistency issue during rename.

**Comment by mattgodbolt** [comment]
Thanks @kahing !
