### ISSUE TITLE
Executable support

### ISSUE THREAD

**Issue by mattgodbolt** [kahing/goofys#258]
Unless I'm much mistaken, there's no way for goofys to support executable files. Is this the case? I was rather hoping to replace my 60+GB set of (read-only!) compiler executables on EFS with goofys, but...

```
ubuntu@ip-172-30-0-97 /opts3> chmod +x moo
ubuntu@ip-172-30-0-97 /opts3> ls -l moo
-rw-r--r-- 1 ubuntu ubuntu 0 Jan  3 18:26 moo
```

Am I overlooking something?

**Comment by kahing** [comment]
goofys doesn't support changing file permissions although you can use `--file-mode` to override the bits.
