### ISSUE TITLE
Unable to write file > 5mb to GCS 

### ISSUE THREAD

**Issue by MinosPong** [kahing/goofys#259]
VERSION:
   0.0.18-2a3ff2a2adbed07472b7902dfca348c5a21bd92b

I am trying to play goofys with GCS and it have error when cp file >5mb

```
> cp largefile /mnt/mount/
cp: error writing ‘/mnt/mount/largefile’: Invalid argument
cp: failed to extend ‘/mnt/mount/largefile’: Invalid argument
cp: failed to close ‘/mnt/mount/largefile’: Invalid argument
```
From capture I see Request
```
POST /bucket/largefile?uploads= HTTP/1.1\r\n
Host: storage.googleapis.com\r\n
Content-Length: 0\r\n
Accept-Encoding: gzip\r\n
... [auth-header skipped here]
```
And Response
```
HTTP/1.1 400 Bad Request\r\n
Content-Type: application/xml; charset=UTF-8
Content-Length: 188
Vary: Origin
Server: UploadServer

<?xml version='1.0' encoding='UTF-8'?><Error><Code>InvalidArgument</Code><Message>Invalid argument.</Message><Details>POST object expects Content-Type multipart/form-data</Details></Error>
```

**Comment by kahing** [comment]
This is because GCS's S3 implementation does not support S3 multipart uploads and instead reinvented another API (ugh). Coincidentally I've started working on a fix for this so stay tuned.

**Comment by kahing** [comment]
Is there a reason why you use goofys instead of gcsfuse?

**Comment by MinosPong** [comment]
Yes, our application is using goofys + s3, and we are migrating it to GCS. 
We want to keep using goofys because of its performance, and align the tech in s3 and gcs application.

**Comment by kahing** [comment]
Could you help me test the latest commit? It seems to work for me in tests and some smallish uploads

**Comment by MinosPong** [comment]
Yes. It looks fine now~~ Thank you for your fast response ^^
