### ISSUE TITLE
allow other issue

### ISSUE THREAD

**Issue by expitly** [kahing/goofys#262]
Hello, 
I want to use allow_other option. but this error occured.
I use 0.0.18 version.

Thanks,

==========================================

goofys -o allow_other aaa /S3

main.FATAL Unable to mount file system, see syslog for details

**Comment by kahing** [comment]
Well what does syslog say?

**Comment by expitly** [comment]
I added 'user_allow_other' in the /etc/fuse.conf file.

It works.

Thanks.
