### ISSUE TITLE
empty mounted folder 

### ISSUE THREAD

**Issue by AlexFinn** [kahing/goofys#266]
```
> goofys --version
goofys version 0.19.0-943e017724ea820eb4185419ef3c41d6f921a324
```

GCS bucket is mount in `/bucket`.
/usr/local/bin/goofys -o allow_other --uid=1001 --gid=1002 --dir-mode=0755 --file-mode=0644 --debug_fuse --profile=gcs -f --endpoint https://storage.googleapis.com bucket_name /bucket

```
> ls -l /bucket/folder/ym=2018-01/dd=20
ls: cannot access '/bucket/folder/ym=2018-01/dd=20': Invalid argument
> ls /bucket/folder/ym=2018-01/dd=20
ls: reading directory '/bucket/folder/ym=2018-01/dd=20': Invalid argument
mapper_histogram.lst     merged-out-000-0133.lst  merged-out-000-0267.lst  merged-out-000-0401.lst  merged-out-001-0035.lst  merged-out-001-0169.lst  merged-out-001-0303.lst
merged-out-000-0000.lst  merged-out-000-0134.lst  merged-out-000-0268.lst  merged-out-000-0402.lst  merged-out-001-0036.lst  merged-out-001-0170.lst  merged-out-001-0304.lst
merged-out-000-0001.lst  merged-out-000-0135.lst  merged-out-000-0269.lst  merged-out-000-0403.lst  merged-out-001-0037.lst  merged-out-001-0171.lst  merged-out-001-0305.lst
merged-out-000-0002.lst  merged-out-000-0136.lst  merged-out-000-0270.lst  merged-out-000-0404.lst  merged-out-001-0038.lst  merged-out-001-0172.lst  merged-out-001-0306.lst
merged-out-000-0003.lst  merged-out-000-0137.lst  merged-out-000-0271.lst  merged-out-000-0405.lst  merged-out-001-0039.lst  merged-out-001-0173.lst  merged-out-001-0307.lst
```

Log with `--debug_fuse`: https://gist.github.com/AlexFinn/c4071053a7d3fb72ca6e6e306fb79c20

**Comment by AlexFinn** [comment]
s3_debug log: https://gist.github.com/AlexFinn/efd5d748039aea5f4f10470cd3b2ab58

**Comment by EssentialMix** [comment]
I guess we experiencing same issue with GCS and goofys. Sometime it can show files, but not all of them or not show at all.
`/images-fast/Projects/MyProject/Builds$ ls
ls: reading directory .: Invalid argument
/images-fast/Projects/MyProject/Builds$ ls
ls: reading directory .: Invalid argument
/images-fast/Projects/MyProject/Builds$`

`2018/01/23 07:05:29.795490 fuse.DEBUG <-- LookUpInode 3589 monit.flag invalid argument
2018/01/23 07:05:29.795529 fuse.DEBUG Op 0x00006817        connection.go:481] -> Error: "invalid argument"
2018/01/23 07:05:29.837422 fuse.DEBUG Op 0x00006818        connection.go:396] <- ForgetInode (inode 3809)`

We tried to use again 0.0.17, but see same issue.

**Comment by donmccasland** [comment]
We are seeing the same issue and we are getting the same issue on 0.0.17 and 0.19.0.  Our message says:
2018/01/23 06:39:38.765026 fuse.DEBUG Op 0x00004001        connection.go:479] -> OK ()
2018/01/23 06:39:38.765797 fuse.DEBUG Op 0x00004002        connection.go:396] <- ReadFile (inode 2772, handle 103, offset 21299200, 131072 bytes)

We're wondering if something has changed in GCS.

**Comment by kahing** [comment]
Wow why do I have so many GCS users? Why aren't you guys using gcsfuse?

@AlexFinn thanks for the debug logs. The other two reports are not actionable.

@AlexFinn seems like your example is for `folder/ym=2018-01/dd=20` but the fuse debug log is for `folder/ym=2018-01/dd=19`? Could you get both fuse and S3 debug log from the same run (I don't see any S3 errors in the s3 debug log)? Does it happen in multiple prefixes? Does it always happen for a particular prefix?

**Comment by AlexFinn** [comment]
Because gcsfuse works much slower, at least, on our tasks the difference is almost twofold. :)
It does in multiple prefixes. I will try to get logs from the same run.
