### ISSUE TITLE
Performance improvement suggestion

### ISSUE THREAD

**Issue by visualgui823** [kahing/goofys#268]
goofys is really a good enough tools for simulating POSIX filesystem for AWS S3. But I still not satisfied the performance.

- Is it possiable to use connection pool to reduce TCP & TLS handshake latence ?
- Is it possiable to limit memory usage by using buffer pool ?

Thanks.

**Comment by kahing** [comment]
really good suggestions, goofys already do both

**Comment by kahing** [comment]
goofys does not create a new process for each cp, each cp is a new process regardless of what it's reading/writing from. In your example, xargs would be the one creating new processes.

The memory usage is limited to 50% of free memory. Please elaborate more about your environment and use case if you are running into a problem.

**Comment by visualgui823** [comment]
After I execute command
`ls| xargs -i cp /local/{} /s3/{}`
Then monitor the networking with command multiple times as below
`sudo netstat -tnp| grep goofys`
I found the tcp connection established to S3 changed frequently.

And in my r4.large(16G) server, goofys takes 15% memory in heavy disk loads, and this server is not a file only server, I need many memory reserved for other services.

Thx

**Comment by kahing** [comment]
Looks like the connection problem is due to https://github.com/golang/go/issues/13801

**Comment by kahing** [comment]
Thanks for the report about connection pooling @visualgui823 !

As for the memory issue, goofys should automatically shrink its footprint as free memory decreases. Is that not working for you? I really need to have more info to figure out if there's anything I need to change

**Comment by kahing** [comment]
note that even after 6b55674433a801daef71168405f1625455aa361b , goofys will still use more than 1 connections for serial operation if S3's domain resolves to a different IP. Probably not worth fixing though

**Comment by visualgui823** [comment]
You are right, whole connections limitation is not necessary, to use connection pool is just for better performance not pool concept.

Thanks for your great support @kahing

**Comment by kahing** [comment]
closing for now, please file a new bug if the memory thing is a problem
