### ISSUE TITLE
total newb question

### ISSUE THREAD

**Issue by michaelberlinphoto** [kahing/goofys#269]
I got to the ***Usage*** portion but don't understand how to actually launch goofys and mount my bucket. I have access keys ready. I'm not sure I understand the syntax of the 'usage' code.

**Comment by kahing** [comment]
You configure goofys the same way you configure aws-cli. Could you be more specific about what you need help with?

**Comment by michaelberlinphoto** [comment]
thanks for responding. i'm in over my head! no need for more help.
