### ISSUE TITLE
Unexpected "Operation not supported" returned when using sequential write

### ISSUE THREAD

**Issue by Francis-Tsui** [kahing/goofys#273]
Hi,

  I have a simple Java application for coping a 1GB file to S3 storage via goofys.

```Java
  FileInputStream fis = new FileInputStream(source);
  int bufferSize = 8 * 1024;
  try (FileOutputStream outputStream = new FileOutputStream(destination)){
            byte[] buffer = new byte[bufferSize];
            int n;
            while((n = fis.read(buffer)) > -1){
                outputStream.write(buffer, 0, n);
            }
   }
```
There is Exception when running outputStream.write

java.io.IOException: Operation not supported
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at demo.rest.RestController.copyFileSimpleGet(RestController.java:80)

It is reported that it is caused by non sequential write operation
"ERROR WriteFile: only sequential writes supported"

I cross checked with the system call used by the application using monitoring tool sysdig
and I do not find any non sequential write operations
``
java (32537:48) > write fd=1103(<f>/opt/goofys/assets/upload/1G.bin) size=8192 
java (32537:48) < write res=8192 data=................................................................................ 
java (32537:48) > write fd=1103(<f>/opt/goofys/assets/upload/1G.bin) size=8192 
java (32537:48) < write res=8192 data=................................................................................ 
java (32537:48) > write fd=1103(<f>/opt/goofys/assets/upload/1G.bin) size=8192 
java (32537:48) < write res=8192 data=................................................................................ 
java (32537:48) > write fd=1103(<f>/opt/goofys/assets/upload/1G.bin) size=8192 
java (32537:48) < write res=8192 data=................................................................................ 
java (32537:48) > write fd=1103(<f>/opt/goofys/assets/upload/1G.bin) size=8192 
java (32537:48) < write res=8192 data=................................................................................ 
java (32537:48) > write fd=1103(<f>/opt/goofys/assets/upload/1G.bin) size=8192 
java (32537:48) < write res=8192 data=................................................................................ 
java (32537:48) > write fd=1103(<f>/opt/goofys/assets/upload/1G.bin) size=8192 
java (32537:48) < write res=8192 data=................................................................................ 
java (32537:48) > write fd=1103(<f>/opt/goofys/assets/upload/1G.bin) size=8192 
java (32537:48) < write res=8192 data=................................................................................ 
java (32537:48) > write fd=1103(<f>/opt/goofys/assets/upload/1G.bin) size=8192 
java (32537:48) < write res=8192 data=................................................................................ 
java (32537:48) > write fd=1103(<f>/opt/goofys/assets/upload/1G.bin) size=8192 
java (32537:48) < write res=-95(EOPNOTSUPP) data=................................................................................ 
java (32537:48) > close fd=1103(<f>/opt/goofys/assets/upload/1G.bin) 
java (32537:48) < close res=-95(EOPNOTSUPP) 
java (32361:21) > close fd=1103(<f>/opt/goofys/assets/upload/1G.bin) 
java (32361:21) < close res=0 
``

Do you know why "Operation not supported" is returned even the sequential write operations are ised?
Is it a bug or anything can do to avoid this.

The latest version of goofys is used.

  Thanks

Regards,
Francis

**Comment by kahing** [comment]
please run goofys with --debug_fuse and attach the log here

**Comment by Francis-Tsui** [comment]
Thanks for the update. The testing version is 
goofys version 0.0.18-2a3ff2a2adbed07472b7902dfca348c5a21bd92b

I attached the file log after enabled --debug_fuse flag

Feb  7 08:49:52 vos-controller-node-i-056bee420c1492703 /usr/local/bin/goofys[6470]: fuse.DEBUG Op 0x00006dde        connection.go:396] <- GetXattr (inode 193, name "security.capability", name security.capability)
Feb  7 08:49:52 vos-controller-node-i-056bee420c1492703 /usr/local/bin/goofys[6470]: fuse.DEBUG Op 0x00006dde        connection.go:481] -> Error: "no data available"
Feb  7 08:49:52 vos-controller-node-i-056bee420c1492703 /usr/local/bin/goofys[6470]: fuse.DEBUG Op 0x00006ddf        connection.go:396] <- WriteFile (inode 193, handle 252, offset 71000064, 8192 bytes)
Feb  7 08:49:52 vos-controller-node-i-056bee420c1492703 /usr/local/bin/goofys[6470]: fuse.DEBUG Op 0x00006ddf        connection.go:479] -> OK ()
Feb  7 08:49:52 vos-controller-node-i-056bee420c1492703 /usr/local/bin/goofys[6470]: fuse.DEBUG Op 0x00006de0        connection.go:396] <- GetXattr (inode 193, name "security.capability", name security.capability)
Feb  7 08:49:52 vos-controller-node-i-056bee420c1492703 /usr/local/bin/goofys[6470]: fuse.DEBUG Op 0x00006de0        connection.go:481] -> Error: "no data available"
Feb  7 08:49:52 vos-controller-node-i-056bee420c1492703 /usr/local/bin/goofys[6470]: fuse.DEBUG Op 0x00006de1        connection.go:396] <- WriteFile (inode 193, handle 252, offset 71008256, 8192 bytes)
Feb  7 08:49:52 vos-controller-node-i-056bee420c1492703 /usr/local/bin/goofys[6470]: fuse.DEBUG Op 0x00006de1        connection.go:479] -> OK ()

Feb  7 08:49:57 vos-controller-node-i-056bee420c1492703 /usr/local/bin/goofys[6470]: fuse.DEBUG WriteFile: only sequential writes supported 193 assets/upload/Francis1.bin [0 107036672]

[goofys_log.zip](https://github.com/kahing/goofys/files/1702396/goofys_log.zip)

**Comment by kahing** [comment]
```
Feb  7 08:49:52 vos-controller-node-i-056bee420c1492703 /usr/local/bin/goofys[6470]: fuse.DEBUG Op 0x00006de1        connection.go:396] <- WriteFile (inode 193, handle 252, offset 71008256, 8192 bytes)
Feb  7 08:49:52 vos-controller-node-i-056bee420c1492703 /usr/local/bin/goofys[6470]: fuse.DEBUG Op 0x00006de1        connection.go:479] -> OK ()
Feb  7 08:49:55 vos-controller-node-i-056bee420c1492703 docker: time="2018-02-07T08:49:55.364126303Z" level=debug msg="Calling GET /version"
Feb  7 08:49:55 vos-controller-node-i-056bee420c1492703 docker: time="2018-02-07T08:49:55.364536827Z" level=debug msg="Calling GET /version"
Feb  7 08:49:57 vos-controller-node-i-056bee420c1492703 /usr/local/bin/goofys[6470]: fuse.DEBUG WriteFile: only sequential writes supported 193 assets/upload/Francis1.bin [0 107036672]

```

It looks like some log lines are missing

**Comment by Francis-Tsui** [comment]
>>It looks like some log lines are missing

What lines are expected? it is all I get from log.
Any other options should be set as parameter for that log?

**Comment by kahing** [comment]
lines from 08:49:52 to 08:49:57 look missing. I also expect log from the fuse protocol layer for offset before "only sequential writes supported".

How are you running goofys? Maybe try running in the terminal instead of through fstab and redirect the output yourself.

**Comment by Francis-Tsui** [comment]
Thanks for the suggestion I uploaded the log following your guideline this time.
It seems it is related to WriteFile and FlushFile.
Please help to take a look.

```
2018/02/09 10:57:18.044146 fuse.DEBUG Op 0x00020288        connection.go:396] <- WriteFile (inode 8, handle 1, offset 539410432, 8192 bytes)
2018/02/09 10:57:18.044461 fuse.DEBUG WriteFile 8 Test/Test/Francis1.bin [539410432 8192]
2018/02/09 10:57:18.044500 fuse.DEBUG Op 0x00020288        connection.go:479] -> OK ()
2018/02/09 10:57:18.044619 fuse.DEBUG Op 0x00020289        connection.go:396] <- FlushFile (inode 8)
2018/02/09 10:57:18.044651 fuse.DEBUG Op 0x0002028a        connection.go:396] <- GetXattr (inode 8, name "security.capability", name security.capability)
2018/02/09 10:57:18.044707 fuse.DEBUG FlushFile 8 Test/Test/Francis1.bin []
2018/02/09 10:57:18.044902 fuse.DEBUG GetXattr 8 Test/Test/Francis1.bin [security.capability]
2018/02/09 10:57:18.044938 fuse.DEBUG Op 0x0002028a        connection.go:481] -> Error: "no data available"
2018/02/09 10:57:18.045025 fuse.DEBUG Op 0x0002028b        connection.go:396] <- WriteFile (inode 8, handle 1, offset 539418624, 8192 bytes)
2018/02/09 10:57:18.045273 fuse.DEBUG WriteFile 8 Test/Test/Francis1.bin [539418624 8192]
2018/02/09 10:57:18.407279 fuse.DEBUG <-- FlushFile 8 Test/Test/Francis1.bin [<nil>]
2018/02/09 10:57:18.407323 fuse.DEBUG Op 0x00020289        connection.go:479] -> OK ()
2018/02/09 10:57:18.407361 fuse.DEBUG WriteFile: only sequential writes supported 8 Test/Test/Francis1.bin [0 539418624]
2018/02/09 10:57:18.407394 fuse.DEBUG Op 0x0002028b        connection.go:481] -> Error: "operation not supported"
2018/02/09 10:57:18.410175 fuse.DEBUG Op 0x0002028c        connection.go:396] <- FlushFile (inode 8)
```

[goofys_fuse_log.zip](https://github.com/kahing/goofys/files/1711557/goofys_fuse_log.zip)

**Comment by Francis-Tsui** [comment]
Is the debug log enough for troubleshooting?

**Comment by kahing** [comment]
Could you show me more of your Java-side code, specifically what's causing FlushFile to be issued? goofys cannot keep writing to a file after it's been flushed (not to be confused with `sync`) but in Java that typically only happens if you close the stream.

**Comment by Francis-Tsui** [comment]
Kahing,

   it is the Java code used to write the file. The FileOutputStream will be closed when the try block end. Hence, close stream is not expected while writing data
```
        if (new File(destination).exists()) {
            throw new FileAlreadyExistsException("File already exists");
        }

        FileInputStream fis = new FileInputStream(source);
        int bufferSize = 8 * 1024;
        try (FileOutputStream outputStream = new FileOutputStream(destination)){
            byte[] buffer = new byte[bufferSize];
            int n;
            while((n = fis.read(buffer)) > -1){
                outputStream.write(buffer, 0, n);
            }
        }

```
   Thanks

Regards,
Francis

**Comment by kahing** [comment]
Could you write a standalone java program that can reproduce this problem?

**Comment by wongfei2009** [comment]
I think the flush is called by JRE implementation automatically. There's no way you can control it explicitly. 

Might be Gooyfs should perform an no-op to flush call to avoid the problem. The remaining buffer will be flushed during close file anyway.

**Comment by kahing** [comment]
I am not able to reproduce this with this java program:

```java
import java.io.*;

public class Cp {

    public static void main(String[] argv) throws Exception {
        String source = argv[0];
        String destination = argv[1];

        if (new File(destination).exists()) {
            throw new RuntimeException("File already exists");
        }

        FileInputStream fis = new FileInputStream(source);
        int bufferSize = 8 * 1024;
        try (FileOutputStream outputStream = new FileOutputStream(destination)){
            byte[] buffer = new byte[bufferSize];
            int n;
            while((n = fis.read(buffer)) > -1){
                outputStream.write(buffer, 0, n);
            }
        }
    }

}
```

**Comment by robparrott** [comment]
We are seeing a similar issue to this one, during a callout from within an application server.

You may need to run the java process as a daemon and run the test over and over in a loop in order to drive the issue. It may be that a short lived java program like this does not drive the behavior because the JRE does not perform the flush at all, or in a manner that drives the issue.

**Comment by dotslash** [comment]
For the sake of completion, let me describe the problem and fix 

- If a process forks it self while holding an open file, the forked process will inherit the file descriptor. So when the forked process exits, it issues a close on the open file. So single open file can have multiple `FlushFile` fuse operations.
- This causes the write failure. 

The fix was to ignore the `FlushFile` op if the opening process and the flushing process is different.

Kahing and I managed to reproduce the issue by making a small change to the program in https://github.com/kahing/goofys/issues/273#issuecomment-366152967. See the java program below. (You can also check the unit test added in the fix [TestClientForkExec](https://github.com/databricks/databricks-goofys/blob/0ed400280f54a9d002e11fab4515652463a37511/internal/goofys_test.go#L1926)) 

```java
import java.io.*;
public class Cp {
    public static void main(String[] argv) throws Exception {
        String source = argv[0];
        String destination = argv[1];
        if (new File(destination).exists()) {
            throw new RuntimeException("File already exists");
        }

        FileInputStream fis = new FileInputStream(source);
        int bufferSize = 8 * 1024;
        try (FileOutputStream outputStream = new FileOutputStream(destination)){
            // !!!!!========= Run some command which causes fork + exec =====!!!!
            Runtime.getRuntime().exec("ls");
            byte[] buffer = new byte[bufferSize];
            int n;
            while((n = fis.read(buffer)) > -1){
                outputStream.write(buffer, 0, n);
            }
        }
    }
}
```
