### ISSUE TITLE
encryption + gzip compression

### ISSUE THREAD

**Issue by thrasibule** [kahing/goofys#281]
I have some files in a bucket which are both encrypted and gzipped. It's using server side encryption aes-256 and they have the metadata Content-Encoding gzip set. I can download them fine from the S3 web interface (i.e. they come back as unencrypted and ungzipped). However when I mount the bucket using goofys, the files stay gzip compressed, I have to manually ungzip them. Is it expected? Is there a setting to change this behavior?

**Comment by kahing** [comment]
That's the expected behavior since the object is in S3 compressed. There's no setting to change this behavior but you can pipe the file to `gzip -d` to uncompress it on the fly
