### ISSUE TITLE
How does the S3 compatibility store set fstab?

### ISSUE THREAD

**Issue by lifans133** [kahing/goofys#282]
I have a S3 compatible storage;
Use: goofys --endpoint http://172.16.200.187:80 franklitest/MNT /bjtest is successful.
Question: how to set fstab under Linux because of the "-endpoint" parameter.

**Comment by kahing** [comment]
you set it like any other options:

```
goofys#bucket    /mnt/point      fuse    _netdev,allow_other,--uid=1001,--gid=1001,--endpoint=http://172.16.200.187:80    0       0
```
