### ISSUE TITLE
Question: what is the best way to watch a goofys mounted s3 directory?

### ISSUE THREAD

**Issue by nitrocode** [kahing/goofys#283]
I'm trying to trigger a shell script when a new directory is created in an S3 bucket. 

My `goofys` volume is mounted on `~/artifacts/` and I'm trying to use a daemonized `inotifywait` to watch the directory to run `~/run.sh` and I'm having issues where the `close_write` event seems to happen constantly thus triggering the script constantly.

```
while inotifywait \
    --daemon \
    -o ~/watch-build.log \
    --event close_write \
    --recursive \
    --monitor ~/artifacts/origin/qa/; do ~/run.sh; done
```

What is the best way to trigger a shell script on a `close_write` change in a `goofys` mounted s3 directory? Is `inotifywait` the best way to do this?

**Comment by kahing** [comment]
Goofys does not general inotify events by itself and I am not sure what's happening here. Are you trying to monitor writes to the same mount point, or are you trying to get notified when a new object is created somewhere else?

**Comment by nitrocode** [comment]
@kahing I'm trying to monitor writes to the local S3 mounted directory. It would be nice to trigger the script based on an `inotify` event but if `goofys` doesn't do that, then a less robust solution would be to add the script to a cron job.

Are `inotify` events on the roadmap?

**Comment by crypticspawn** [comment]
I think the best way to do it, is to use S3 Notification system.

https://docs.aws.amazon.com/AmazonS3/latest/user-guide/enable-event-notifications.html

**Comment by nitrocode** [comment]
@crypticspawn could you go into more detail? I'd imagine using goofys with `inotify` would be easier than SQS or SNS with lambda to do the same thing?

**Comment by nitrocode** [comment]
@crypticspawn interesting. I'll keep that in mind. What I was trying to do was a really hacky deploy that I've since replaced with a better system. I agree with your implementation so thanks for sharing.
