### ISSUE TITLE
Bucket still mounted after deleting the credentials.

### ISSUE THREAD

**Issue by Alageshan-M** [kahing/goofys#290]
I mounted my bucket and deleted the credentials file, still i was able to do all actions. Can you explain how goofys handle this situation. Does it store the credentials anywhere else?. Do we have a limit on number of buckets that can be mounted to a single machine?

**Comment by kahing** [comment]
Are you using IAM?

**Comment by kahing** [comment]
Or are you saying that after you mount, before you terminate goofys, the mount still works? That's expected since goofys read the files at startup.

**Comment by kahing** [comment]
goofys does not impose a limit on how many mounts you can have, although linux/fuse itself certainly does. See http://man7.org/linux/man-pages/man8/mount.fuse.8.html under mount_max for the fuse limit

**Comment by Alageshan-M** [comment]
thanks for the reply, lately im facing an issue which throws an invalid argument error. I have opened a new issue #291 , Please let me know if u need more information
