### ISSUE TITLE
How to use goofys to mount s3 bucket in a container

### ISSUE THREAD

**Issue by vishal24tuniki** [kahing/goofys#293]
I have installed fuse and other dependencies in docker images. But when i try to mount, the process gets stuck
`goofys -o allow_other bucket_name local_dir`

But when i run the same process in foreground using -F, then the mount happens without issue. But i need the process in background

**Comment by powers-alan** [comment]
Experiencing the exact same problem in CentOS 7.3 Docker image.

**Comment by wskinner** [comment]
Not a solution, but I have worked around this issue by mounting the s3 bucket to a directory on the host and injecting it into the container as a volume with `docker run -v`.

**Comment by vishal24tuniki** [comment]
@powers-alan @wskinner 
I got this working by doing the following assuming ubuntu docker
1) Install ca-certificates, fuse, syslog-ng
2) Download goofys binary from github releases of this repo
2) Configure syslog-ng

Then start syslog-ng & use goofys to mount with instructions in docker ENTRYPOINT script

I have raised the issue to see if there is a proper way of doing this. Hello @kahing , can you please help

**Comment by kahing** [comment]
the docker image goofys uses for benchmarking mounts goofys from within the container without issues: https://github.com/kahing/goofys/blob/master/bench/Dockerfile

I can possibly help you look into why it's not working for your case but you need to provide me with a minimal Dockerfile definition where I can reproduce the problem

**Comment by vishal24tuniki** [comment]
@kahing This was my original Dockerfile

```
FROM ubuntu:16.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    fuse \
 && rm -rf /var/lib/apt/lists/* \
 && curl -o /usr/local/bin/goofys -J -L -H "Accept: application/octet-stream" https://github.com/kahing/goofys/releases/download/v0.19.0/goofys \
 && chmod +x /usr/local/bin/goofys \
 && apt-get purge -y --auto-remove \
    curl
COPY app /usr/local/bin
COPY docker-entrypoint.sh /usr/local/bin
ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["--help"]
```

docker-entrypoint.sh
`RECORDING_BUCKET` & `INPUT_BUCKET` are environment variables
```
#!/bin/bash

if [ "$1" == "--help" ]; then
    echo "Usage: something"
    exit 1
fi

export ARCHIVAL_DIR="/opt/archival"
export CONCAT_DIR="/opt/concat"

mkdir -p ${ARCHIVAL_DIR}
mkdir -p ${CONCAT_DIR}

goofys -o allow_other ${RECORDING_BUCKET} ${ARCHIVAL_DIR}
goofys -o allow_other ${INPUT_BUCKET} ${CONCAT_DIR}

output_file="/opt/$6"
app -i $1 -m $2 -p $3 -s $4 -e $5 -o ${output_file}
```

**Comment by rfasouliotis** [comment]
Having a very similar issue as described by @vishal24tuniki. In my case, I am trying to run this in AWS using a container. For some weird reason, the mount hangs when syslog is not running in the container. As soon as I start syslog, and call the mount again, it works fine. This is the same whether I use the foreground method, or calling through fstab (through mount -a or mount /blah).

It's a but hard to troubleshoot as without a logger I can't capture what's happening. As soon as I start the logger, it works :)

**Comment by dprestegard** [comment]
Same issue occurring for me as well. It runs fine with -f, but hangs without it

**Comment by dprestegard** [comment]
@kahing I did figure out a workaround though :)

goofys -f <whatever> &

works just fine in my case!

**Comment by kahing** [comment]
ah that's fixed by https://github.com/kahing/goofys/commit/224a69530a8fefa8f07e51582b928739127134f2 .
