### ISSUE TITLE
Question: What is "filey system"?

### ISSUE THREAD

**Issue by choleraehyq** [kahing/goofys#30]
Hello @kahing , thank you for your great work.
README tells me that Goofys is a "filey" system instead of file system, which I have never heard before. And I cannot google out any valuable information about it. Could you please give me some references about it? Thanks a lot.

**Comment by andrewgaul** [comment]
From the [overview](https://github.com/kahing/goofys/blob/master/README.md#overview):

> It's a Filey System instead of a File System because goofys strives for performance first and POSIX second. Particularly things that are difficult to support on S3 or would translate into more than one round-trip would either fail (random writes) or faked (no per-file permission)

**Comment by choleraehyq** [comment]
@andrewgaul But I can't find out any other information about filey system. Is this concept created by kahing?

**Comment by kahing** [comment]
The concept itself is not new, many (if not all) cloud gateways do not implement the full POSIX. I am merely being explicit about the trade-offs.
