### ISSUE TITLE
Question: S3 mount error often occurs.

### ISSUE THREAD

**Issue by URAGO-Hisaaki** [kahing/goofys#300]
We are mounting the S3 bucket using goofys 0.0.10 in the production environment.

The following error occurred the other day and it became impossible to access the mounted directory.

`/ mnt / mountpoint: Transport endpoint is not connected`

S3 and IAM (e.g. accessibility) have not changed anything.

Is this problem because the version of goofys we use is old, has it been fixed in the latest version?

**Comment by kahing** [comment]
This is a generic error that indicates that goofys crashed, so it's possible that a newer version fixes this. 0.0.10 is quite old and I can't provide support for that anymore. Please re-open with the panic trace if you are able to reproduce this with the newest version

**Comment by DenisBY** [comment]
Still have this issue with
```
# /usr/local/bin/goofys --version
goofys version 0.19.0-943e017724ea820eb4185419ef3c41d6f921a324
```
