### ISSUE TITLE
Possible to mount specific folder?

### ISSUE THREAD

**Issue by abagshaw** [kahing/goofys#304]
I am wanting to use goofys with a GCP Storage Bucket - and am needing to mount a specific folder in my bucket (not the root of the bucket) to a folder on the local system. Is this possible?

**Comment by kahing** [comment]
presumably you closed this because you figured it out, but you can use `bucket:prefix` to mount a specific folder, as per `goofys -h`

```
$ goofys -h
Error: goofys takes exactly two arguments.

NAME:
   goofys - Mount an S3 bucket locally

USAGE:
   goofys [global options] bucket[:prefix] mountpoint
```
