### ISSUE TITLE
goofys <bucket> <mountpoint> KEY SECRET args

### ISSUE THREAD

**Issue by cekvenich** [kahing/goofys#308]
I would like to mount a few 'accounts'. 
Is there a way to pass AWS_KEY and AWS_SECRET to the goofYs command line?

**Comment by kahing** [comment]
you can pass `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` through environmental variables. Another option is have multiple profiles in `~/.aws/credentials` and use `--profile` to switch from them

**Comment by cekvenich** [comment]
How do I use --profile ?
I pass the full path to credentials file?
(no docs I see)

**Comment by benooli** [comment]
@cekvenich  - I did the following and worked for me

added this line to fstab

goofys#MY-BUCKET-HERE     /MOUNT-POINT-HERE    fuse    _netdev,allow_other,--file-mode=0666,--dir-mode=0777,--profile=MYPROFILE 0       0


and in /root/.aws/credentials, I added a section called MYPROFILE with the aws_access_key_id and aws_secret_access_key, like so.


[default]
aws_access_key_id = AAAAAAAAAAA
aws_secret_access_key = BBBBBBBBBB

[MYPROFILE]
aws_access_key_id = CCCCCCCCCCCCCC
aws_secret_access_key = DDDDDDDDDDDDDDDDDD


then mounted /MOINT-POINT-HERE.

All good here.
