### ISSUE TITLE
code request signature does not match

### ISSUE THREAD

**Issue by greerso** [kahing/goofys#31]
Hey,  I've used aws-cli configure to setup my aws credentials but still get the following messages when I attempt to mount:

2015/11/04 23:02:53.910241 s3.ERROR code=The request signature we calculated does not match the signature you provided. Check your key and signing method. msg=403 request=

2015/11/04 23:02:53.910435 s3.ERROR code=The request signature we calculated does not match the signature you provided. Check your key and signing method. msg=403 request=

2015/11/04 23:02:53.910538 s3.INFO Unable to detect bucket region, staying at 'us-west-2'
2015/11/04 23:02:53.914630 main.INFO File system has been successfully mounted.

Can a goofys mount be added to fstab?

**Comment by kahing** [comment]
Does `aws s3` work? Is the clock set correctly?

**Comment by greerso** [comment]
apologies, stupid mistake.  Had no credentials in /root/.aws/credentials and tried to mount as super user.

Will goofys work in fstab or should I will i need to add the mount to rc.local?

Thanks,

**Comment by greerso** [comment]
The file/directory modes are not being set asas spceifed in the command below.  Instead I'm getting dr----x--x

sudo goofys --dir-mode "777" --file-mode "777" --uid "33" --gid "33" --storage-class "STANDARD_IA" bucketname /mnt/mountpoint

**Comment by kahing** [comment]
The modes are ints, try 0777 or convert from base 8. I've not tried to mount from fstab so I can't tell you if it works or not, and won't be able to look into it the next couple days. Do you want to give it a try and report back?

**Comment by greerso** [comment]
using 0777, sort of works, now super user see's the correct permissions set, but even though they're 777 other users see d?????????  ? ?        ?           ?            ?.  --help suggests the three digit number which is why I had made that mistake and may be worth updating.

I have tried the following but get the message:  mount: can't find /mnt/cpirepsarchive.s3/ in /etc/fstab

goofys#bucketname /mnt/mountpoint fuse rw --dir-mode="0777",--file-mode="0777",--uid="33",--gid="33",--storage-class="STANDARD_IA",allow_other 0 0

**Comment by kahing** [comment]
You need to set -o allow_other, that's a fuse thing.

**Comment by greerso** [comment]
Still getting mount: can't find /mnt/cpirepsarchive.s3/ in /etc/fstab or /etc/mtab

I'm guessing that its something with the format of my entry.  I'm just copying from the way that I mount s3fs and riofs.

**Comment by kahing** [comment]
I probably need to explicitly support that. Could you file another issue?

**Comment by kahing** [comment]
The original problem is not an issue.
