### ISSUE TITLE
Multiple S3 mounts - Memory Limits

### ISSUE THREAD

**Issue by eswarantg** [kahing/goofys#312]
In my product i have a use-case to consume a file input on one S3 bucket.  The processed output file is to be written to a second S3 bucket.

This requires that we use 2 goofys mount processes.

#310 - I am working to understand the Memory usage of the processes.

Since each one is set to use 1/2 of the available space, Is there a changes that at times it can exceed the overall available memory?

If so, is there any mechanism available to limit the usage of a instance of goofys process to a lower value.

I have seen earlier suggestions to have a % value of total available, but were not taken.
Wondering if there are already mechanisms existing.

Appreciate inputs.

**Comment by kahing** [comment]
goofys uses up to 1/2 of the available memory for write buffering, where available means it's not used by other processes. So if there are two goofys processes they shouldn't each use 50% but more likely to settle to around 33% each ((100% - 33%) / 2). There's no mechanism to limit goofys' total memory usage.

Feel free to re-open if goofys does end up using more memory than it should
