### ISSUE TITLE
Example for DigitalOcean Spaces

### ISSUE THREAD

**Issue by Jnoack331** [kahing/goofys#315]
## 1. Creating credentials
For DigitalOcean you have to create a "fake" credentials file with path `~/.aws/credentials`

there you insert you spaces credentials like:
```
[default]
aws_access_key_id=<space-access-key-id>
aws_secret_access_key=<space-access-key-secret>
```
or create a additional profile when you are already using aws.

if you dont know where your Space keys are you can create them under
`Spaces > Manage Keys (upper-right corner)`
then create a key but **don't save right away**, there is the secret which you need in the credentials file which is only shown once so copy past it like shown above.

### just once:
```
goofys <space-name> <path-to-mount-in> --file-mode=<your-filemode> --endpoint=<your-space-region --uid=<user-id-from-passwd> --gid=<group-id-from-passwd> -o allow_other
```

### with fstab(mount on boot):
edit the file under `/etc/fstab`:
```
goofys#<space-name> <path-to-mount-in> fuse _netdev,allow_other,--file-mode=<your-filemode>,--endpoint=<your-space-region>,--uid=<user-id-from-passwd>,--gid=<group-id-from-passwd>, 0 0
```
where user and group are the owner of the files.

configuration value examples:
```
--endpoint="https://ams3.digitaloceanspaces.com"
--uid=123
--gid=123
--file-mode=0640
```

**Comment by cekvenich** [comment]
thx!

**Comment by kahing** [comment]
thanks @Jnoack331
