### ISSUE TITLE
goofy aborts abnormally when writing large files

### ISSUE THREAD

**Issue by kishorekumark** [kahing/goofys#318]
Hi,
Some one help me here, I'm trying to write large files ~10TB to a S3 bucket, after ~188GB write goofy process aborting.Is there any limit on write? this is my setup.
1. Mount s3-bucket-1 to directory dir-1 on EC2.(/usr/bin/goofys cloudvideos usstagevideos)
2. Mount s3-bucket-2 to directory dir-2 on EC2.(/usr/bin/goofys crr-largefiles eustagevideos)
3. rsync usstagevideos eustagevideos

please suggest me is any parameter i can set to tune?

{code}
root@ip-172-31-17-140:~# ls -lrt eustagevideos 
ls: cannot access 'eustagevideos': Transport endpoint is not connected
root@ip-172-31-17-140:~# ls -lrt
ls: cannot access 'eustagevideos': Transport endpoint is not connected
total 26908
d????????? ? ?      ?            ?            ? eustagevideos
{code}

**Comment by kahing** [comment]
S3 only supports max of 5TB files, so if you are writing 10TB there's no way that could work. And yes @robparrott is correct that there's also a goofys limitation of 1TB
