### ISSUE TITLE
cannot mount from /etc/fstab

### ISSUE THREAD

**Issue by greerso** [kahing/goofys#32]
I have tried the following but get the message: mount: can't find /mnt/mountpoint/ in /etc/fstab

goofys#bucketname /mnt/mountpoint fuse rw -o allow-other --dir-mode="0777",--file-mode="0777",--uid="33",--gid="33",--storage-class="STANDARD_IA"  0 0

**Comment by kahing** [comment]
Here's my fstab:

```
goofys#bucket   /mnt/mountpoint        fuse    allow_other,--file-mode=0777    0       0
```
