### ISSUE TITLE
failed mount to s3 bucket

### ISSUE THREAD

**Issue by suddincam** [kahing/goofys#322]
Hi, 
 What could be the reason for this message on a linux system.

s3.ERROR code=NoCredentialProviders msg=no valid providers in chain. Deprecated.#012#011For verbose messaging see aws.Config.CredentialsChainVerboseErrors, err=<nil>

 I just installed it on an ubuntu 17 server.

 Any insight will be appreciated.

Thanks

**Comment by kahing** [comment]
How are you authenticating?

**Comment by suddincam** [comment]
With aws key and secret only.

**Comment by kahing** [comment]
Does awscli work? You need to provide more details

**Comment by suddincam** [comment]
This is resolved, my credentials file had some bugs. Discovered when I tried aws cli. 

Thanks for your quick replies.

**Comment by kahing** [comment]
Could you describe what the problem was and what did awscli say?

**Comment by sorcer1122** [comment]
I am having the same issue, can somebody pls share the solution?
