### ISSUE TITLE
folder names with @ character no longer supported (as of v0.19)

### ISSUE THREAD

**Issue by stevebma** [kahing/goofys#326]
Folder names with @ characters used to be supported (totally fine), updating to 0.19 breaks this.

some notes:

The @ character is escaped to %40, as shown by ls on the mountpoint, e.g.:
`ls /mnt/s3bucket/`

shows:

`folder%40name.something`

Escaping the character manually will list any subfolders (prefixes), yet contents of the folders are not listed, so the directory appears to be empty.

e.g. 
`ls /mnt/s3bucket/folder\@name.something`

Please advise, kind regards

**Comment by benooli** [comment]
I also have this issue with my buckets. Reproduced on CentOS 6 and Ubuntu 16.04. Tried both my own compiled binaries and the pre-built binaries.

Seems to be a regression on version 0.19. I went back to 0.18 and the problem went away.

**Comment by kahing** [comment]
This was a regression on the unreleased goofys on master, but thanks for catching it!

**Comment by benooli** [comment]
@kahing  - thanks will try the official release this time :)
