### ISSUE TITLE
DigitalOcean Spaces compatibility

### ISSUE THREAD

**Issue by xxmatxx** [kahing/goofys#327]
I mount DO space with this parametrs
```
goofys --use-content-type -o allow_other  --file-mode=0777 --dir-mode=0777  --endpoint nyc3.digitaloceanspaces.com plex-daffy /mnt/spaces-goofys
```
ls -al list files correctly in root directory, but when i try list files in /mnt/spaces-goofys/Foto it didn't list files, but files count is correct.
```
total 8
drwxrwxrwx 2 root root 4096 May 29 06:53 .
drwxrwxrwx 2 root root 4096 May 29 06:53 ..
```
i dont know if its problem of DO API, goofys, or it is just misconfiguration.

**Comment by dsclearuc** [comment]
A little late but for one who's reading, use --region XXXX (nyc3, etc...) solves the problem

**Comment by hikarine3** [comment]
This solution doesn't work for Singapore DC in 2023 in my case.
I can read content of flie if I specify absolute path but I cannot list nor find file & directories under mounted directory.
