### ISSUE TITLE
File Permissions

### ISSUE THREAD

**Issue by yeniugo** [kahing/goofys#328]
when i start goofys,i see a problem of permission,who load the aws,only the user can saw the mount file of aws,and i want everyone can see it,how can i do with it?

**Comment by xxmatxx** [comment]
you mus use -o allow_other

example: `goofys  -o allow_other   name  dir`

**Comment by yeniugo** [comment]
like the set startup,`goofys#bucket   /mnt/mountpoint        fuse     _netdev,allow_other,--file-mode=0666    0       0`,is this?

**Comment by xxmatxx** [comment]
yes
