### ISSUE TITLE
Stuck IO operations

### ISSUE THREAD

**Issue by lnicola** [kahing/goofys#329]
I'm trying to use `goofys` to mount an OpenStack container. I don't know any details of the setup. Read performance is generally good, but from time to time processes get stuck while reading some files.

This shows up under `strace` as a `read` that never returns. I can reproduce it with sequential workloads like `cat` or `md5sum`, which get stuck in the middle of the file, at the same position. There might be some caching involved (but not `catfs`). I didn't try to `strace` the `goofys` process, but I don't think there are any errors in the logs.

Accessing the same files from another machine works fine. After unmounting and remounting the container, they start working again. I have reason to believe that the server may be unstable, for some definition of it.

I didn't look into the implementation of `goofys`. Maybe this could be fixed by setting a timeout on the HTTP client? I would be fine with `EIO` or something like that in this case.

**Comment by lnicola** [comment]
I can partially reproduce this on my machine:

1. mount a container
2. start reading a file from it
3. while the file is being read, add a firewall rule to drop incoming packets from the endpoint
4. wait
5. nothing happens; I think it might be a good if `goofys` returned an error after a while
6. try to kill the process; it will be stuck in the `D` state and won't die
7. delete the firewall rule
8. the hung process dies
9. the data is now cached by `goofys`, so you'll have to remount the container to try again

So this is not an exact reproducer, because when the network comes back, everything starts working. In the original report, I had to remount (sometimes with `-lf`) to resume operation.

**Comment by lnicola** [comment]
Update:

- `HEAD` doesn't show my files
- `6b55674433a801daef71168405f1625455aa361b` can list the files, but doesn't seem to help with the timeout handling
- I tried to set the `Timeout` field on the `http.Client`; it makes `goofys` detect the timeout earlier, but the application is still stuck
- I noticed that `goofys` sometimes return data to the application, even with the firewall rule which should prevent it; could it be an uninitialized buffer?

```
read(3, "(\20(\20(\20(\20(\20(\20(\20(\20(\20(\20(\20(\20(\20(\20(\20(\20"..., 32768) = 32768
read(3, "(\r(\r(\r(\r(\r(\r(\r(\r(\r(\r(\r(\r(\r(\r(\r(\r"..., 32768) = 32768
read(3, "(\n(\n(\n(\n(\n(\n(\n(\n(\n(\n(\n(\n(\n(\n(\n(\n"..., 32768) = 32768
read(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 32768) = 32768
read(3, "(\22(\22(\22(\22(\22(\22(\22(\22(\22(\22(\22(\22(\22(\22(\22(\22"..., 32768) = 32768
read(3, "(\16(\16(\16(\16(\16(\16(\16(\16(\16(\16(\16(\16(\16(\16(\16(\16"..., 32768) = 32768
read(3, "(\f(\f(\f(\f(\f(\f(\f(\f(\f(\f(\f(\f(\f(\f(\f(\f"..., 32768) = 32768
```

**Comment by kahing** [comment]
Thanks for the contribution @lnicola
