### ISSUE TITLE
fuse allow-other invalid argument

### ISSUE THREAD

**Issue by greerso** [kahing/goofys#33]
Tried mounting with "goofys -o allow-other --dir-mode "0777" --file-mode "0777" --uid "33" --gid "33" --storage-class "STANDARD_IA" bucket name /mnt/mountpoint &"

Got message:

"2015/11/05 17:39:10 mount helper error: fusermount: mount failed: Invalid argument
2015/11/05 17:39:10.689705 main.FATAL Mounting file system: Mount: mount: fusermount: exit status 1"

**Comment by kahing** [comment]
Try -o allow_other

**Comment by greerso** [comment]
That worked from the command line.

**Comment by kahing** [comment]
What do you mean it worked from command line? allow-other doesn't exist as an option.

**Comment by greerso** [comment]
-o allow_other worked from the command line.  Thanks.
