### ISSUE TITLE
File is not updated even though mtime is updated

### ISSUE THREAD

**Issue by keybod** [kahing/goofys#338]
Hello,

I'm suffering an issue that file changes are not reflected from S3. The changes made the file size same.

I created a file, upload it to S3 and mount the S3 location to my laptop.
The file is quite simple.

```
#!/usr/bin/env python
import time

while True:
    print(time.time())
    print(',,.')
    time.sleep(1)
```

After that, I changed `,,.` part to `,,,` but goofys didn't recognize the changes. But `mtime` of the file on S3 and the file on mounted by goofys are the same.

I used goofys 0.19.0 in OSX with options; `goofys -f --debug_fuse --debug_s3 --stat-cache-ttl 1s --type-cache-ttl 1s test-s3-bucket:yjpark/ /tmp/s3-mount-test`

**Comment by keybod** [comment]
It works now. There may be latency issues.

**Comment by keybod** [comment]
Weired. It worked on and off.

**Comment by keybod** [comment]
It was because of buffer cache of OS.
It worked well when I cleared buffer cache.

**Comment by crh3675** [comment]
I would reopen this as an issue.  One should not have to clear the buffer as that causes an essential down-time on the system to rebuild the inode buffers.  Is there another resolution?

**Comment by biligeny** [comment]
Would anyone explain why OS cache clean could save the failure and what was the exact change for that? //Thanks
