### ISSUE TITLE
Can’t complete the operation

### ISSUE THREAD

**Issue by af-stefan** [kahing/goofys#339]
Hello! 

I've been using goofys for about a week now without issue when suddenly Finder started spitting out the following error when I try to drag and drop: 

The Finder can’t complete the operation because some data in “myfile.txt” can’t be read or written. (Error code -36)

and the following when I do a cp command from the terminal:

cp: myfile.txt: could not copy extended attributes to S3FS3/IMG_2217.jpg: Permission denied

I'm not sure what the issue is here....Attached is the entire output of --debug_fuse and --dubeg_s3
[goofysdebugouput.txt](https://github.com/kahing/goofys/files/2185479/goofysdebugouput.txt)

**Comment by kahing** [comment]
I think this is the same as #260
