### ISSUE TITLE
sqlite db with goofys

### ISSUE THREAD

**Issue by DenisBY** [kahing/goofys#340]
Hi,

We are getting an error `sqlite3.OperationalError: disk I/O error` when we create a sqlite db in a directory mounted with goofys to a s3 bucket.

Is it know issue/limitation?

**Comment by cr-solutions** [comment]
Hello Denis,

we have the same issue with sqlite. But createing the file on /tmp, move then to S3-Goofys directory works.
Similar error on Goofys directory come with VIM swap file.

**Comment by DenisBY** [comment]
Thanks! Will try it.

**Comment by kahing** [comment]
running database like workload on goofys directly is not supported
