### ISSUE TITLE
Does goofys support  -no_check_certificate and sigv2?

### ISSUE THREAD

**Issue by tangchaosh** [kahing/goofys#349]
I want to use goofys to connect S3 complaint object storage.  just want to know if it supports not to check certificate (i am using self-signed CA for my object storage) and v2 signature?   just like s3fs to do.

**Comment by kahing** [comment]
goofys does support v2 signing but does not support not verifying signatures. Can you add the CA to the system?

**Comment by mipapo** [comment]
Not recommended, but a possible option is to disable curls ssl checks by creating a file ".curlrc" with "insecure" as content
