### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by johnnyrocku2** [kahing/goofys#35]
I am trying to install goofys 0.0.2 on a SUSE 13.1 system, but getting the following messages/errors (the preview shows some big bold text.  If it posts as that, I apologize in advance, I'm not doing that on purpose): 

goofys-0.0.2> make
wget https://oss.sonatype.org/content/repositories/snapshots/org/gaul/s3proxy/1.5.0-SNAPSHOT/s3proxy-1.5.0-20151012.215145-8-jar-with-dependencies.jar -O s3proxy.jar
--2015-11-07 02:56:19--  https://oss.sonatype.org/content/repositories/snapshots/org/gaul/s3proxy/1.5.0-SNAPSHOT/s3proxy-1.5.0-20151012.215145-8-jar-with-dependencies.jar
Resolving oss.sonatype.org (oss.sonatype.org)... 107.23.94.232, 52.21.253.142, 52.21.106.20
Connecting to oss.sonatype.org (oss.sonatype.org)|107.23.94.232|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7743535 (7.4M) [application/java-archive]
Saving to: ‘s3proxy.jar’

s3proxy.jar                   100%[================================================>]   7.38M  3.49MB/s   in 2.1s

2015-11-07 02:56:21 (3.49 MB/s) - ‘s3proxy.jar’ saved [7743535/7743535]

./test/run-tests.sh
warning: building out-of-date packages:
        github.com/aws/aws-sdk-go/aws
        github.com/aws/aws-sdk-go/aws/request
        github.com/aws/aws-sdk-go/aws/client
        github.com/aws/aws-sdk-go/aws/corehandlers
        github.com/aws/aws-sdk-go/aws/ec2metadata
        github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds
        github.com/aws/aws-sdk-go/aws/defaults
        github.com/aws/aws-sdk-go/aws/session
        github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil
        github.com/aws/aws-sdk-go/private/protocol/query
        github.com/aws/aws-sdk-go/private/protocol/rest
        github.com/aws/aws-sdk-go/private/protocol/restxml
        github.com/aws/aws-sdk-go/private/signer/v4
        github.com/aws/aws-sdk-go/service/s3
        github.com/jacobsa/fuse/internal/buffer
        github.com/jacobsa/fuse
        github.com/jacobsa/fuse/fuseutil
installing these packages with 'go test -i ./...' will speed future tests.

?       _/home/john/goofys/test2/goofys-0.0.2   [no test files]
# github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil
../../../gocode/src/github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil/xml_to_struct.go:79: e.EncodeToken undefined (type *xml.Encoder has no field or method EncodeToken)
../../../gocode/src/github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil/xml_to_struct.go:82: e.EncodeToken undefined (type *xml.Encoder has no field or method EncodeToken)
../../../gocode/src/github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil/xml_to_struct.go:103: e.EncodeToken undefined (type *xml.Encoder has no field or method EncodeToken)
# github.com/aws/aws-sdk-go/aws
../../../gocode/src/github.com/aws/aws-sdk-go/aws/types.go:87: syntax error: unexpected :, expecting ]
# github.com/jacobsa/fuse/internal/buffer
../../../gocode/src/github.com/jacobsa/fuse/internal/buffer/runtime.s:24 6a: No such file or directory: textflag.h
FAIL    _/home/john/goofys/test2/goofys-0.0.2/internal [build failed]
make: *** [run-test] Error 2

**Comment by kahing** [comment]
What go version do you have? 
On Nov 7, 2015 02:27, johnnyrocku2 <notifications@github.com> wrote:I am trying to install goofys 0.0.2 on a SUSE 13.1 system, but getting the following messages/errors (the preview shows some big bold text.  If it posts as that, I apologize in advance, I'm not doing that on purpose): 

goofys-0.0.2> make
wget https://oss.sonatype.org/content/repositories/snapshots/org/gaul/s3proxy/1.5.0-SNAPSHOT/s3proxy-1.5.0-20151012.215145-8-jar-with-dependencies.jar -O s3proxy.jar
--2015-11-07 02:56:19--  https://oss.sonatype.org/content/repositories/snapshots/org/gaul/s3proxy/1.5.0-SNAPSHOT/s3proxy-1.5.0-20151012.215145-8-jar-with-dependencies.jar
Resolving oss.sonatype.org (oss.sonatype.org)... 107.23.94.232, 52.21.253.142, 52.21.106.20
Connecting to oss.sonatype.org (oss.sonatype.org)|107.23.94.232|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7743535 (7.4M) [application/java-archive]
Saving to: ‘s3proxy.jar’

s3proxy.jar                   100%[================================================>]   7.38M  3.49MB/s   in 2.1s

2015-11-07 02:56:21 (3.49 MB/s) - ‘s3proxy.jar’ saved [7743535/7743535]

./test/run-tests.sh
warning: building out-of-date packages:
        github.com/aws/aws-sdk-go/aws
        github.com/aws/aws-sdk-go/aws/request
        github.com/aws/aws-sdk-go/aws/client
        github.com/aws/aws-sdk-go/aws/corehandlers
        github.com/aws/aws-sdk-go/aws/ec2metadata
        github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds
        github.com/aws/aws-sdk-go/aws/defaults
        github.com/aws/aws-sdk-go/aws/session
        github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil
        github.com/aws/aws-sdk-go/private/protocol/query
        github.com/aws/aws-sdk-go/private/protocol/rest
        github.com/aws/aws-sdk-go/private/protocol/restxml
        github.com/aws/aws-sdk-go/private/signer/v4
        github.com/aws/aws-sdk-go/service/s3
        github.com/jacobsa/fuse/internal/buffer
        github.com/jacobsa/fuse
        github.com/jacobsa/fuse/fuseutil
installing these packages with 'go test -i ./...' will speed future tests.

?       _/home/john/goofys/test2/goofys-0.0.2   [no test files]

github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil

../../../gocode/src/github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil/xml_to_struct.go:79: e.EncodeToken undefined (type *xml.Encoder has no field or method EncodeToken)
../../../gocode/src/github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil/xml_to_struct.go:82: e.EncodeToken undefined (type *xml.Encoder has no field or method EncodeToken)
../../../gocode/src/github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil/xml_to_struct.go:103: e.EncodeToken undefined (type *xml.Encoder has no field or method EncodeToken)

github.com/aws/aws-sdk-go/aws

../../../gocode/src/github.com/aws/aws-sdk-go/aws/types.go:87: syntax error: unexpected :, expecting ]

github.com/jacobsa/fuse/internal/buffer

../../../gocode/src/github.com/jacobsa/fuse/internal/buffer/runtime.s:24 6a: No such file or directory: textflag.h
FAIL    _/home/john/goofys/test2/goofys-0.0.2/internal [build failed]
make: *** [run-test] Error 2

**Comment by johnnyrocku2** [comment]
~> go version
go version go1.1.2 linux/amd64

**Comment by kahing** [comment]
You need to upgrade to something more recent. I've only tested with 1.5.1
On Nov 8, 2015 12:25 AM, johnnyrocku2 <notifications@github.com> wrote:~> go version
go version go1.1.2 linux/amd64

**Comment by johnnyrocku2** [comment]
I upgraded to go v1.5.1, and goofys does seem to build ok now.  However, I am still having an issue:
> $GOPATH/bin/goofys -f goofystest2 /mnt/goofys
2015/11/08 04:08:52.418928 main.FATAL Mounting file system: Mount: mount: Starting fusermount: exec: "fusermount": executable file not found in $PATH

(without the '-f' the message isn't printed, but the bucket doesn't get mounted.)
I do have fuse installed and the fusermount command is in my $PATH in /usr/local/bin

**Comment by johnnyrocku2** [comment]
Thanks for the help!  Looking at the source code linked in your last comment, I saw the code is setting PATH to "/bin".  Since fusermount is installed on my system at /usr/local/bin, I added a symlink with 'ln -s /usr/local/bin/fusermount /bin', and that seems to have fixed it.
