### ISSUE TITLE
Has anyone installed successfully under centos7?

### ISSUE THREAD

**Issue by RootPeter** [kahing/goofys#358]
Hi，

A binary package installation, let me find more than one article is still not installed properly. If someone installs successfully under centos, please send an installation process. I don't understand if your S3 is working under the MAC? Why are there no people on the server?

**Comment by siozosdr** [comment]
@RootPeter 
This worked for me in CentOS 7:
```
wget http://bit.ly/goofys-latest
mv goofys-latest /usr/local/bin/goofys && sudo chmod +x /usr/local/bin/goofys
```
To install catfs I had to build it from source with the following:
```
curl -sSf https://static.rust-lang.org/rustup.sh | sh
git clone https://github.com/rust-lang/cargo
cd cargo
cargo build --release
cargo install catfs
```
The syslog you can review should be `/var/log/messages`

**Comment by RootPeter** [comment]
Sincerely thank you for your reply.
