### ISSUE TITLE
I find some error # github.com/kahing/goofys/api

### ISSUE THREAD

**Issue by k30339035** [kahing/goofys#359]
I send a command. 
Error code is generated. 
Please check it. 
I think code type is ambiguous in a api go file.
 
work/src/github.com/kahing/goofys/api/api.go:196: syntax error: unexpected = in type declaration
work/src/github.com/kahing/goofys/api/api.go:197: syntax error: unexpected = in type declaration
work/src/github.com/kahing/goofys/api/api.go:198: syntax error: unexpected = in type declaration
ubuntu@ip-100-64-3-33:~$ ls

**Comment by nikzen** [comment]
Got the same error while installing.

**Comment by kahing** [comment]
I cannot reproduce this, what version of go are you using?

**Comment by kahing** [comment]
cool, thanks for checking @nqbao

**Comment by gaul** [comment]
We will document this dependency in #365.
