### ISSUE TITLE
git clone permission error

### ISSUE THREAD

**Issue by quancore** [kahing/goofys#363]
**Error:**
![image](https://user-images.githubusercontent.com/15036825/46655090-ddbf9800-cbaa-11e8-8bf0-124b2fe84039.png)
**fstab conf:**
![image](https://user-images.githubusercontent.com/15036825/46655126-f92aa300-cbaa-11e8-9f30-450ccc317911.png)
**df:**
![image](https://user-images.githubusercontent.com/15036825/46655169-17909e80-cbab-11e8-8f2d-a7b8a8440fd2.png)

### **EDIT:**
I changed a bit of permissions:
![image](https://user-images.githubusercontent.com/15036825/46738800-615ab100-cc9f-11e8-86d1-ae826efef6fb.png)
but I have still same problem.In addition to that, when I tried to execute a sh script it gives me (I already run _chmod u+x script_name_ without any error):
![image](https://user-images.githubusercontent.com/15036825/46738896-9961f400-cc9f-11e8-9da0-98fc7733decb.png)
file permissions:
![image](https://user-images.githubusercontent.com/15036825/46740130-61a87b80-cca2-11e8-9f3e-2d15683098e7.png)
Here is my all mounted devices:
![image](https://user-images.githubusercontent.com/15036825/46739048-ec3bab80-cc9f-11e8-9f1c-c2e3126ebb5f.png)
I need an instant help. Thank you.

**Comment by quancore** [comment]
Still not solved.

**Comment by gaul** [comment]
goofys does not support appending to files: https://github.com/kahing/goofys#current-status

**Comment by quancore** [comment]
> goofys does not support appending to files: https://github.com/kahing/goofys#current-status

Any recommendations for multıple client mounting with appending etc.?

**Comment by gaul** [comment]
s3fs allows appends but is not good for multiple clients simultaneously interacting with files.  Perhaps NFS or CephFS?
