### ISSUE TITLE
Permission denied After mount

### ISSUE THREAD

**Issue by delia-m** [kahing/goofys#379]
Hi, I am getting Permission denied as soon as mount. 

I have **root**, and another user - let's say **userA**

**on root,** 
1. create /s3 folder with permission 777 and owner to userA(1001)
2. checkout to userA  (login as - sudo su userA)
3. cd /s3 - can access

**checkout to root again** 
1. mount /s3 folder to amazon s3 with command below
```
goofys -o allow_other --cache="--free:1%:/tmp" --uid=1001 --debug_fuse --debug_s3 --file-mode=0777 --dir-mode=0777 s3_bucket /s3
```
2. manually put file under /s3 -> works all well
3. checkout to userA
4. cd /s3 - permission denied
5. cd /  && ls -la 
```
d?????????   ? ?    ?        ?            ? s3
```

**checkout root again**
1. cd / &&  ls -la
```
drwxrwxrwx   2 userA root  4096 Nov 12 01:54 s3
```
2. umount /s3
3. checkout userA again
4. cd / && ls -la
```
drwxrwxrwx   2 userA root  4096 Nov 12 00:16 s3
```

**conclusion**
userA has all permission for s3 folder but lost them as soon as I mount it with s3 - I can see `???` for permissions instead of rwx for s3 folder

Did I miss something..?
All works fine when manually put file under /s3 in root user
but I can access /s3 folder with userA after mount..

**Comment by ikuradon** [comment]
Probably, replace `--cache="--free:1%:/tmp"` with `--cache="-oallow_other:--free:1%:/tmp"` to fix this situation.

**Comment by kahing** [comment]
I believe @ikuradon 's suggestion would work
