### ISSUE TITLE
Options to not use syslog

### ISSUE THREAD

**Issue by toots** [kahing/goofys#380]
Hi,

I'm trying to deploy goofys in a function as a service environment with limited capacities. In particular, I don't seem to have access to the `syslog` which makes it quite difficult to debug issues. 

Is there any other way to grab logs? All I can see is:
```
FATAL Unable to mount file system, see syslog for details
```

Thanks!

**Comment by gaul** [comment]
If you run `goofys -f` (foreground) the logs should go to stdout.

**Comment by toots** [comment]
That worked, thanks! I'm running into more issues though. What's the preferred way to ask troubleshooting questions?
