### ISSUE TITLE
Support other S3 compliant services

### ISSUE THREAD

**Issue by st-sloth** [kahing/goofys#388]
There are services beside Amazon that are "S3-compliant" implementing the same API (like Wasabi).
Can `goofys` add an option for the user to specify the base URL? That is how Wasabi [can be used with s3fs](https://wasabi-support.zendesk.com/hc/en-us/articles/115001744651-How-do-I-use-S3FS-with-Wasabi-), for example.

**Comment by gaul** [comment]
goofys supports this via the `--endpoint` flag.

**Comment by st-sloth** [comment]
@gaul thank you! My bad, I was too quick too judge by README without running `--help`.
