### ISSUE TITLE
Does not unmount on SIGTERM

### ISSUE THREAD

**Issue by lrowe** [kahing/goofys#39]
I'm not entirely sure what the expected behaviour should be here... When the goofys process is killed by SIGTERM no attempt is made to unmount, so a subsequent start will fail:

```
$ goofys -f ...
2015/11/12 01:52:34.132755 main.INFO File system has been successfully mounted.

    # kill -INT <pid> from another terminal.

2015/11/12 01:52:49.936056 main.INFO Received SIGINT, attempting to unmount...
2015/11/12 01:52:49.946200 main.INFO Successfully exiting.

$ goofys -f ...
2015/11/12 01:54:11.416722 main.INFO File system has been successfully mounted.

    # kill -TERM <pid> from another terminal.

$ goofys -f ...
2015/11/12 01:56:20.199572 main.FATAL Mounting file system: Mount: Statting mount point: stat /s3/encode-files: transport endpoint is not connected
```

At this point one must forcefully umount the mountpoint ``sudo umount /mnt``.

(I discovered this writing a systemd configuration for my goofys mount. Setting ``KillSignal=SIGINT`` seems to make systemctl restart work ok.)

**Comment by kahing** [comment]
I'd consider that a bug. Is there a reason why you are doing this via systems vs fstab?

**Comment by lrowe** [comment]
I just couldn't work out how to configure the fstab.

With systemd I can have goofys run as a non-root user, though I guess that's not really critical.
