### ISSUE TITLE
option --no-implicit-dir can not access file in subdirs directly

### ISSUE THREAD

**Issue by zhjunqin** [kahing/goofys#390]
When start goofys with option `--no-implicit-dir `, it can not access file in subdirs directly

for example: 
bucket `s3://test-bucket/dir1/dir2/dir3/test.txt`, 
mount point is `/mnt/s3/`

It is OK to run `ls /mnt/s3/`
But if run `ls /mnt/s3/dir1/dir2/dir3/` or `ls /mnt/s3/dir1/dir2/dir3` directly, it got error `FileNotFoundError: [Errno 2] No such file or directory`

I need to run `ls /mnt/s3/dir1/`, then `ls /mnt/s3/dir1/dir2/`, and then `ls /mnt/s3/dir1/dir2/dir3` to access `test.txt`.

**Comment by kahing** [comment]
do these all exist?

```
s3://test-bucket/dir1/
s3://test-bucket/dir1/dir2/
s3://test-bucket/dir1/dir2/dir3/
s3://test-bucket/dir1/dir2/dir3/test.txt
```

**Comment by t2y** [comment]
I am using s3 compatible object storage with goofys. I had the same issue before.

But, I guess this issue is s3 compatible object storage instead of goofys. You can confirm the response of head-object like this.

```bash
$ aws --endpoint-url http://s3-ap-northeast-1.amazonaws.com --profile aws --region ap-northeast-1 s3api head-object --bucket ${YOUR-BUCKET} --key path/to/dir/
{
    "AcceptRanges": "bytes",
    "LastModified": "Thu, 21 Mar 2019 03:12:09 GMT",
    "ContentLength": 0,
    "ETag": "\"d41d8cd98f00b204e********\"",
    "ContentType": "application/x-directory",
    "Metadata": {}
}
```

When head-object requests path/to/dir/ and get 200 response, goofy's handle the object in the path normally.

**Comment by zhjunqin** [comment]
We are using ceph rgw as backend, maybe it is cause by the problem as you said.

> I am using s3 compatible object storage with goofys. I had the same issue before.
> 
> But, I guess this issue is s3 compatible object storage instead of goofys. You can confirm the response of head-object with awscli like this.
> 
> ```shell
> $ aws --endpoint-url http://s3-ap-northeast-1.amazonaws.com --profile aws --region ap-northeast-1 s3api head-object --bucket ${YOUR-BUCKET} --key path/to/dir/
> {
>     "AcceptRanges": "bytes",
>     "LastModified": "Thu, 21 Mar 2019 03:12:09 GMT",
>     "ContentLength": 0,
>     "ETag": "\"d41d8cd98f00b204e********\"",
>     "ContentType": "application/x-directory",
>     "Metadata": {}
> }
> ```
> 
> When head-object requests path/to/dir/ and get 200 response, goofys handles the object in the path normally.
