### ISSUE TITLE
Visibility into memory usage strategy

### ISSUE THREAD

**Issue by ikonst** [kahing/goofys#393]
I've noticed some debug logs in the memory management code, but they don't get printed even with '--debug_fuse' (which, itself, is very noisy) and it makes it hard to know what's the expected memory footprint of goofys.

This, in turn, makes it hard to pick alarm thresholds.

**Comment by ikonst** [comment]
For example, there's the memory usage observed over a few weeks of using goofys.
![image](https://user-images.githubusercontent.com/1186084/50788016-053b0500-126d-11e9-93d5-1ecd9612cdba.png)

Right now it peaks at 65% and I'm not sure whether it's normal or what to expect.

**Comment by kahing** [comment]
goofys tries to use up to half of the available memory for buffering (which should only be in use during IO). Idle time memory should be minimal other than inode caching (which you've found a bug in).
