### ISSUE TITLE
when mounted by fstab files created are invisible

### ISSUE THREAD

**Issue by greerso** [kahing/goofys#40]
`$touch /mnt/goofysmount/test`
`$rm /mnt/goofysmount/test`
`$touch /mnt/goofysmount/test`
`$ls -la`

nothing created the second time

**Comment by kahing** [comment]
I am not able to reproduce this:

```
$ touch /tmp/mnt/test
$ rm /tmp/mnt/test
$ touch /tmp/mnt/test
$ ls -la /tmp/mnt
...
-rw-r--r--  1 khc  khc          0 Nov 12 14:18 test
```

**Comment by greerso** [comment]
In my case I am logged in with user 'ubuntu', mounted the volume as root but used options to make owner and group www-data and permissions 0777.

The permissions and owner appear correct.

cpirepsarchive  1.0P     0  1.0P   0% /mnt/cpirepsarchive.s3
root@ip-10-0-0-27:/mnt/cpirepsarchive.s3# ll
total 8
drwxrwxrwx 2 www-data www-data 4096 Nov 12 22:20 ./
drwxr-xr-x 4 root     root     4096 Oct 30 21:23 ../
root@ip-10-0-0-27:/mnt/cpirepsarchive.s3# touch test
root@ip-10-0-0-27:/mnt/cpirepsarchive.s3# mkdir test
mkdir: cannot create directory ‘test’: File exists
root@ip-10-0-0-27:/mnt/cpirepsarchive.s3# mkdir testdir
root@ip-10-0-0-27:/mnt/cpirepsarchive.s3# ll
total 12
drwxrwxrwx 2 www-data www-data 4096 Nov 12 22:20 ./
drwxr-xr-x 4 root     root     4096 Oct 30 21:23 ../
drwxrwxrwx 2 www-data www-data 4096 Nov 12 22:20 testdir/
root@ip-10-0-0-27:/mnt/cpirepsarchive.s3# rmdir testdir
root@ip-10-0-0-27:/mnt/cpirepsarchive.s3# ll
total 8
drwxrwxrwx 2 www-data www-data 4096 Nov 12 22:20 ./
drwxr-xr-x 4 root     root     4096 Oct 30 21:23 ../
root@ip-10-0-0-27:/mnt/cpirepsarchive.s3# mkdir testdir
root@ip-10-0-0-27:/mnt/cpirepsarchive.s3# touch test
root@ip-10-0-0-27:/mnt/cpirepsarchive.s3# ll
total 12
drwxrwxrwx 2 www-data www-data 4096 Nov 12 22:20 ./
drwxr-xr-x 4 root     root     4096 Oct 30 21:23 ../
drwxrwxrwx 2 www-data www-data 4096 Nov 12 22:20 testdir/
root@ip-10-0-0-27:/mnt/cpirepsarchive.s3# rmdir testdir
root@ip-10-0-0-27:/mnt/cpirepsarchive.s3# ll
total 8
drwxrwxrwx 2 www-data www-data 4096 Nov 12 22:20 ./
drwxr-xr-x 4 root     root     4096 Oct 30 21:23 ../
root@ip-10-0-0-27:/mnt/cpirepsarchive.s3# touch testdir
root@ip-10-0-0-27:/mnt/cpirepsarchive.s3# ll
total 8
drwxrwxrwx 2 www-data www-data 4096 Nov 12 22:20 ./
drwxr-xr-x 4 root     root     4096 Oct 30 21:23 ../
root@ip-10-0-0-27:/mnt/cpirepsarchive.s3# mkdir testdir
mkdir: cannot create directory ‘testdir’: File exists

**Comment by greerso** [comment]
I should mention that when I check the bucket on aws.amazon.com, it is empty even though command line is reporting 'File exists'.

**Comment by kahing** [comment]
I can sort of reproduce this:

```
$ pwd
/tmp/mnt/test_dir
$ ls -l
total 0
$ ls -l /tmp/mnt/test_dir
total 0
-rw-r--r-- 1 khc khc    0 Nov 12 17:10 test
drwxr-xr-x 2 khc khc 4096 Nov 12 17:09 testdir
```

**Comment by greerso** [comment]
I have found that if I `ls -la` there is nothing but if I `ls -la test` I see the file. I do not have permission to edit the file even though it shows as 0777.

**Comment by kahing** [comment]
Do you have a reliable way to reproduce this?

**Comment by greerso** [comment]
Yes.

Mount volume with uid and gid of www-data user and file and directory permissions 0777 using goofys.
Create a file.
Delete the file.
Try to create a file with the same name, receive no error, but also no file is created.
`ls` shows no file by that name.
`ls filename` shows the file that you thought that you had deleted.
`nano filename` allows you to edit the file, but does not allow save.

If you would like, I can give you access to clean install ubuntu 14.04 test server where the issue exists.

**Comment by greerso** [comment]
This only happens when I mount from fstab using the following:

goofys#cpirepsarchive   /mnt/cpirepsarchive.s3	fuse	allow_other,--file-mode=0777,--dir-mode=0777,--uid=33,--gid=33,--storage-class="REDUCED_REDUNDANCY"    0       0

I think there is something wrong with that entry because the server will not boot unless its commented out.  I will try copying the binary to /usr/bin instead of the symlink to see if it makes a difference.

**Comment by kahing** [comment]
I think that's unrelated to this issue, try adding _netdev to your fstab mount options:

```
goofys#cpirepsarchive /mnt/cpirepsarchive.s3 fuse _netdev,allow_other,--file-mode=0777,--dir-mode=0777,--uid=33,--gid=33,--storage-class="REDUCED_REDUNDANCY" 0 0
```

```

**Comment by greerso** [comment]
My initial description is not quite correct.  I cannot see any files that I create when mounting using fstab when I `ls -la` but can I see them if I use `ls -la filename`.  This is true even the first time that i create a file.

The problem does not exists when i mount from command line.

Adding _netdev did not help with the invisible files.  (unless that was supposed to help with the reboot issue which I haven't tried).

**Comment by kahing** [comment]
_netdev is for the reboot problem. Please file new issues next time to avoid confusion.

Could you see if the new commit helped with the invisible files issue?

**Comment by greerso** [comment]
The latest version did not resolve the issue.

**Comment by kahing** [comment]
try removing the quotes around REDUCED_REDUNDANCY

**Comment by greerso** [comment]
Worked!

**Comment by kahing** [comment]
Reopening. There's still an issue here because we should have returned an error when the files were created
