### ISSUE TITLE
goofys consistently panics with S3 mount when hitting TAB to complete a filename in emacs

### ISSUE THREAD

**Issue by dakoner** [kahing/goofys#405]
Ubuntu 18.04 on AWS using goofys linux binary downloaded from github.

I have a goofys-mounted S3 bucket and in emacs, I'm trying to TAB-complete a filename in a the mounted filesystem:
Find file: /mnt/my-data-bucket/data/Ind<TAB>

as soon as I do this, I get a crash:

$ ~/goofys-latest -f my-data-bucket /mnt/my-data-bucket
2019/03/11 18:26:17.572849 s3.INFO Switching from region 'us-east-1' to 'us-west-2'
2019/03/11 18:26:17.608076 main.INFO File system has been successfully mounted.
panic: invalid offset 12996, base=13000

goroutine 207 [running]:
github.com/kahing/goofys/internal.(*DirHandle).ReadDir(0xc420322f00, 0x32c4, 0xc420322f08, 0xc421e0ae50, 0x1)
        /home/khc/Code/go/src/github.com/kahing/goofys/internal/dir.go:342 +0x166b
github.com/kahing/goofys/internal.(*Goofys).ReadDir(0xc420148a90, 0xc89020, 0xc4217b0060, 0xc4202c0000, 0x0, 0x0)
        /home/khc/Code/go/src/github.com/kahing/goofys/internal/goofys.go:816 +0x260
github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).handleOp(0xc42039a200, 0xc4202023c0, 0xc89020, 0xc4217b0060, 0x8ba640, 0xc4202c0000)
        /home/khc/Code/go/src/github.com/jacobsa/fuse/fuseutil/file_system.go:178 +0xc06
created by github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).ServeOps
        /home/khc/Code/go/src/github.com/jacobsa/fuse/fuseutil/file_system.go:121 +0x176

Hitting TAB to complete the entire dir doesn't cause a crash.
Hitting TAB to complete the filename in bash doesn't cause a crash.
When I enable S3 debugging, the error doesn't occur (the TAB completion succeeds).

**Comment by kahing** [comment]
dup of #335 , use master for now
