### ISSUE TITLE
Caching causes many ways to create invalid views of a bucket

### ISSUE THREAD

**Issue by dakoner** [kahing/goofys#411]
Hi,
I've been using goofys while also modifying a bucket using application code (aws rm, boto3).  What I've seen is that there are many ways to cause the cache to show invalid bucket metadata.

Some of the more troubling examples involve showing the same filename twice after a object prefix was created, deleted, and created again outside of goofys:

$ ls /mnt/my-data-tiles/
bar  foo  foo

Practically speaking, I'd like to know how to work with goofys: can I drop the internal cache or force a cache invalidation without restarting the binary?  Can the internal cache have a timeout for path metadata?

**Comment by dakoner** [comment]
To clarify- i've already looked at the cache options in goofys and I don't think it's working in my case. For example, in the example where I see 'foo' twice. I've run the query repeatedly for an hour and see stable incorrect reuslts.

**Comment by kahing** [comment]
there's a readdir caching related bug that was fixed recently, could you try again with master? also, could you describe in more details about how you hit the specific cases?

**Comment by dakoner** [comment]
Try with actual Master, or the latest binary release (0.20)?

**Comment by dakoner** [comment]
I'm using master (924ca6e871dd14782598c3bbc3c9a8133954f7b3).

Here's an example of a what I call an invalid view:
ubuntu@ip-172-31-0-132:/mnt/redacted/tiles.1024$ ls
11  12  13  14  2  20  21  22  25  26  3  30  4  5  637  641  648  650  661  663  666  668  669  673  685  688  689  690  7  9
ubuntu@ip-172-31-0-132:/mnt/redacted/tiles.1024$ rm -rf 11
# While the above command is running, in another shell I run "cd /mnt/redacted/tiles.1024/11" and then "rm -rf *" in that subfolder

# returning to the original terminal, I wait until the rm -rf 11 is done and run ls:

ubuntu@ip-172-31-0-132:/mnt/redacted/tiles.1024$ ls
ls: cannot access '11': No such file or directory
11  12  13  14  2  20  21  22  25  26  3  30  4  5  637  641  648  650  661  663  666  668  669  673  685  688  689  690  7  9

This is an invalid view because
1) 11 was rm -rf'd
2) ls says 11 is not a file or directory
3) 11 still shows up in the listing, repeatedly (I didn't wait for a cache invalidation timeout, but did re-run the command a few times)

After carefully removing any shells that were cd'd into the bucket, restarting goofys shows the correct view (no 11 dir).

I didn't do any operations using 'aws s3' or the console.  I bet in this specific report it's specific to the concurrent actions where one terminal was in a subfolder and another terminal was trying to delete that subfolder, so some reference count didn't get reduced by 1.  Trying a simpler repro.

**Comment by dakoner** [comment]
OK, confirmed: if you have one window cd'd to a subfolder, and another window that rm -rfs that subfolder, subsequent directory listings will both list a subfolder, and say it doesn't exist.

Further, if I then try to remake the dir that is both missing and listed, it will panic the server 
2019/07/11 23:43:41.660165 main.ERROR stacktrace from panic: double insert of tiles.1024/13
goroutine 844598 [running]:
runtime/debug.Stack(0xc000123bf8, 0xc86f20, 0xc00059c480)
        /home/ubuntu/go/src/runtime/debug/stack.go:24 +0x9d
github.com/kahing/goofys/api/common.LogPanic(0xc000123f50)
        /home/ubuntu/work/src/github.com/kahing/goofys/api/common/panic_logger.go:32 +0x7c
panic(0xc86f20, 0xc00059c480)
        /home/ubuntu/go/src/runtime/panic.go:522 +0x1b5
github.com/kahing/goofys/internal.(*Inode).insertChildUnlocked(0xc00032cfc0, 0xc000af23f0)
        /home/ubuntu/work/src/github.com/kahing/goofys/internal/handles.go:351 +0x4bd
github.com/kahing/goofys/internal.(*Goofys).insertInode(0xc00032ce10, 0xc00032cfc0, 0xc000af23f0)
        /home/ubuntu/work/src/github.com/kahing/goofys/internal/goofys.go:651 +0x6b
github.com/kahing/goofys/internal.(*Goofys).MkDir(0xc00032ce10, 0xf78780, 0xc000290ba0, 0xc0003c20e0, 0x0, 0x0)
        /home/ubuntu/work/src/github.com/kahing/goofys/internal/goofys.go:949 +0x1a1
github.com/kahing/goofys/api/common.FusePanicLogger.MkDir(0xf8b080, 0xc00032ce10, 0xf78780, 0xc000290ba0, 0xc0003c20e0, 0x0, 0x0)
        /home/ubuntu/work/src/github.com/kahing/goofys/api/common/panic_logger.go:61 +0x81
github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).handleOp(0xc000292320, 0xc000346820, 0xf78780, 0xc000290ba0, 0xc5d860, 0xc0003c20e0)
        /home/ubuntu/work/src/github.com/jacobsa/fuse/fuseutil/file_system.go:154 +0xb0b
created by github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).ServeOps
        /home/ubuntu/work/src/github.com/jacobsa/fuse/fuseutil/file_system.go:121 +0x173

I was not able to come up with a much simpler repro with just a few folders/files yet.

**Comment by kahing** [comment]
any chance you could add a test case for this? I've been trying to reproduce this with the following but not able to:

```go
@@ -2971,3 +2971,32 @@ func (s *GoofysTest) testMountsNested(t *C, cloud StorageBackend,

        s.assertEntries(t, in, []string{"in"})
 }
+
+func (s *GoofysTest) TestIssue411DirCaching(t *C) {
+       mountPoint := "/tmp/mnt" + s.fs.bucket
+       s.fs.flags.StatCacheTTL = 1 * time.Minute
+       s.fs.flags.TypeCacheTTL = 1 * time.Minute
+
+       s.mount(t, mountPoint)
+       defer s.umount(t, mountPoint)
+
+       defer os.Chdir("/")
+
+       dir, err := os.Open(mountPoint + "/dir2")
+       t.Assert(err, IsNil)
+       defer dir.Close()
+
+       err = dir.Chdir()
+       t.Assert(err, IsNil)
+
+       dir2, err := s.LookUpInode(t, "dir2")
+       t.Assert(err, IsNil)
+       dir2.dir.seqOpenDirScore = 2
+
+       err = os.RemoveAll(mountPoint + "/dir2")
+       t.Assert(err, IsNil)
+
+       files, err := dir.Readdir(0)
+       t.Assert(err, IsNil)
+       t.Assert(len(files), Equals, 0)
+}
```

**Comment by dakoner** [comment]
I don't have the time to write a good test case, sorry!

**Comment by kahing** [comment]
could you give me the exact directory structure that you reproduced on, and the exact commands? I tried creating a directory structure with:

```shell
for i in $(seq 1 1000); do mkdir $i && for j in $(seq 1 30); do touch $i/$j.png; done; done
```
but not able to reproduce the problem

**Comment by kahing** [comment]
for example you can email me the output of `find`

**Comment by dakoner** [comment]
it looks something like this:
/mnt/redacted/tiles.1080/{1..100}/{0..4}/tiles/{0-9}/{0-20}/{0-100}.png

one terminal is in /mnt/redacted/tiles.1080 calling rm -rf 1
another terminal is in /mnt/redacted/tiles.1080/1
then an ls in /mnt/redacted/tiles.1080 will list 1 as well as saying 1 doesn't exist, until you close the second terminal.

with simpler dirtrees than the full one, I don't see the problem.  If the last {0-100} is too much I think you can lower it. 

I was going to suggest using at least 
cd /mnt/redacted
mkdir tiles.1080
cd tiles.1080
mkdir -p {1..100}/{0..4}/{0..9} 
touch {1..100}/{0..4}/{0..9}/{0..9}.png 

however, I couldn't repro with that, so I have mailed the find output to you.

**Comment by kahing** [comment]
Please re-open if 464737f4d85b06180f54e63b5adc23704c814c91 didn't fix your problem
