### ISSUE TITLE
Suggestion: Use Etag to reuse Inodes upon renaming

### ISSUE THREAD

**Issue by emillynge** [kahing/goofys#419]
Dear Maintainer(s)

I have a use-case where I want to keep track of files in an s3 bucket over time. I have noted an inconcistency when renaming e.g. `mv BUCKET/file BUCKET/renamed_file`

In the locally mounted folder where this command is executed, `renamed_file` reports the same inode as the original `file`. But in a remote mount, the new file is assigned a completely new inodeID.

I understand that this is due to a limitation in the s3 SDK where the only option is a copy followed by a delete.

We could however attempt to infer this rename in goofys by looking into our cache using the following:

- The old Inode object has been forgotten (hopefully) and the inode could be "released"
- The new Inode object would have same size and etag

I think my use case differs from the one raise in https://github.com/kahing/goofys/issues/178 
Since i do not want to have multiple file names with the same Inode at the same time.

The main issue I think is that for a short moment, s3 will report 2 files before deleting the original one, and therefore the InodeId cannot be "released".

Do you think a solution like this one could be implemented?

Alternatively, maybe we can introduce a flag that enables inodeId creation based on hashing a (Etag, size) tuple, rather than incrementing.  This would effectively hardlink any files with same (etag, size) - which for some would be a bad idea, but for others, it may be fine.

**Comment by kahing** [comment]
This seems really strange. If I create a new file with the same content as an existing file, the inode id will suddenly become the same as an existing file?

Also, for big files, you have to do multi-part upload/copy, so the etag is non-deterministic (well, deterministic if you always use the same part sizes) anyway, so that seems flaky.

what's the motivation for having consistent inode id?

**Comment by kahing** [comment]
also by default `du` will under-report space usage if two files have the same inode (unless you pass `-l`)

**Comment by dougstarfish** [comment]
What would you do for pseudo directories? Directories are inferred and thus cannot have an etag, so you'd have to have some other inode generation scheme for them. If you wanted them to be persistent (vs in-order-of-access), you'd also have to cache them locally, probably in a DB.

**Comment by kahing** [comment]
I've thought more about this and this doesn't really work. If we re-use inode for objects with the same etag, the kernel will think they are the same files when they are not. This maybe fine for reading data but other things like xattr will break.
