### ISSUE TITLE
main.FATAL Mounting file system: Mount: mount: running fusermount: exit status 1#012#012stderr:#012fusermount: fuse device not found, try 'modprobe fuse' first#012

### ISSUE THREAD

**Issue by patdapogi** [kahing/goofys#421]
s3 bucket not mounting on my instance but when i use "aws s3 ls" all s3 buckets are showing

error message:"main.FATAL Mounting file system: Mount: mount: running fusermount: exit status 1#012#012stderr:#012fusermount: fuse device not found, try 'modprobe fuse' first#012"

**Comment by deborja-angelica** [comment]
I have a similar issue.
The following command is executed:
```
sudo /root/gopath/bin/goofys [s3 bucket] [dir] -o allow_other,--file-mode=0777,--uid=500,--gid=500,--profile=s3
```
Checking the logs yield the ff.:
```
/root/gopath/bin/goofys[20220]: main.FATAL Mounting file system: Mount: mount: running fusermount: exit status 1#012#012stderr:#012fusermount: fuse device not found, try 'modprobe fuse' first#012
```

**Comment by kahing** [comment]
You are missing the fuse kernel module which is required by all fuse programs. Are you running in docker? If yes, you probably need to pass through `/dev/fuse` into your container.
