### ISSUE TITLE
Invalid ELF?

### ISSUE THREAD

**Issue by chrissound** [kahing/goofys#422]
https://github.com/cloudposse/goofys won't run - it seems to run into an error of https://unix.stackexchange.com/questions/378301/linux-executable-fails-with-file-not-found-even-though-the-file-is-there-and-i

I've also tried locally: 
```
wget https://github.com/kahing/goofys/releases/download/v0.19.0/goofys -O Downloads/goofys
 chmod +x Downloads/goofys
./Downloads/goofys --version
zsh: no such file or directory: ./Downloads/goofys
```

We seem to have a missing library (on my local):
```
>file goofys 
goofys: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=4b4e04a46d1d3e2b89b36f5548bf22701d897132, with debug_info, not stripped

> ldd /lib64/ld-linux-x86-64.so.2
ldd: /lib64/ld-linux-x86-64.so.2: No such file or directory
```

**Comment by chrissound** [comment]
No luck with using the `golang:1.11.10-alpine3.9` image either 

```
/usr/local/bin/goofys: line 1: ELF: not found
/usr/local/bin/goofys: line 2: syntax error: unexpected "("
/usr/bin/run.sh: line 6: /usr/local/bin/goofys: not found
```

**Comment by chrissound** [comment]
This works on the docker `ubuntu:14.04` image. With dependencies of `RUN apt update
RUN apt install -y gcc ca-certificates openssl musl-dev git fuse syslog-ng syslog-ng-core coreutils curl
`

**Comment by kahing** [comment]
should you file a problem with https://github.com/cloudposse/goofys? The binary was built on Ubuntu and I can't guarantee that it will work on all systems. You could always try to build from source instead
