### ISSUE TITLE
mount failed: Operation not permitted

### ISSUE THREAD

**Issue by gilgameshskytrooper** [kahing/goofys#425]
I set up an EC2 instance as similar as possible to one where I got `goofys` working properly (Ubuntu 18.04 with Linuxbrew, installing `libfuse` and `goofys` from Linuxbrew, running `aws configure`, as well as exporting `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` inside `~/.profile` and `/etc/environment` such that the output of `~/.aws/credentials` matches those environment variables.

However, when running the command `goofys [bucket] [mount point]`, I get the error `2019/06/07 18:08:09.789068 main.FATAL Unable to mount file system, see syslog for details`

Here is the logs when I run `goofys --debug_s3 [bucket] [mount point]

```
Jun  7 18:09:00 ip-172-30-4-96 /home/linuxbrew/.linuxbrew/Cellar/goofys/0.19.0/bin/goofys[6447]: s3.DEBUG HEAD https://s3.amazonaws.com/[BUCKET NAME] = 403 [us-east-1]
Jun  7 18:09:00 ip-172-30-4-96 /home/linuxbrew/.linuxbrew/Cellar/goofys/0.19.0/bin/goofys[6447]: s3.DEBUG DEBUG: Request s3/HeadObject Details:#012---[ REQUEST POST-SIGN ]-----------------------------#012HEAD /[BUCKET NAME]/pi85l8j9ybvmwi8bk3854sadocevuxw5 HTTP/1.1#015#012Host: s3.amazonaws.com#015#012User-Agent: aws-sdk-go/1.8.25 (go1.9.2; linux; amd64)#015#012Authorization: AWS4-HMAC-SHA256 Credential=[CREDENTIAL]/20190607/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=33b39b855f6241919d152aef310efd51e8f88c1c2165f45497c5e28088d08328#015#012X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855#015#012X-Amz-Date: 20190607T180900Z#015#012#015#012#012-----------------------------------------------------
Jun  7 18:09:01 ip-172-30-4-96 /home/linuxbrew/.linuxbrew/Cellar/goofys/0.19.0/bin/goofys[6447]: s3.DEBUG DEBUG: Response s3/HeadObject Details:#012---[ RESPONSE ]--------------------------------------#012HTTP/1.1 404 Not Found#015#012Transfer-Encoding: chunked#015#012Content-Type: application/xml#015#012Date: Fri, 07 Jun 2019 18:09:00 GMT#015#012Server: AmazonS3#015#012X-Amz-Id-2: +OsyIatnuMCizQinEGcOVgtlHK0U3fHYWBI3PTPDKheTvHkwFj6OMipuCdURPWPNVwhlYjZ0oAI=#015#012X-Amz-Request-Id: 1EEAB5C275EAD46E#015#012#015#012#015#012#012-----------------------------------------------------
Jun  7 18:09:01 ip-172-30-4-96 /home/linuxbrew/.linuxbrew/Cellar/goofys/0.19.0/bin/goofys[6447]: s3.DEBUG DEBUG: Validate Response s3/HeadObject failed, not retrying, error NotFound: Not Found#012#011status code: 404, request id: 1EEAB5C275EAD46E, host id: +OsyIatnuMCizQinEGcOVgtlHK0U3fHYWBI3PTPDKheTvHkwFj6OMipuCdURPWPNVwhlYjZ0oAI=
Jun  7 18:09:01 ip-172-30-4-96 /home/linuxbrew/.linuxbrew/Cellar/goofys/0.19.0/bin/goofys[6447]: s3.DEBUG DEBUG: Request s3/ListMultipartUploads Details:#012---[ REQUEST POST-SIGN ]-----------------------------#012GET /[BUCKET NAME]?uploads= HTTP/1.1#015#012Host: s3.amazonaws.com#015#012User-Agent: aws-sdk-go/1.8.25 (go1.9.2; linux; amd64)#015#012Accept-Encoding: identity#015#012Authorization: AWS4-HMAC-SHA256 Credential=[CREDENTIAL]/20190607/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=1c61023cb53b459cdeef12fcc646e88300b88e5a30986036819d587f4d0588d7#015#012X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855#015#012X-Amz-Date: 20190607T180901Z#015#012#015#012#012-----------------------------------------------------
Jun  7 18:09:01 ip-172-30-4-96 /home/linuxbrew/.linuxbrew/Cellar/goofys/0.19.0/bin/goofys[6447]: main.FATAL Mounting file system: Mount: mount: running fusermount: exit status 1#012#012stderr:#012fusermount: mount failed: Operation not permitted
Jun  7 18:17:01 ip-172-30-4-96 CRON[6481]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
```

Any idea why this could be happening?

**Comment by gilgameshskytrooper** [comment]
Weird because it totally works when I put it inside a SystemD script

**Comment by kahing** [comment]
which user are you running goofys as? could it be that your user doesn't have permission to mount?

Also, any reason why you are using linuxbrew?

**Comment by gilgameshskytrooper** [comment]
Potentially, but this doesn't explain why the systemd script works:

```
Description=(Some Description)
After=network-online.target
Requires=network-online.target

[Service]
User=ubuntu
Group=ubuntu
Environment=AWS_ACCESS_KEY_ID=[KEY_ID]
Environment=AWS_SECRET_ACCESS_KEY=[KEY]
WorkingDirectory=/home/ubuntu/[path_to_application]
ExecStartPre=/home/linuxbrew/.linuxbrew/bin/go build
ExecStartPre=/home/linuxbrew/.linuxbrew/bin/goofys [bin-name] /home/ubuntu/[mount_point]
ExecStart=/home/ubuntu/[location_of_go_binary]
ExecStop=/bin/kill -USR1 $MAINPID
ExecStopPost=/usr/bin/sudo /bin/umount /home/ubuntu/[mount_point]

[Install]
WantedBy=multi-user.target
```
As you can see, I am doing everything with the `user:group` combo `ubuntu:ubuntu` (other than sudo umount).

You guys don't specify a PPA in your README.md, and I guess having to satisfy the `libfuse` dependency manually was kind of an annoyance.

**Comment by kahing** [comment]
That's quite strange. How does linuxbrew install `fuse`? (goofys depends on the `fuse` package, and not `libfuse`, I don't remember why I said `fuse-utils` in README anymore, maybe it was renamed?)

**Comment by gilgameshskytrooper** [comment]
According to [this](https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/goofys.rb) (line 23), it states `libfuse` is a dependency. Do you think this is an error with the formula then?

**Comment by gilgameshskytrooper** [comment]
I did not know `libfuse` ≠ `fuse`

**Comment by kahing** [comment]
`libfuse` is the C binding to fuse, `fuse` contains a couple utils and the manpages. goofys depends on `fusermount` which is in `fuse`. At least, that's the case for ubuntu.

looks like `libfuse` in homebrew is actually installing `fuse` from source: https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/libfuse.rb , so maybe that brings in `fusermount`. `fusermount` needs to be a `setuid` binary and it's hard for me to tell if that's done or not. Maybe when you are running in systemd you are using the system `fusermount`, and when you are running in terminal you are using the broken `fusermount` from homebrew?

**Comment by gilgameshskytrooper** [comment]
O. I just built from source and it worked fine. The linux distro I am using has `fusermount` built in, so I just installed Goofys from source and now it just works every time. I guess the problems are with the Linuxbrew package.

**Comment by kahing** [comment]
@gilgameshskytrooper could you file a bug with linuxbrew/homebrew?

**Comment by gilgameshskytrooper** [comment]
Will do. Thanks for your help.
