### ISSUE TITLE
Can't even ls without sudo

### ISSUE THREAD

**Issue by c0d3m0nky** [kahing/goofys#429]
How I'm mounting:
`sudo goofys -o allow_other --profile s3Mounter --file-mode=0666 --dir-mode=0666 bucket /mnt/bucket/`

When I `ls /mnt/bucket` I get the details but also get `ls: cannot access '/mnt/bucket/bucketFolder': Permission denied` for every directory unless I sudo. 

If I `ls -l /mnt/bucket` I get `d????????? ? ? ? ?            ? bucketFolder` but sudoing that gives me 
`drw-rw-rw- 2 root root 4096 Jun 21 21:24 bucketFolder` 

Why can only root access this if it's rw for all?

**Comment by kahing** [comment]
goofys is doing exactly what you asked it to do. Here's the equivalent on a regular ext4 filesystem:

```
$ chmod 0666 b
$ ls b
ls: cannot access 'b/1': Permission denied
1
```

You want to give execute permission to `--dir-mode`
