### ISSUE TITLE
Permission denied for non-root user

### ISSUE THREAD

**Issue by pditommaso** [kahing/goofys#430]
I'm struggling to configure goofys to allow a non-root user, e.g. `foo`, to read-write to a mounted s3 bucket. 

I'm using the following line in the `/etc/fstab/file`

```
goofys#bucket       /mnt/s3       fuse     _netdev,allow_other,--file-mode=0755,--uid=112,--gid=116       0 0
```

Where `112` and `116` are respectively the user and group ID for `foo`.  The bucket is mounted correctly, the content can be listed but when I try to create/delete a file as `foo` I get a `Permission denied` error. 

Any clue what's wrong?

**Update:**

When the bucket is mounted using the following command, it works fine: 

```
sudo goofys -o allow_other --file-mode=0755 --uid 112 --gid 116  bucket /mnt/s3
```

However still not working when mounting it via fstab.

**Comment by kahing** [comment]
Are you using `--dir-mode`? Also it's not clear if you are using the same `--file-mode` in `sudo` vs `fstab`

**Comment by pditommaso** [comment]
> Are you using --dir-mode?

Nope. Should I use it? 

> Also it's not clear if you are using the same --file-mode in sudo vs fstab

Yes, there are the same, just as reported in the comment above.

**Comment by kahing** [comment]
you should make the directories executable (ie: `--dir-mode=755`)

**Comment by pditommaso** [comment]
Unfortunately does not help 

```
goofys#bucket       /mnt/s3 fuse     _netdev,allow_other,--file-mode=0666,--dir-mode=755,--uid=112,--gid=116      0 0
```

**Comment by pditommaso** [comment]
Ok, it turns that `,--dir-mode=0755` was necessary but I has also an IAM access policy problem. Thanks for your help.
