### ISSUE TITLE
regression for list dir, only get the first 1000 objects in a directory

### ISSUE THREAD

**Issue by iamdusky** [kahing/goofys#431]
I have a bucket with more than 1000 objects in it. When doing an ls, I only get 1000 objects returned. 

I haven't been able to find the correct option to up the 1000 limit.

Any help is appreciated.
Eric

**Comment by kahing** [comment]
goofys doesn't have that option because it's a server side limit imposed by AWS. Are you using a non-AWS S3 that has a higher limit?

**Comment by gaul** [comment]
Even without such an option, ls with goofys should be able to list more than 1,000 objects.  Does your test show otherwise?

**Comment by iamdusky** [comment]
I'm using AWS s3 and consistently get only 1000 objects returned on a bucket with 50,109 objects.

If this is an aws s3 limitation, then I'll have to figure out a different solution for this. 

Goofys has been great for my other use cases though.

**Comment by kahing** [comment]
what version are you using?

**Comment by iamdusky** [comment]
# goofys -v
goofys version 0.20.0-use `make build' to fill version hash correctly

**Comment by kahing** [comment]
seems like a regression, will look into this

**Comment by kahing** [comment]
could you test again with master?

**Comment by iamdusky** [comment]
Looks good. ls is listing all 50,191 objects.
Thanks!
