### ISSUE TITLE
cp 2GB file to a sub-directory of s3 goofys mountpoint makes it stale

### ISSUE THREAD

**Issue by y0n3t4n1** [kahing/goofys#432]
I'm on macOS High Sierra and goofys version 0.20.0.  cp'ing a file whose size is 2GB or larger to a sub-directory of s3 bucket makes goofys mountpoint unusable until I manually unmount and mount it again.  Here's how to reproduce the problem (I'm deliverately using a sparse file below to reduce the wasted space on local disk, but non-sparse file also trigger the symptom):

```
$ mkdir -p ~/tmp
$ goofys any-s3-bucket ~/tmp
$ mkdir -p ~/tmp/subdir
$ cd ~/Downloads
$ dd if=/dev/null of=BIG oseek=2g bs=1 count=0
$ cp BIG ~/tmp/subdir/
cp: /Users/y0n3t4n1/tmp/subdir/BIG: Socket is not connected
```
The file content itself is always properly copied to S3; the mountpoint becomes unusable afterwards.
Setting `--http-timeout`, as suggested in a similar issue #370, doesn't seem to help.

The actual smallest file size that can trigger the problem seems to be less than 2GiB, but 2001MiB in the above example.

**Comment by kahing** [comment]
goofys currently does not support sparse files. Could you try again without using sparse file and enable `--debug_fuse --debug_s3` and attach the log?

**Comment by y0n3t4n1** [comment]
Sorry, I've been trying to reproduce the issue with or without using sparse files, but without success.

Maybe there was something else which triggered the above problem (like some weird path names).  Once I sort that out and if it hasn't been reported yet, I'll open a new issue for that.

Thank you for your time.

**Comment by NorseGaud** [comment]
Opened https://github.com/kahing/goofys/issues/557 as I can consistently replicate this
