### ISSUE TITLE
Unable to mount file system on AmazonLinux but works on Ubuntu

### ISSUE THREAD

**Issue by cc4i** [kahing/goofys#433]
I can compile and run goofys, but always get following error:
"2019/06/27 16:10:16.818151 main.FATAL Unable to mount file system, see syslog for details"

I tried to use pre-compiled binary with same error, however it works fine on Ubuntu.

**Comment by kahing** [comment]
what does syslog say?

**Comment by dtodd-wipeos** [comment]
I had some issues with mounting gooyfs on AmazonLinux, but was able to figure out a configuration that worked. Maybe this will help.

* Create your mount, such as /mnt/gooyfs
* Create `/root/.aws/credentials` with your standard AWS credentials (you can use the aws-cli as it comes with the distro if you don't feel comfortable creating the file yourself)
* Set those permissions to 600 for the credentials file and 700 for the .aws directory
* Store gooyfs somewhere reasonable (such as /usr/sbin/gooyfs) and make sure it's executable `chmod a+x gooyfs`
* Create a symlink `ln -s /usr/sbin/gooyfs /bin/mount.gooyfs` -- I found that setting a path to the binary itself doesn't work (`/bin/sh: /usr/sbin/gooyfs: No such file or directory` is the error `mount -a` gives), but a link does for some reason
* In the /etc/fstab, add a line similar to this `/bin/mount.gooyfs#s3-bucket-name /mnt/gooyfs fuse _netdev,allow_other,--file-mode=0644,--dir-mode=0777,--http-timeout=5m 0 0`
* Verify mount with `mount -a`

**Comment by huangpd** [comment]
# If it's not empty, unmount first:
fusermount -u /obs
# Or:
umount /obs
