### ISSUE TITLE
goofys crash in master: fatal error: concurrent map writes

### ISSUE THREAD

**Issue by dakoner** [kahing/goofys#438]
I am trying to repro #411 at head.  Host is an Ubuntu 18.04 w/ $ go version
go version go1.12.7 linux/amd64 and goofys  at 4b36e222715286ca636c34eeb28ea98e2444e6a4

I happened to try to speed up a cp of data from a goofys-mounted bucket to a goofys mounted bucket:

xargs -P 4 -n 1 -I'{}' -a ~/tiles5 rsync -av tiles5/{} tiles.1024/{}

This copies 4 subfolders in a bucket simultaneously; when I use this, I get an almost-immediate crash in goofys:

fatal error: concurrent map read and map write

Crash does NOT occur w/ release 0.20.

I can provide the full traceback if required.  Here's the top thread:

goroutine 393 [running]:
runtime.throw(0xe01fcc, 0x15)
        /home/ubuntu/go/src/runtime/panic.go:617 +0x72 fp=0xc00043fa98 sp=0xc00043fa68 pc=0x42dfc2
runtime.mapassign_fast64(0xcc0d60, 0xc0002a6360, 0x88a, 0xffffffffffffffff)
        /home/ubuntu/go/src/runtime/map_fast64.go:101 +0x35f fp=0xc00043fad8 sp=0xc00043fa98 pc=0x412cef
github.com/kahing/goofys/internal.(*Goofys).insertInode(0xc0003ace10, 0xc001176fc0, 0xc001177830)
        /home/ubuntu/go/src/github.com/kahing/goofys/internal/goofys.go:653 +0xac fp=0xc00043fb50 sp=0xc00043fad8 pc=0xbc003c
github.com/kahing/goofys/internal.(*Inode).insertSubTree(0xc001176fc0, 0xc000d9ed2c, 0x5, 0xc00043fe28, 0xc00043fe78)
        /home/ubuntu/go/src/github.com/kahing/goofys/internal/handles.go:926 +0x17f fp=0xc00043fbe0 sp=0xc00043fb50 pc=0xbc937f
github.com/kahing/goofys/internal.(*Inode).insertSubTree(0xc000341950, 0xc000d9ed2a, 0x7, 0xc00043fe28, 0xc00043fe78)
        /home/ubuntu/go/src/github.com/kahing/goofys/internal/handles.go:964 +0x4e1 fp=0xc00043fc70 sp=0xc00043fbe0 pc=0xbc96e1
github.com/kahing/goofys/internal.(*Inode).insertSubTree(0xc0003ad560, 0xc000d9ed28, 0x9, 0xc00043fe28, 0xc00043fe78)
        /home/ubuntu/go/src/github.com/kahing/goofys/internal/handles.go:964 +0x4e1 fp=0xc00043fd00 sp=0xc00043fc70 pc=0xbc96e1
github.com/kahing/goofys/internal.(*DirHandle).listObjectsSlurp(0xc00026ce60, 0xc000998960, 0x2a, 0x0, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/kahing/goofys/internal/dir.go:176 +0x691 fp=0xc00043ff70 sp=0xc00043fd00 pc=0xbb3151
github.com/kahing/goofys/internal.(*DirHandle).listObjects.func1(0xc00026ce60, 0xc00028f560, 0xc000285080, 0xc0002850e0)
        /home/ubuntu/go/src/github.com/kahing/goofys/internal/dir.go:237 +0x4d fp=0xc00043ffc0 sp=0xc00043ff70 pc=0xbcea7d
runtime.goexit()
        /home/ubuntu/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc00043ffc8 sp=0xc00043ffc0 pc=0x45acd1
created by github.com/kahing/goofys/internal.(*DirHandle).listObjects
        /home/ubuntu/go/src/github.com/kahing/goofys/internal/dir.go:236 +0x621

**Comment by kahing** [comment]
could you give me an idea how the sub folders look like so I can try to reproduce this?

**Comment by dakoner** [comment]
Top level is just subfolders:

/mnt/redacted/tiles5$ ls
1    109  116  123  130  139  149  157  167  20   223  231  239  249  257  3    376  392  405  452  541  602  610  618  633  641  649  657  665  673  685  693  70   707  714  722  73   737  744  751  759  766  773  781  789  796  802  81   817  824  831  839  846  853  94
10   11   117  124  131  14   150  158  168  21   224  232  240  25   258  30   377  393  407  494  559  603  611  619  634  642  650  658  666  674  686  694  700  708  715  723  730  738  745  752  76   767  774  782  79   797  803  810  818  825  832  84   847  854  96
101  110  118  125  132  140  151  159  169  218  225  233  241  251  26   31   378  394  409  499  597  604  612  620  635  643  651  659  667  675  687  695  701  709  716  724  731  739  746  753  760  768  775  783  790  798  804  811  819  826  833  840  848  86   98
103  111  119  126  134  141  152  160  170  219  226  234  242  252  260  32   381  398  410  5    598  605  613  628  636  644  652  660  668  676  688  696  702  71   717  725  732  74   747  754  761  769  776  784  791  799  805  812  82   827  834  841  849  87
104  112  12   127  135  145  153  161  171  22   227  235  243  253  261  33   382  4    411  500  599  606  614  629  637  645  653  661  669  679  689  697  703  710  718  726  733  740  748  755  762  77   777  785  792  8    806  813  820  828  835  842  85   9
105  113  120  128  136  146  154  164  172  220  228  236  244  254  262  34   383  401  414  505  6    607  615  630  638  646  654  662  67   680  690  698  704  711  719  727  734  741  749  756  763  770  778  786  793  80   807  814  821  829  836  843  850  90
106  114  121  129  137  147  155  165  173  221  229  237  245  255  28   369  388  402  417  506  600  608  616  631  639  647  655  663  670  681  691  699  705  712  720  728  735  742  75   757  764  771  779  787  794  800  808  815  822  83   837  844  851  91
108  115  122  13   138  148  156  166  2    222  230  238  247  256  29   375  39   403  447  507  601  609  617  632  640  648  656  664  672  684  692  7    706  713  721  729  736  743  750  758  765  772  780  788  795  801  809  816  823  830  838  845  852  92

Each subfolder then has a bunch of subfolders:
$ ls -l 1
total 17
drwxr-xr-x 2 ubuntu ubuntu 4096 Jul  3 13:45 'HOECHST 33342'
drwxr-xr-x 2 ubuntu ubuntu 4096 Jul  3 13:45 'HOECHST 33342 - extended'
drwxr-xr-x 2 ubuntu ubuntu 4096 Jul  3 13:45 'Styo 14'
drwxr-xr-x 2 ubuntu ubuntu 4096 Jul  3 13:45  composite
-rw-r--r-- 1 ubuntu ubuntu  450 May 30 21:39  tiles_info.tsv

Each subfolder of those wil have a tree of PNGs:
....
'1/HOECHST 33342/tiles/7/67':
0.png  10.png  12.png  14.png  16.png  18.png  2.png   21.png  23.png  25.png  27.png  29.png  30.png  32.png  34.png  36.png  38.png  4.png   41.png  6.png  8.png
1.png  11.png  13.png  15.png  17.png  19.png  20.png  22.png  24.png  26.png  28.png  3.png   31.png  33.png  35.png  37.png  39.png  40.png  5.png   7.png  9.png
...
'1/HOECHST 33342/tiles/7/68':
0.png  10.png  12.png  14.png  16.png  18.png  2.png   21.png  23.png  25.png  27.png  29.png  30.png  32.png  34.png  36.png  38.png  4.png   41.png  6.png  8.png
1.png  11.png  13.png  15.png  17.png  19.png  20.png  22.png  24.png  26.png  28.png  3.png   31.png  33.png  35.png  37.png  39.png  40.png  5.png   7.png  9.png
....

I would guess this would repro with a much simpler case with 100 top-level folders, each with 1-2 subfolders containing ~100 files each, and then doing concurrent rm -rfs on each of the top-level folders using xargs -P

**Comment by kahing** [comment]
could you see if that commit fixes your problem?

**Comment by dakoner** [comment]
It does seem to work.  
cd /mnt/redacted/
ls > ~/folders
I ran xargs -P 50 -a folders -I{} rm -rf /mnt/redacted/{}
and it did not crash right away (which is what happened previously).

BTW, the goal of using xargs -P 50 is to speed up rm -rf of a large tree.  I don't know if applying a global lock could be interfering with the deletion performance; for example, if it's not actually faster to delete many folders in parallel, then we wouldn't use xargs -P 50, we'd just rm -rf the top-level folder.

**Comment by kahing** [comment]
Your workload is hitting an optimization in goofys which allows us to coalesce list objects apis. Briefly, when you list a directory, in s3 you issue an api call:
```
list prefix=dir/ delimiter=/
```
that returns all the immediate children of the directory, so that when you do `ls dir` it won't table forever even if there are millions of objects in nested directories. The downside is that when you recursively walk down the tree we will be issuing lots of api calls.

What goofys does is if it notices a recursive directory walk, it assumes eventually we will read all the objects anyway, so when we list a directory there's no reason to just get the immediate children. That reduces the number of api calls we need to do by a large amount (so it's faster and saves you money!). But for a `ls dir`, we have to only return the immediate children for `readdir`, which means that we need to cache the rest of the results until we actually return them later in the recursive walk.

When we add these items to the cache, we need to take a global lock. Since we only get 1000 items at a time from S3, this shouldn't take that long. The only downside to doing xargs -P is that it will interfere with goofys' recursive walk detection at the top level. But if you have multiple nested levels anyway it doesn't matter much. Also the fact that you are doing delete objects in parallel should more than make up for it.

**Comment by gaul** [comment]
Feature request for parallel delete #12.
