### ISSUE TITLE
Uphold custom providers of credentials

### ISSUE THREAD

**Issue by zhiburt** [kahing/goofys#441]
### Could goofys uphold the idea of refreshing credentials in runtime?

Kind of enforce new ones to AWS without unmounting bucket.

I haven't found any information about. I've already got through and create a small fix just refresh a config of S3 in another goroutine (only credentials). I assume it isn't the best solution. That isn't thread safe at least currently. Basically it's working :1234:

By the way, I'd like to say that is a nice library.

If this feature is not provided by goofys at present, I'd like to  carrying on maintain it.

**Comment by zhiburt** [comment]
Meanwhile better solution has come up.
Just create a new provider of credentials and it corries out properly.

### I cannot enforce any options which should be included in _goofys_. Anyway I hope provide custom providers would be valuable.

I suppose this feature can be added as __a side component__. Using code generation or something like it to be effortless to add new providers.

#### Let's move to the business.

> My proposal is support a custom provider as well.

```
goofys -vault ...
```

```
goofys -redis ...
```

## Under hood

At the core what this intention is we have `map[string] ConfigureProvider`, some like

```
providers := map[string] ConfigureProvider {
       "vault", DefaultVaultProvider,
       "redis", DefaultRedisProvider,
}
```

where `ConfigureProvider` is

```
type ConfigureProvider interface {
    Configure(FlagStorage) credentials.Provider
}
```

Using code generation we create default flags for all of these ones.

Exactly there's a need to create a pair of new flags for it. As I see there's a pair of ways to passage though that. That is such as using StringSliceFlag of urfave/cli or just generate new flags which would be hoocked with a provider on generation stage.

If some user would like to create some new provider this Sir/Madam just needs to add it to this map and recompile _goofys_.

> I believe there's no overhead for this feature. Chose of provider do only one time at the start of it.

**Comment by kahing** [comment]
you could probably use the `api` package to install these custom credentials providers right? Let me know if that's not good enough for you
