### ISSUE TITLE
Extremely slow directory listing w/ Apache

### ISSUE THREAD

**Issue by kevinlong206** [kahing/goofys#453]
Greetings,

I'm wondering if there is a way to perhaps get a detailed log of which files are trying to be listed/accessed,  and what S3 calls are subsequently being called?

Utlimately what I am trying to troubleshoot is this:  Doing an 'ls' or 'ls -l' in the root of the mounted s3 bucket, the listing comes back in a reasonable amount of time ( > 1 second ),  however,  when I try to get the listing by visiting the local apache instance which I set up to serve files from this bucket mount, it is extremely slow,  more than 1 minute to get the listning.

I suspect apache may be trying to do something recursively, I'm not sure. I have AllowOveride None set in apache for this directory, so in theory it should not be looking for .htpasswd files etc.

I realize this is quite likely more of an apache issue, but I thought it might be easier to tackle from the goofys end to see what is going on. Any hints appreciated.

```
# time ls /mnt/XXXX-rpm

...

real	0m0.566s
user	0m0.002s
sys	0m0.008s

-----
# time curl http://localhost:8080/XXXX-rpm/
...
real	1m7.114s
user	0m0.001s
sys	0m0.006s

```

in /etc/fstab:

`goofys#iXXXX-rpm /mnt/XXXX-rpm fuse _netdev,allow_other,--file-mode=0444,--region=us-east-1 0 0`

**Comment by kahing** [comment]
you can add `--debug_fuse` to see the individual IO calls and also `--debug_s3` to see the S3 requests

**Comment by kevinlong206** [comment]
Thanks very much. This helped show me in syslog that apache was recursively looking for index.html file in all subdirectories. Settings DirectoryIndex disabled  fixed the issue for me in apache. Cheers!

**Comment by JaneSoo** [comment]
@kevinlong206 How did you do that? I also have DirectoryIndex disabled but it's still very slow for me. Files under my directory are in total around 15GB. It took almost 15 mins to load. (I host the webserver inside container and wonder if it could be the issue)

here is what I set in httpd.conf file
```
<IfModule dir_module>
    DirectoryIndex disabled
</IfModule>
```
