### ISSUE TITLE
use of internal package github.com/kahing/goofys/internal not allowed

### ISSUE THREAD

**Issue by charlesgogo01** [kahing/goofys#454]
error when go build goofys in local. my golang version is go1.12.7 
and IDE is goland.

the error message is:
use of internal package github.com/kahing/goofys/internal not allowed

how to fix it?

**Comment by kahing** [comment]
how are you building it? Where did you checkout goofys to? Seems like you have the checkout in an incorrect `GOPATH`: https://github.com/golang/go/wiki/GOPATH
