### ISSUE TITLE
 'go install github.com/kahing/goofys' failed 

### ISSUE THREAD

**Issue by yangzh** [kahing/goofys#463]
I'm using Go 1.13 on Mac:
$ go version
go version go1.13 darwin/amd64

Here is what I saw:

 go install github.com/kahing/goofys

..........
go: downloading github.com/cpuguy83/go-md2man v1.0.10
go: extracting github.com/Azure/go-autorest/autorest/date v0.2.0
go: downloading github.com/mattn/go-ieproxy v0.0.0-20190702010315-6dee0af9227d
go: downloading github.com/Azure/go-autorest/logger v0.1.0
go: extracting github.com/Azure/go-autorest/logger v0.1.0
go: extracting github.com/Azure/go-autorest/autorest/to v0.3.0
go: extracting github.com/cpuguy83/go-md2man v1.0.10
go: finding github.com/Azure/go-autorest/autorest/validation v0.2.0
go: extracting github.com/mattn/go-ieproxy v0.0.0-20190702010315-6dee0af9227d
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.0-20190314233015-f79a8a8ca69d
go: downloading github.com/Azure/go-autorest/autorest/validation v0.2.0
go: extracting github.com/cpuguy83/go-md2man/v2 v2.0.0-20190314233015-f79a8a8ca69d
go: downloading github.com/russross/blackfriday v1.5.2
go: extracting github.com/Azure/go-autorest/autorest/validation v0.2.0
go: extracting github.com/russross/blackfriday v1.5.2
go: downloading github.com/russross/blackfriday/v2 v2.0.1
go: extracting github.com/russross/blackfriday/v2 v2.0.1
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
go: extracting github.com/shurcooL/sanitized_anchor_name v1.0.0
go: finding github.com/cpuguy83/go-md2man/v2 v2.0.0-20190314233015-f79a8a8ca69d
go: finding github.com/mattn/go-ieproxy v0.0.0-20190702010315-6dee0af9227d
go: finding github.com/Azure/go-autorest/autorest/date v0.2.0
go: finding github.com/Azure/go-autorest/tracing v0.5.0
go: finding github.com/russross/blackfriday/v2 v2.0.1
go: finding github.com/Azure/go-autorest/logger v0.1.0
go: finding github.com/dimchansky/utfbom v1.1.0
go: finding github.com/shurcooL/sanitized_anchor_name v1.0.0
# github.com/kahing/goofys/internal
../../../../go/pkg/mod/github.com/kahing/goofys@v0.21.0/internal/backend_adlv1.go:112:9: assignment mismatch: 2 variables but "github.com/satori/go.uuid".NewV4 returns 1 values
../../../../go/pkg/mod/github.com/kahing/goofys@v0.21.0/internal/backend_adlv1.go:527:15: assignment mismatch: 2 variables but "github.com/satori/go.uuid".NewV4 returns 1 values

**Comment by kahing** [comment]
I don't think `go install` is correctly handling git submodules. Could you do `go submodule update` first in the repo, or use `go get github.com/kahing/goofys`?
