### ISSUE TITLE
E297: Write error in swap file

### ISSUE THREAD

**Issue by bs-thomas** [kahing/goofys#466]
Hello there, I'm facing the issue of just editing a small text file using "vi".

When I "vi"'d into a new file, or existing file, and then start inserting text, it will return this:
- E297: Write error in swap file

![image](https://user-images.githubusercontent.com/2464920/65439199-5faade80-de59-11e9-9d3e-e6dd11918bb7.png)

Saving it using ":w" works, but just the swap file not working (possibly due to it being hidden I'm guessing?)

Odd thing here is, this is happening under debian docker image, but not the equivalent docker image for golang:1.13.0-alpine.

If you could shed me some light, I'd appreciate a lot!!

This issue is related to #209 so I'm just tagging it here.

**Comment by bs-thomas** [comment]
Very interesting, I noticed that under the golang image (golang:1.13-alpine), it seems that doing "vi" seems to make no "swp" file.  So, if it crashes, nothing gets saved.

I wonder if that's the reason already.

But at the same time quite curious, was that my config problem (something brokedown during a series of installation commands)?  Or is it related the OS defaults?

**Comment by kahing** [comment]
disable swp file in vi
