### ISSUE TITLE
installation error 

### ISSUE THREAD

**Issue by amitkertis17** [kahing/goofys#472]
hi i follow the procedure and i get this error when i run this command 
go get github.com/kahing/goofys

i am using go version 1.8

ccloud@amitkertes-goofys:~$ go get github.com/kahing/goofys
# github.com/kahing/goofys/vendor/google.golang.org/grpc/credentials/internal
work/src/github.com/kahing/goofys/vendor/google.golang.org/grpc/credentials/internal/syscallconn.go:29: syntax error: unexpected = in type declaration
# github.com/kahing/goofys/vendor/google.golang.org/grpc/internal/syscall
work/src/github.com/kahing/goofys/vendor/google.golang.org/grpc/internal/syscall/syscall_linux.go:79: tcpconn.SyscallConn undefined (type *net.TCPConn has no field or method SyscallConn)
work/src/github.com/kahing/goofys/vendor/google.golang.org/grpc/internal/syscall/syscall_linux.go:100: tcpconn.SyscallConn undefined (type *net.TCPConn has no field or method SyscallConn)
# github.com/kahing/goofys/vendor/google.golang.org/grpc/resolver/dns
work/src/github.com/kahing/goofys/vendor/google.golang.org/grpc/resolver/dns/dns_resolver.go:91: unknown field 'Dial' in struct literal of type net.Resolver
# github.com/kahing/goofys/vendor/golang.org/x/net/http2
work/src/github.com/kahing/goofys/vendor/golang.org/x/net/http2/server.go:220: s.RegisterOnShutdown undefined (type *http.Server has no field or method RegisterOnShutdown)

**Comment by kahing** [comment]
you need to upgrade go
