### ISSUE TITLE
goofys rel 22 returns incomplete file lists

### ISSUE THREAD

**Issue by msmitherdc** [kahing/goofys#474]
After upgrading to goofys release 22 we started getting inconsistent results from the number of files in large buckets. The bucket contained 354714 files in many nested folders. Using `find -type f | wc -l ` on the goofys mount returned 129544 the first call and 225603 the second call. Changing back to r20 and r21 both returned the same number that aws s3 ls --recursive returned, 354714.

**Comment by kahing** [comment]
Is it possible for you attach the list result?

**Comment by msmitherdc** [comment]
[file_lists_2_goofys_versions.zip](https://github.com/kahing/goofys/files/3827933/file_lists_2_goofys_versions.zip)
Different bucket with public names. One list from goofys 21 and one list from goofys 22. Count from 21 is correct according to aws s3 ls

**Comment by kahing** [comment]
@msmitherdc could you see if the commit fixed the issue for you?

**Comment by msmitherdc** [comment]
@kahing yes, the issue is fixed with this change
