### ISSUE TITLE
Build failure since azure-sdk-for-go's storageapi interface was changed

### ISSUE THREAD

**Issue by t2y** [kahing/goofys#476]
I tried to build goofys, but I couldn't.

```bash
$ make get-deps
go get -t ./...
# github.com/kahing/goofys/api/common
api/common/conf_azure.go:272:34: accountsRes.Value undefined (type storage.AccountListResultPage has no field or method Value)
api/common/conf_azure.go:373:35: not enough arguments in call to client.ListKeys
	have (context.Context, string, string)
	want (context.Context, string, string, storage.ListKeyExpand)
make: *** [get-deps] Error 2
```

It seems  azure-sdk-for-go's storageapi interface was changed at 2019-10-31.

* https://github.com/Azure/azure-sdk-for-go/blame/master/services/storage/mgmt/2019-04-01/storage/storageapi/interfaces.go#L50
* https://github.com/Azure/azure-sdk-for-go/blame/master/services/storage/mgmt/2019-04-01/storage/accounts.go#L836

**Comment by kahing** [comment]
Are you using the vendored git submodules?

**Comment by t2y** [comment]
Maybe, No.

In my environment (macOS 10.14.6), git clone goofys repository into `$HOME/go/src/github.com/kahing/goofys` and run `make get-deps`. And then, azure-sdk-for-go was fetched into `$HOME/go/src/github.com/Azure/azure-sdk-for-go` and used.

hmm, is this my wrong operation?

**Comment by kahing** [comment]
The easiest thing to do is install goofys via Homebrew. Another thing you can do is run `git submodule init` and `git submodule update`

**Comment by t2y** [comment]
I could build as below. Thank you!

```bash
$ git submodule init
$ git submodule update
$ make build
go build -ldflags "-X main.Version=`git rev-parse HEAD`"
$ ./goofys --version
goofys version 0.23.0-674fcca3e055e8b667e5b307ee250441460ad592
```

**Comment by Fiber-Man** [comment]
#527
