### ISSUE TITLE
0.23 release downloading as 0.22 binary?

### ISSUE THREAD

**Issue by cloudguy23** [kahing/goofys#477]
Downloaded 0.23 release (binary), however showing up as:

```
# ./goofys.dms -v
goofys version 0.22.0-67dee3274f7b3744351f6dfae7216c7593b289a2
```

**Comment by kahing** [comment]
Yes I must have made a mistake. Thankfully 67dee3274f7b3744351f6dfae7216c7593b289a2 is the commit right before the tag so it should have exactly the same fixes as the real 0.23.0. I will make a 0.23.1 release
