### ISSUE TITLE
Cannot `umount` without `sudo`

### ISSUE THREAD

**Issue by CrashyBang** [kahing/goofys#481]
Hey there!

Everything works as expected however I cannot unmount using `umount` or my file manager without `sudo` (or opening my file manager with `sudo`).

I can use:
```
fusermount -u s3 
```

So it's not really a bit deal, would just be nice to be able to do from file manager.

**Comment by kahing** [comment]
which file manager do you use? This is a problem with your file manager not goofys. `umount` is supposed to require root (hence the reason there's `fusermount`
