### ISSUE TITLE
Automount isn't working

### ISSUE THREAD

**Issue by crypticspawn** [kahing/goofys#489]
I have the mounting set up in fstab to look like this:

    goofys#<<mybucket>> 				/mnt/drive_z		fuse 	_netdev,allow_other,--dir-mode=0777,--file-mode=0777		0 	0

However when I look into the syslogs to find out why it didn't mount I get this:

    Jan 20 17:37:57 localhost /usr/local/bin/goofys[1369]: s3.ERROR code=RequestError msg=send request failed, err=Head https://s3.amazonaws.com/<bucket-name>/pfoxgtph0qsjb70j6nta5vu3khezbdo1: dial tcp: lookup s3.amazonaws.com on 8.8.4.4:53: dial udp 8.8.4.4:53: connect: network is unreachable
    Jan 20 17:37:57 localhost /usr/local/bin/goofys[1369]: main.ERROR Unable to access '<bucket-name>': RequestError: send request failed#012caused by: Head https://s3.amazonaws.com/<bucket-name>/pfoxgtph0qsjb70j6nta5vu3khezbdo1: dial tcp: lookup s3.amazonaws.com on 8.8.4.4:53: dial udp 8.8.4.4:53: connect: network is unreachable
    Jan 20 17:37:57 localhost /usr/local/bin/goofys[1369]: main.FATAL Mounting file system: Mount: initialization failed

I understand _netdev is suppose to wait until we are connected to the internet, but the message seems to contradict this assumption of that option.  I have goofys automounting successfully on another computer without a problem in the same colo.

**Comment by kahing** [comment]
are there any other differences between the two setup? Could you reach `8.8.4.4` after startup?

**Comment by crobibero** [comment]
I'm also having this issue upon reboot with Wasabi

```
Feb 27 16:18:20 cloud /usr/bin/goofys[492]: s3.ERROR Unable to access 'my-bucket': dial tcp: lookup s3.wasabisys.com on [::1]:53: read udp [::1]:53870->[::1]:53: read: connection refused
Feb 27 16:18:20 cloud /usr/bin/goofys[492]: s3.ERROR code=RequestError msg=send request failed, err=Head https://s3.wasabisys.com/my-bucket/my-key: dial tcp: lookup s3.wasabisys.com on [::1]:53: read udp [::1]:60462->[::1]:53: read: connection refused#012
Feb 27 16:18:20 cloud /usr/bin/goofys[492]: s3.ERROR code=RequestError msg=send request failed, err=Head https://s3.wasabisys.com/my-bucket/my-key: dial tcp: lookup s3.wasabisys.com on [::1]:53: read udp [::1]:60462->[::1]:53: read: connection refused#012
Feb 27 16:18:20 cloud /usr/bin/goofys[492]: s3.ERROR code=RequestError msg=send request failed, err=Head https://s3.wasabisys.com/my-bucket/my-key: dial tcp: lookup s3.wasabisys.com on [::1]:53: read udp [::1]:60462->[::1]:53: read: connection refused#012
Feb 27 16:18:20 cloud /usr/bin/goofys[492]: main.ERROR Unable to access 'my-bucket': RequestError: send request failed#012caused by: Head https://s3.wasabisys.com/my-bucket/my-key: dial tcp: lookup s3.wasabisys.com on [::1]:53: read udp [::1]:60462->[::1]:53: read: connection refused
Feb 27 16:18:20 cloud /usr/bin/goofys[492]: main.FATAL Mounting file system: Mount: initialization failed
```

I can successfully mount the bucket after SSHing in and running `mount -a`

**Comment by crypticspawn** [comment]
The differences between the other system was how we were setting up the network, after forcing network manager to control my setup, the auto-mount started working.  So changed to this:

# This file describes the network interfaces available on your system
# For more information, see netplan(5).
network:
  version: 2
  renderer: NetworkManager
  ethernets:
    enp3s0:
      dhcp4: yes
 
for my netplan config file.
