### ISSUE TITLE
File caches on first read, updates can be read only after PageCache reset

### ISSUE THREAD

**Issue by arraen** [kahing/goofys#490]
Hi,
We work with files that change from time to time, but on a remote host, we can't see these changes.
Only `echo 1 > /proc/sys/vm/drop_caches` fix this.
Is there is a way to enable direct_io for goofys?
OS:
RHEL 7.6.1810, kernel: 3.10.0-957.10.1.el7.x86_64, goofys 0.23.1
fstab:
`#goofys#goofys-bucket   /mnt/goofys       fuse     _netdev,allow_other,--file-mode=0775,--stat-cache-ttl=0,--type-cache-ttl=0  0       0`

**Comment by kahing** [comment]
have you tried with lower `--type-cache-ttl` and `--stat-cache-ttl` settings?

**Comment by arraen** [comment]
Yes, tried with `--type-cache-ttl=0,--stat-cache-ttl=0` - same results.
OS: RHEL 7.6.1810, kernel: 3.10.0-957.10.1.el7.x86_64, goofys 0.23.1

**Comment by kahing** [comment]
I added a test for this and it seems to pass: https://github.com/kahing/goofys/blob/d90a07e99f557093d6d30eef9302c95365f40ba4/internal/goofys_test.go#L4002

do you have steps that I can reproduce the problem with?

**Comment by arraen** [comment]
What we a doing to test this issue:
1. From one host run $ watch -n2 "date > test_date.txt"
2. On second $ watch -n2 "cat test_date.txt"
3. Looking for test_date.txt update on a second host
From S3 console we can see changes in test_date.txt.
On the second host only after remount and only one change.

**Comment by kahing** [comment]
@arraen could you see if the fix works for you?

**Comment by arraen** [comment]
@kahing Yes, works perfectly now. Thank you!
