### ISSUE TITLE
Azure automount fstab

### ISSUE THREAD

**Issue by gussj** [kahing/goofys#491]
Hi there, I have a question that I couldn't find an answer. I actually mounted an azure blob storage account with this command:
goofys -o allow_other --file-mode=0777 --dir-mode=0777 wasb://account@address /azure/storage

What is the correct line that I need to add in the fstab to auto mount this?. I have configured the .azure/config file.

Thanks.

**Comment by gussj** [comment]
Hello! @kahing can you help me on this? Thanks.

**Comment by kahing** [comment]
similar fstab as s3 works fine:

```
goofys#wasb://BUCKET@ACCOUNT.blob.core.windows.net       /tmp/mnt        fuse    _netdev,allow_other,--file-mode=0666,--dir-mode=0777    0       0
```
