### ISSUE TITLE
Can't disable Caching 

### ISSUE THREAD

**Issue by epgrvp** [kahing/goofys#50]
Hi,

I.ve experimented with --stat-cache-ttl=0,--type-cache-ttl=0 in fstab, but I can't disable caching.
Example:
1) perl -e 'print "found\n" if (-f "/mnt/07ooBP_g87NjF2oX6mGSzHnWodE/abcd.pdf")'
=> found

2) Unlink the file abcd.pdf via Web-UI or from another host mounting the same Bucket

3) perl -e 'print "found\n" if (-f "/mnt/07ooBP_g87NjF2oX6mGSzHnWodE/abcd.pdf")'
=> found

4) perl -e 'print "found\n" if (-f "/mnt/07ooBP_g87NjF2oX6mGSzHnWodE/abcd.pdf")'
from another host mounting the same bucket
=> not found

I need to disable caching because I want to check for existance of a file in a bucket. And need to have the files with a prefix like above to make them downloadable via S3.

My fstab-entry:
goofys#mybucket   /mnt fuse _netdev,allow_other,--uid=300,--stat-cache-ttl=0,--type-cache-ttl=0 0   0

Any hints?

I can flush the inodes cache with 'echo 2 > /proc/sys/vm/drop_caches', what helps, but this is an performance killer...

**Comment by kahing** [comment]
this is fixed. haven't written a test for this yet since our existing tests are either too low level, or too high level which lacks s3 setup.

**Comment by epgrvp** [comment]
Thanks, I'll give it a try asap!
