### ISSUE TITLE
Can't get nofail to work

### ISSUE THREAD

**Issue by Gabisonfire** [kahing/goofys#512]
Hi,

I'm mounting a bucket using fstab, I was not able to make the nofail option work otherwise it mounts perfectly. I've tried:

`goofys#bucket /mnt/bucket      fuse     _netdev,allow_other,nofail,--endpoint=s3.wasabisys.com,--file-mode=0666,--dir-mode=0777    0       0`

`goofys#bucket /mnt/bucket      fuse     _netdev,allow_other,-o=nofail,--endpoint=s3.wasabisys.com,--file-mode=0666,--dir-mode=0777    0       0`

All of them fails with

> Apr 09 22:50:13  /usr/sbin/goofys[26277]: main.FATAL Mounting file system: Mount: mount: invalid argument
Apr 09 22:52:57 /usr/sbin/goofys[27430]: s3.ERROR Unable to access 'bucket': unsupported protocol scheme ""

Is that possible/needed? I'd like to make sure my machine will boot even if the endpoint is down, or the credentials are accidentaly deleted etc.

Thanks!

**Comment by kahing** [comment]
`--endpoint` needs to include `https://`

**Comment by Gabisonfire** [comment]
Still getting a
> main.FATAL Mounting file system: Mount: mount: invalid argument
error.

endpoint works just fine without https:// by the way, as I said I'm able to mount without issues.
> I was not able to make the nofail option work otherwise it mounts perfectly. 

The issue is the "nofail" option not working.

**Comment by Gabisonfire** [comment]
bump @kahing
