### ISSUE TITLE
Can Authorization information be included in goofys request？

### ISSUE THREAD

**Issue by captainzmc** [kahing/goofys#513]
Mount the directory with goofys, and when I read or write the directory, I find that Authorization is not included in the request.
What configuration can I use to pass in the AccessKeyID of the current user. I see goofys has [this part of the function,](https://github.com/kahing/goofys/blob/b2302fdf5af978f1698c0b21f38f01928da25b2f/internal/v2signer.go#L192) but do not know how to configure.

**Comment by captainzmc** [comment]
Authorization in request should be similar to:
"Authorization: AWS test@apache.org: NvBkxWmMlmRogBCGROKAoEJ4fuo = [\ r] [\ n]"

I debug the current request as follows:
`2020/04/14 15:01:21.414120 s3.DEBUG DEBUG: Request s3/HeadObject Details:`
`---[ REQUEST POST-SIGN ]-----------------------------`
`HEAD /bucket1/test3 HTTP/1.1`
`Host: localhost:9878`
`User-Agent: aws-sdk-go/1.17.13 (go1.13.1; linux; amd64)`

**Comment by maobaolong** [comment]
New a file ~/.aws/credentials , with the following content.
```properties
[default]
aws_access_key_id=12345678
aws_secret_access_key=12345678
```

And exexute goofys with the `--profile`, for example

```bash
$ goofys --profile default --endpoint http://localhost:9878  mybucket /data/montpointdir
```

such like this, goofys will send the Authorization header to s3.

Thanks @captainzmc for telling me this. I just share it.
