### ISSUE TITLE
Unable to read read-only public bucket

### ISSUE THREAD

**Issue by msmitherdc** [kahing/goofys#52]
example:
```
[root@ip ec2-user]# export GOPATH=$HOME/gopath
[root@ip ec2-user]# $GOPATH/bin/goofys -o ro --dir-mode 0555 --file-mode 444   lidar_fema /femadata/
[root@ip ec2-user]# ls /femadata/
ls: reading directory /femadata/: Input/output error
```

**Comment by kahing** [comment]
the above bucket is in us-east-1 and goofys can't detect the bucket region because permission is not granted for s3:GetBucketLocation. We can't do much to detect the region via 301 until https://github.com/aws/aws-sdk-go/issues/542 is fixed. For now use --region us-east-1 as a workaround.

**Comment by msmitherdc** [comment]
Just to let you know, it worked perfectly. Much thanks.

**Comment by kahing** [comment]
You are welcome! Thanks for reporting this. 

For future reference goofys log to syslog when foreground mode is not enabled.
