### ISSUE TITLE
Append question

### ISSUE THREAD

**Issue by let4be** [kahing/goofys#53]
Is append to file implemented and if so how(hopefully not via overwrite the whole file)?
I would like to use goofys to store append only file for redis

**Comment by kahing** [comment]
There's rudimentary support for append in the append branch. It works by doing a multi-part upload with the existing chunks copied on the server side (https://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadUploadPartCopy.html). I haven't tested the performance but I don't imagine that it would be good enough for redis like workload where every append has to be persistent right away.

**Comment by kahing** [comment]
probably won't be supported, closing to avoid confusion
