### ISSUE TITLE
Use /etc/mime.types to set Content-Type accordingly

### ISSUE THREAD

**Issue by tdi** [kahing/goofys#54]
My server created bunch of css files automatically and they got written to S3 with `Content-Type:binary/octet-stream`, which is the default. 

It would be nice if goofys could guess MIME type and set the header accordingly (same as s3fs does it).

**Comment by reo7sp** [comment]
#60

**Comment by AndydeCleyre** [comment]
Yes, please. This can actually be a pretty big problem.

In python, the known mimetypes could be read into a `dict` as follows:

```python
with open('/etc/mime.types') as mimetypes_file:
    mimetypes = {}
    for line in mimetypes_file:
        if len(line.split('\t')) > 1:
            extensions = line.split('\t')[-1].split()
            for ext in extensions:
                mimetypes[ext] = line.split('\t')[0]
```

**Comment by AndydeCleyre** [comment]
Is the best workaround for this right now using a custom AWS lambda function to act whenever a new file appears in a bucket?

**Comment by AndydeCleyre** [comment]
Excellent, thanks!
