### ISSUE TITLE
Storage class dependency of object size

### ISSUE THREAD

**Issue by ssvinarev** [kahing/goofys#546]
https://github.com/kahing/goofys/blob/master/internal/backend_s3.go
In CopyBlob and in PutBlob there are conditions for storage class of objects less than 128*1024 or more.
- Could you please explain the reason of that?
- Is it save to reduce it to 128 bytes or less?

**Comment by dotslash** [comment]
IIUC, With STANDARD_IA, files smaller than 128KB will be charged as if they are 128KB. 
See https://github.com/kahing/goofys/pull/255

**Comment by ssvinarev** [comment]
Looks like it's AWS specific.
Thanks!
