### ISSUE TITLE
IAM Instance Profile support?

### ISSUE THREAD

**Issue by rowanu** [kahing/goofys#55]
Does goofys support instance profile-based access? I can't see any mention or reference to it.

**Comment by kahing** [comment]
aws-go-sdk supports it, I believe we just need to plumb the options through. Want to try to submit a patch? ;-)

**Comment by lrowe** [comment]
It works for me.

**Comment by kahing** [comment]
@lrowe could you describe your setup and I will add it to README?

**Comment by lrowe** [comment]
There is no setup... I have no .aws/credentials file so presumably the aws-go-sdk is simply falling back to the instance keys.

**Comment by kahing** [comment]
@rowanu is that good enough for you?

**Comment by rowanu** [comment]
Sounds like it, thanks for sharing.
