### ISSUE TITLE
Update aws-sdk-go to support IRSA

### ISSUE THREAD

**Issue by ameir** [kahing/goofys#556]
In order to support IAM Roles for Service Accounts, the minimum version of the Go SDK needs to be 1.23.13 (https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html). It's currently 1.17.13. This should be auto-fixed after merging #555.

**Comment by iptizer** [comment]
Sooo, is this already solved?

**Comment by ameir** [comment]
Based on current master, I believe this is sorted. I don't have an active EKS project that uses goofys right now to validate. I'll leave open for someone to confirm.

**Comment by monthonk** [comment]
I can confirm that goofys is now support IRSA. related with https://github.com/kahing/goofys/issues/703

**Comment by ameir** [comment]
Thank you for confirming!
