### ISSUE TITLE
 Out of memory: Kill process 3155 (goofys)

### ISSUE THREAD

**Issue by Classsic** [kahing/goofys#56]
this error :Feb 11 12:50:11 localhost kernel: Out of memory: Kill process 3155 (goofys) score 202 or sacrifice child
is about buffer memory?
How I can fixit manually?
Thanks

**Comment by kahing** [comment]
What version are you using?

**Comment by Classsic** [comment]
goofys version 0.0.3.
Logs:
Feb 11 12:50:11 localhost kernel: [ 3155]     0  3155   164285    57782     202       5     8768             0 goofys
Feb 11 12:50:11 localhost kernel: Out of memory: Kill process 3155 (goofys) score 202 or sacrifice child
Feb 11 12:50:11 localhost kernel: Killed process 3155 (goofys) total-vm:657140kB, anon-rss:231128kB, file-rss:0kB
Feb 11 20:31:22 localhost /usr/bin/goofys[378]: s3.INFO Switching from region 'us-west-2' to 'us-east-1'
Feb 11 20:31:22 localhost /usr/bin/goofys[378]: main.FATAL Mounting file system: Mount: mount: fusermount: exit status 1
Feb 11 20:53:49 localhost /usr/bin/goofys[3600]: s3.INFO Switching from region 'us-west-2' to 'us-east-1'
Feb 11 20:53:49 localhost /usr/bin/goofys[3600]: main.INFO File system has been successfully mounted.
Feb 11 20:53:55 localhost /usr/bin/goofys[3600]: main.INFO Successfully exiting.
Feb 11 20:55:38 localhost /usr/bin/goofys[11736]: s3.INFO Switching from region 'us-west-2' to 'us-east-1'
Feb 11 20:55:38 localhost /usr/bin/goofys[11736]: main.INFO File system has been successfully mounted.
Feb 11 20:59:00 localhost /usr/bin/goofys[11736]: main.INFO Successfully exiting.
Feb 11 20:59:08 localhost /usr/bin/goofys[22555]: s3.INFO Switching from region 'us-west-2' to 'us-east-1'
Feb 11 20:59:08 localhost /usr/bin/goofys[22555]: main.INFO File system has been successfully mounted.
-------------------------------
I love the speed of goofys, but I want to know if is enough stable for production.
Thanks for your project.

**Comment by kahing** [comment]
This should be fixed in 0.0.4

**Comment by Classsic** [comment]
Ok, I'll try it.
Thanks again.
