### ISSUE TITLE
Goofys fails on mkdir in OpenStack Swift 3

### ISSUE THREAD

**Issue by viktoriaas** [kahing/goofys#597]
Hello,

we use goofys (0.24.0) with openstack swift3 (2.23.1). Mounting is ok, bud `mkdir any_dir` causes failures, as openstack swift3 refuses putting directory without issuing content-type: application/directory header. 

See:
`<?xml version='1.0' encoding='UTF-8'?>
<Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>tx8b3004fd08cb4a658fba2-005ff883ae</RequestId><Reason>Invalid object name \"any_dir/\", object path can end with a slash only if it is a directory marker object with \"Content-Type: application/directory\" header</Reason></Error>`

Is this a known issue or can we somehow fix this easily?

**Comment by kahing** [comment]
sounds like this version of swift3 isn't quite s3 compatible.
