### ISSUE TITLE
Permission denied errors, no other debug data

### ISSUE THREAD

**Issue by forrie** [kahing/goofys#601]
My .aws/credentials file is correct, the credentials are correct, the mount point I am referencing is correct and has the correct permissions.  I am not able to get goofys to work, the errors are generic:

```
Jan 13 12:08:53 MacbookPro /Users/[username]/work/bin/goofys[74629]: main.ERROR Unable to access '[mybucket]': permission denied
Jan 13 12:08:53 MacbookPro /Users/[username]/work/bin/goofys[74629]: main.FATAL Mounting file system: Mount: initialization failed
```

This doesn't really tell me what the problem is.  Can I solicit more debugging information from goofys?

At one point, my terminal (iTerm) became unresponsive, and I saw the log kill off a dead process -- may or may not be related to this usage above.

**Comment by dotslash** [comment]
Goofys tries to head `[MOUNTED_BUCKET]/[MOUNTED_PREFIX]/[RANDOM_BLOB]` when inititializing the mount. A 404 response or 200 => the given credentials are most likely to work.

If you think you have the right credentials, can you share the output after running goofys with `--debug_s3` `--debug_fuse` ?
