### ISSUE TITLE
Goofys crashes on Openshift

### ISSUE THREAD

**Issue by deekshahegde86** [kahing/goofys#602]
I am using goofys on a container running on openshift.

The container uses Goofys to mount readonly publick buckets to the container to read and view the data.

command i have used is:
goofys --uid=1001 --gid=1001 --file-mode=0555 --dir-mode=0555 landsat-pds /home/user/landsat-8-dataset/landsat-pds/data

The openshift runs the container in privileged mode with privileged SCC given to service account.

Issue:
When i try to open the file using either vi editor or any developer tool like VS code or Jupyterhub, the goofys crashes and pulls off the content. 
I then have to run fusermount -u <mountpath> to unmount and remount the S3 with goofys command.

This behaviour is seen only in openshift, while the same container runs perfectly fine on a normal Docker setup. 
Another thing i noticed is that the goofys doesnt crash on openshift if we use -f option in it. While without -f , it crashes as described above.

When i run the goofys with -f option on openshift , it desnt crash instead, i see the errors for the following 2 actions performed:
(NOTE: It doesnt crash and opens file for viewing and gives the relevant error with -f option. While without -f , it crashes and pulls of the mount content.)

1) open a file
Error:
2021/01/15 07:11:21.124795 fuse.ERROR *fuseops.MkDirOp error: permission denied
2021/01/15 07:11:21.268991 fuse.ERROR *fuseops.MkDirOp error: permission denied

2) Save/create a new file to the mount location
Error:
2021/01/15 07:14:43.738977 fuse.ERROR *fuseops.FlushFileOp error: permission denied
2021/01/15 07:14:49.722047 fuse.ERROR *fuseops.GetInodeAttributesOp error: no such file or directory

I am blocked with the solution on openshift and need help on the same.

**Comment by dotslash** [comment]
Can you share the logs when you run goofys with --debug_fuse, --debug_s3 flag?
