### ISSUE TITLE
build by go.mod

### ISSUE THREAD

**Issue by wsyangyun** [kahing/goofys#609]
hi can you let it build with mod?so we can konw the dependent of version

**Comment by djmaze** [comment]
This tool seems unfortunately not be maintained anymore. But there is a [fork](https://github.com/kahing/goofys/issues/542#issuecomment-705064973) which you can use for go module support.

**Comment by dotslash** [comment]
this is done recently https://github.com/kahing/goofys/commit/e3748e3cdfe2d2f5ca775e6370020ff863ad6599
