### ISSUE TITLE
Handle AJAX write to S3 via PHP fails for large files

### ISSUE THREAD

**Issue by pkrulz** [kahing/goofys#611]
I am providing more details about the implementation since I have little knowledge of file systems.

I have been trying to implement an image gallery piwigo (http://piwigo.org/) on an AWS EC2 t2 machine.  I intend to store the images on S3 using goofys. 
I created a folder in /home/ubuntu and mounted a S3 folder to it and then softlinked it to the upload folder of piwigo web gallery.

The web gallery allows file upload through a web-browser and this fails for large files (> 900kB). When I changed the upload folder to a native one it works fine. I understand this might has something to do with caching.  I dont intend to use catfs since it is a prod environment.

Any inputs would be great. Thanks.

**Comment by dotslash** [comment]
> The web gallery allows file upload through a web-browser and this fails for large files (> 900kB). 

Can you explain in detail what is failing here? Maybe share your code/logic of how you are writing to the goofys mounted directory?

Can you also share the goofys log? I have a gut feeling that your code is doing "random writes" that goofys does not support.

**Comment by pkrulz** [comment]
Its possible that piwigo does random writes. You can check the code from piwigo. Its opensource. probably this is the page responsible for upload from webform
https://github.com/Piwigo/Piwigo/blob/master/admin/photos_add.php 

I had mounted my drive using this in fstab
goofys#bucket   /mnt/mountpoint        fuse     _netdev,allow_other,--file-mode=0744,--dir-mode=0777    0       0

Regards

**Comment by pkrulz** [comment]
Where do I get the goofys log

**Comment by dotslash** [comment]
goofys log goes to syslog. The location in most OSs is `/var/log/syslog` 

If random write is indeed the issue, the workaround is to write to a local file and then move to the location where goofys is mounted
