### ISSUE TITLE
High CPU utilization on idle mount.

### ISSUE THREAD

**Issue by bedge** [kahing/goofys#62]
I'm seeing 2 cores maxed out by the goofys daemon.

Mount opts are:
```
123.bucketname.xxx.com on /content-goofys type fuse (rw,nosuid,nodev,default_permissions,allow_other)
```
top shows 2 threads maxed out:
```
top - 17:13:33 up 1 day, 18:38,  8 users,  load average: 4.08, 4.33, 5.07
Tasks: 190 total,   1 running, 188 sleeping,   0 stopped,   1 zombie
%Cpu(s): 50.5 us,  0.2 sy,  0.0 ni, 49.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:  16433132 total, 13873464 used,  2559668 free,   245852 buffers
KiB Swap:        0 total,        0 used,        0 free.  8638932 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
10801 root      20   0 7016036 2.715g   4276 S 200.1 17.3   1556:48 goofys
```
version is:
```
goofys version 0.0.4
```
terminating & restarting the mount resolved the CPU issue. Not sure what caused it in the 1st place.

**Comment by kahing** [comment]
are there other processes reading from the mountpoint at the time? Also please upgrade to 0.0.5 as that fixes a deadlock issue (probably not related to your problem though)

**Comment by kahing** [comment]
and if you could attach a debugger and see what it was doing, that would be even better

**Comment by bedge** [comment]
At the time the connection was idle. All goofys clients had timed out and terminated
I have upgraded to 0.0.5 since this was reported.
Will be re-running tests with the newer version.

One thing I can say is that there are many concurrent threads accessing the mount point when the tests are running. So if this hasn't been tested with a high level of concurrency, that may be related.

If it happens again, it's in AWS, so I could get you access to the VM if you want to see first hand.

**Comment by bedge** [comment]
Have not been able to replicate with 0.0.5 running high volume.
