### ISSUE TITLE
High memory use by goofys

### ISSUE THREAD

**Issue by musicjeremy** [kahing/goofys#621]
goofys is using ~55GB of system memory on a 128GB PC.

1633376 root      20   0   54.8g  54.7g   8304 S  38.4  43.5   8:09.88 goofys 
                                                                                                                                                                                               
I am mounting via fstab:
goofys#bucket /mnt/cloud fuse _netdev,allow_other,--file-mode=0666,--dir-mode=0777,--endpoint=https://s3.cloud.io 0 0

goofys version 0.24.0-45b8d78375af1b24604439d2e60c567654bcdf88
Linux tr3690x 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Not sure how to begin troubleshooting this. let me know what other info you need...

**Comment by kahing** [comment]
goofys uses up to 50% of free memory. If you run other memory intensive programs, goofys should eventually autotune and use less memory.

**Comment by aek** [comment]
It's there a way to control how memory will be used by goofys or at least the number of process forked for goofys?
