### ISSUE TITLE
--uid/gid not working

### ISSUE THREAD

**Issue by tomercagan** [kahing/goofys#63]
Hi,

I have a node.js app and thought to share a mount between nodes in my cluster (EC2 instance) using an S3 mount (for users upload, which will be served through a static s3 site).

I am trying to use goofys for mounting the S3 bucket. 

I followed the installation instruction and I am able to mount my bucket and see the files as the root user (centos). I am not able to access it as the web user (which supposed to run the node.js application):

```
[centos@ip-172-31-16-222` ~]$ id web
uid=995(web) gid=992(web) groups=992(web)
[centos@ip-172-31-16-222 ~]$ $GOPATH/bin/goofys --uid "995" --gid "992" -o allow_other my-app-static /mymount
[centos@ip-172-31-16-222 ~]$ cd /mymount/share/
files/      index.html  store/      uploads/    users/
[centos@ip-172-31-16-222 ~]$ sudo su web
[web@ip-172-31-16-222 centos]$ cd /mymount/share
bash: cd: /mymount/share: Permission denied
[web@ip-172-31-16-222 centos]$
```

Am I doing something wrong?

PS - the installed version I have is goofys version 0.0.4... shouldn't I get the latest version following the install directions in the main readme page?

**Comment by kahing** [comment]
you do want 0.0.5, you may need to use `go get -u` instead of just `go get`. I will look into the other problem later

**Comment by tomercagan** [comment]
I tried to use go get -u but it seems not to update... does my syntax using the uid/gid seem correct?

**Comment by kahing** [comment]
the uid/gid usage seems correct. What does `ls -l /mymount` say?

**Comment by tomercagan** [comment]
I kind of tried another solution. I will try to replicate and report back (thanks for taking the time to help!)

**Comment by kahing** [comment]
Understood. It's odd because I cannot reproduce it here.
