### ISSUE TITLE
mount wasabi with goofys.  No file  no directory  found 

### ISSUE THREAD

**Issue by mushokumunou** [kahing/goofys#632]
using dir command
nothing outup
![キャプチャ](https://user-images.githubusercontent.com/20502227/119542938-aeddab00-bdc2-11eb-90ac-3509e577668b.JPG)

**Comment by lwloo** [comment]
Check your bucket policy, I have this issue earlier and it's due to you did not add the permission for the user you used.

**Comment by kahing** [comment]
please reopen with `--debug_s3` log
