### ISSUE TITLE
Files written into bucket with 0 bytes

### ISSUE THREAD

**Issue by TaijiCoinMaster** [kahing/goofys#637]
Files written with 0 bytes and failed to write:
![image](https://user-images.githubusercontent.com/16340329/120260595-c9cf8400-c2c8-11eb-95f3-2b0718229194.png)

My mounting command:
$GOPATH/bin/goofys -o allow_other --file-mode=0777 --dir-mode=0777 --endpoint https://s3.us-east-1.wasabisys.com mybucket /mymount

I am able to write/create directory/file using cli/gui running on Ubuntu 20.04.

**Comment by kahing** [comment]
can you post your `--debug_s3` log?

**Comment by kahing** [comment]
probably dup of #636
