### ISSUE TITLE
StatFS() takes 1PB as the upper size limit

### ISSUE THREAD

**Issue by squalfof** [kahing/goofys#645]
Within `internal/goofys.go`, there's code about size limit,
```
cosnt BLOCK_SIZE = 4096
const TOTAL_SPACE = 1 * 1024 * 1024 * 1024 * 1024 * 1024 // 1PB
const TOTAL_BLOCKS = TOTAL_SPACE / BLOCK_SIZE
```
is there any restriction on the size of the underlining store, say, AWS S3 ?

Thanks.

**Comment by dotslash** [comment]
1) Looks like s3 has no limits on the bucket size.  I think at some point they had 5PB limit.  https://aws.amazon.com/s3/faqs/ 
> Q: How much data can I store in Amazon S3?
> The total volume of data and number of objects you can store are unlimited. Individual Amazon S3 objects can range in size from a minimum of 0 bytes to a maximum of 5 terabytes. The largest object that can be uploaded in a single PUT is 5 gigabytes. For objects larger than 100 megabytes, customers should consider using the Multipart Upload capability.


2) For azure backends the limit seems to be 5PB
https://docs.microsoft.com/en-us/azure/storage/common/scalability-targets-standard-account?toc=/azure/storage/blobs/toc.json (See  "Maximum storage account capacity"



In goofys i think the limit is set "arbitrarily".

**Comment by squalfof** [comment]
Thanks @dotslash. Tried with a recompilation of `TOTAL_SPACE` to 1TB and mount to a s3 bucket occuping over 100TB, nothing odd happens. Hence 1PB should not be a real limitation.
