### ISSUE TITLE
Is it possible to mount OneDrive with goofys? 

### ISSUE THREAD

**Issue by bohatermateusz** [kahing/goofys#646]
Is it possible to mount OneDrive with goofys?

**Comment by dotslash** [comment]
No, one drive is not supported. What is your use case? Which OS do you use?

**Comment by bohatermateusz** [comment]
Thank for reply! Data exchange with OneDrive (uploading) is really slow and i'm looking for best possible solution. Especially, that cost of OneDrive is much less than S3 solutions. I'm using Ubuntu 20 LTS

**Comment by kahing** [comment]
onedrive isn't supported
