### ISSUE TITLE
Support AWS2 auth type?

### ISSUE THREAD

**Issue by chriss745** [kahing/goofys#65]
I would like to connect with goofys to an S3 compatible storage which uses AWS2 auth type, but it looks goofys supports AWS4 auth only.

AWS2 auth type sample: 
Authorization: AWS user1:+4G7GkgyTtws8L0mFbPnxPyOh6Z=

AWS4 auth type sample: 
Authorization: AWS4-HMAC-SHA256 Credential=user1/20160311/us-west-2/s3/aws4_request, SignedHeaders=host;x-amz-date, Signature=a69111c636a160e34e31a394040f3c0f33db57c53b8bb74ecdf4e349fd554e7x

Is there a way I can connect with goofy to an S3 compatible service which supports only AWS2 auth type?

Thanks!

Chris

**Comment by kahing** [comment]
goofys already supports that and I've had users tested with swift3 (which only supports v2 signing). Could you try --debug_s3 and post the log? Also, which S3 compatible storage are you using?

**Comment by jindov** [comment]
I ran this command to connect to s3-ceph storage (v0.9)
goofys --use-path-request --endpoint http://s3.myhost.net --debug_fuse --debug_s3 bucket_name /path/to/directory

**Comment by chriss745** [comment]
I try to connect EMC's ECS service which offers S3 API. Here is the log:

"root@stemcell-3026:~# goofys --debug_fuse --debug_s3 -f --endpoint http://s-us.objectstorage.io krisztian /mnt
2016/03/16 09:34:55.184068 s3.DEBUG DEBUG: Request s3/HeadBucket Details:
---[ REQUEST POST-SIGN ]-----------------------------
HEAD http://s-us.objectstorage.io/krisztian HTTP/1.1
Host: s-us.objectstorage.io
User-Agent: aws-sdk-go/1.0.0 (go1.6; linux; amd64)
Authorization: AWS4-HMAC-SHA256 Credential=XXXXXXXXXX/20160316/us-west-2/s3/aws4_request, SignedHeaders=host;x-amz-date, Signature=20cae92147d0655a6f97aac467e88321ff4a461bbe5e658cb28c9b55ba1becab
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20160316T093455Z


-----------------------------------------------------
2016/03/16 09:34:57.724552 s3.DEBUG DEBUG: Response s3/HeadBucket Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 403 Forbidden
Connection: close
Connection: keep-alive
Content-Type: application/xml
Date: Wed, 16 Mar 2016 09:38:59 GMT
Proxy-Connection: keep-alive
Server: Virtustream Ark crtn01
X-Amz-Request-Id: 309e615c-e580-4a0f-83ba-7e391e67f58b
X-Ecr-Id: 309e615c-e580-4a0f-83ba-7e391e67f58b


-----------------------------------------------------
2016/03/16 09:34:57.724682 s3.DEBUG DEBUG: Validate Response s3/HeadBucket failed, not retrying, error :
        status code: 403, request id:
2016/03/16 09:34:57.725283 s3.DEBUG DEBUG: Request s3/HeadBucket Details:
---[ REQUEST POST-SIGN ]-----------------------------
HEAD http://krisztian.s-us.objectstorage.io/ HTTP/1.1
Host: krisztian.s-us.objectstorage.io
User-Agent: aws-sdk-go/1.0.0 (go1.6; linux; amd64)


-----------------------------------------------------
2016/03/16 09:34:57.823106 s3.DEBUG DEBUG: Response s3/HeadBucket Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 403 Forbidden
Connection: close
Connection: keep-alive
Content-Type: application/xml
Date: Wed, 16 Mar 2016 09:38:59 GMT
Proxy-Connection: keep-alive
Server: Virtustream Ark lsan01
X-Amz-Request-Id: 004f43d7-cb99-499f-ba02-12ba1be53577
X-Ecr-Id: 004f43d7-cb99-499f-ba02-12ba1be53577


-----------------------------------------------------
2016/03/16 09:34:57.823168 s3.DEBUG DEBUG: Validate Response s3/HeadBucket failed, not retrying, error :
        status code: 403, request id:
2016/03/16 09:34:57.823182 s3.INFO Unable to detect bucket region, staying at 'us-west-2'
2016/03/16 09:34:57.823582 s3.DEBUG DEBUG: Request s3/HeadBucket Details:
---[ REQUEST POST-SIGN ]-----------------------------
HEAD http://s-us.objectstorage.io/krisztian HTTP/1.1
Host: s-us.objectstorage.io
User-Agent: aws-sdk-go/1.0.0 (go1.6; linux; amd64)
Authorization: AWS4-HMAC-SHA256 Credential=XXXXXXXXXX/20160316/us-west-2/s3/aws4_request, SignedHeaders=host;x-amz-date, Signature=11e85bd7718de1326d5dcf110527c0a61608833a5e366d35d0ecdc339e53d463
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20160316T093457Z


-----------------------------------------------------
2016/03/16 09:34:57.878469 s3.DEBUG DEBUG: Response s3/HeadBucket Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 403 Forbidden
Connection: close
Connection: keep-alive
Content-Type: application/xml
Date: Wed, 16 Mar 2016 09:38:59 GMT
Proxy-Connection: keep-alive
Server: Virtustream Ark crtn01
X-Amz-Request-Id: 1ee06a72-c426-4655-8ee8-bc8c9784583c
X-Ecr-Id: 1ee06a72-c426-4655-8ee8-bc8c9784583c


-----------------------------------------------------
2016/03/16 09:34:57.878560 s3.DEBUG DEBUG: Validate Response s3/HeadBucket failed, not retrying, error :
        status code: 403, request id:
2016/03/16 09:34:57.878581 main.ERROR Unable to access 'krisztian': permission denied
2016/03/16 09:34:57.878595 main.FATAL Mounting file system: Mount: initialization failed"

with S3backer I get the same error unless I specify parameter: --authVersion=aws2

In S3backer's debug log I can see I get the same HTTP 403 if the AUTH looks like here as

"Authorization: AWS4-HMAC-SHA256 Credential=XXXXXXXXXX/20160316/us-west-2/s3/aws4_request, SignedHeaders=host;x-amz-date, "

but works in format:

"Authorization: AWS user1:+4G7GkgyTtws8L0mFbPnxPyOh6Z="

How can I force goofys to use that AUTH type 2 format?

Thanks!

Chris

**Comment by kahing** [comment]
Funny, I fixed this once for https://github.com/s3fs-fuse/s3fs-fuse/pull/181 but forgot about it for goofys. For reference, both GCS and EMC return 403 instead of 400 when they don't recognize v4 signing.

**Comment by chriss745** [comment]
Thanks Kahing, could you please fix that in goofys as well?

**Comment by kahing** [comment]
Definitely. Curious why you are using goofys with emc though. Could you share a bit more about your use case? You can find my email on my github profile if you'd rather email me privately.
