### ISSUE TITLE
OOM relates to recusive list operation

### ISSUE THREAD

**Issue by squalfof** [kahing/goofys#669]
Hi,

There's OOM issue relating to goofys deployed in our EC2, from debug log, we found millions of RECURSIVE requests:
`/usr/local/bin/goofys[17883]: s3.DEBUG DEBUG: Request s3/ListObjects Details:#012---[ REQUEST POST-SIGN ]---------------`

while there's no active operations triggered by our app(from our point of view).  Just wonder if 
1. is there any background cronjobs executed by GOOFYS like list object, or
2. is there related operations triggered by FUSE, or
3. is there any options we could employ to prohibit such operation, RECURSIVE list ?

Thanks a lot.

**Comment by arshad158510** [comment]
@squalfof , I am seeing this same exact issue. Can you please let me know if you found a solution to this problem? Thanks
