### ISSUE TITLE
installation trouble goofys on AlmaLinux (CentOS) , please help

### ISSUE THREAD

**Issue by mrAceT** [kahing/goofys#695]
I'm getting stuc on installing goofys on my AlmaLinux

This is what I've done:

- I have previously installed fuse and s3fs-fuse (via dnf). And I've got a mount working. But it's rather slow and thought it was worth it testing with goofys
- **dnf install go**
[~]# go version
go version go1.17.7 linux/amd64
- cd ~
mkdir gocode
vi .bashrc
export GOPATH=$HOME/gocode
- **go get github.com/kahing/goofys**
go: downloading .... (a lot of these)
go get: **installing executables with 'go get' in module mode is deprecated.**
        Use 'go install pkg@version' instead.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
 github.com/kahing/goofys/api/common
gocode/pkg/mod/github.com/kahing/goofys@v0.24.0/api/common/conf_azure.go:272:34: accountsRes.Value undefined (type storage.AccountListResultPage has no field or method Value)
gocode/pkg/mod/github.com/kahing/goofys@v0.24.0/api/common/conf_azure.go:373:35: not enough arguments in call to client.ListKeys
        have (context.Context, string, string)
        want (context.Context, string, string, storage.ListKeyExpand)
- **go install github.com/kahing/goofys@latest**
go: found / finding  .... (a lot of these)
 github.com/kahing/goofys/api/common
_**gocode/pkg/mod/github.com/kahing/goofys@v0.24.0/api/common/conf_azure.go:272:34: accountsRes.Value undefined (type storage.AccountListResultPage has no field or method Value)
gocode/pkg/mod/github.com/kahing/goofys@v0.24.0/api/common/conf_azure.go:373:35: not enough arguments in call to client.ListKeys
        have (context.Context, string, string)
        want (context.Context, string, string, storage.ListKeyExpand)**_

And that's where it ends for me, help is appreciated

**Comment by monthonk** [comment]
This is a known issue https://github.com/kahing/goofys/issues/527. 

However, you should be able to install it by cloning git repo and build from source with the following steps.
```
export PATH=$PATH:$GOPATH/bin
sudo dnf install git make -y
git clone https://github.com/kahing/goofys.git
cd goofys
make install
goofys -v
```

**Comment by mrAceT** [comment]
Thank you, that got me far enough :)
