### ISSUE TITLE
Unable to mount S3 compatible bucket

### ISSUE THREAD

**Issue by mislav-eu** [kahing/goofys#70]
Hi there.

I'm trying to mount s3 compatible bucket on my server, however I'm getting some strange problems. For start, I've managed to connect with s3fs (and it is slow), but I'm trying to configure goofys for performance reasons.

When trying to connect, I'm getting the following error:
```
$ goofys --use-path-request --endpoint https://XY --debug_fuse --debug_s3 -f testus /mnt/mtest

2016/03/23 10:52:21.504708 s3.DEBUG DEBUG: Response s3/HeadBucket Details:
---[ RESPONSE ]--------------------------------------
HTTP/0.0 0 status code 0

-----------------------------------------------------
2016/03/23 10:52:21.504783 s3.DEBUG DEBUG: Send Request s3/HeadBucket failed, not retrying, error RequestError: send request failed
caused by: Head https://XY/testus: read tcp XY:39481->XY:443: read: connection reset by peer
2016/03/23 10:52:21.504828 s3.ERROR code=RequestError msg=send request failed, err=Head https://XY/testus: read tcp XY:39481->XY:443: read: connection reset by peer

2016/03/23 10:52:21.504862 main.ERROR Unable to access 'testus': RequestError: send request failed
caused by: Head https://XY/testus: read tcp XY:39481->XY:443: read: connection reset by peer
2016/03/23 10:52:21.504887 main.FATAL Mounting file system: Mount: initialization failed
```

I'm able to connect via telnet to my s3 compatible host on port 443, I'm able to connect to the same host via other tools like s3browser, dragondisk, clouberry explorer and s3fs.

Next, my profile contains:
$ cat ~/.aws/credentials 
[default]
aws_access_key_id = key
aws_secret_access_key = secret

so I guess it's in valid format. 

Maybe this info helps - to this bucket I'm only able to connect via s3fs using option signature v2, v4 is not supported I guess. I didn't find on help any option.

I've also noticed one info:
s3.INFO Unable to detect bucket region, staying at 'us-west-2'

I've no idea where is my bucket region, I've asked provider but still waiting for answer - through other solutions/program I don't have to specify this. Is this maybe also one of the mandatory global options?

Any ideas?

**Comment by kahing** [comment]
Which provider are you using?

**Comment by mislav-eu** [comment]
Thank you very much. It is working now. I guess v2 was the problem.
