### ISSUE TITLE
does goofys support multiple clients to mount a bucket?

### ISSUE THREAD

**Issue by eversunsoft** [kahing/goofys#71]
I know YAS3FS does support multiple clients to mount a bucket, just wondering if goofys also support that? and what's the benchmark difference between goofys and YAS3FS?

**Comment by kahing** [comment]
goofys does not hook into SNS or use other mechanism to synchronize caches, but it also doesn't cache object contents. You can set `--stat-cache-ttl` and `--type-cache-ttl` to 0 to get up to date listings.

I have not benchmarked yas3fs but it shouldn't be hard to modify bench/run_bench.sh to do so.

**Comment by martyychang** [comment]
To answer the title question, yes, in my experience goofys does support multiple clients mounting a single bucket. I have three servers currently running which all mount the same S3 bucket using goofys and also the same AWS credentials.
