### ISSUE TITLE
EOPNOTSUPP (Operation not supported) for file write

### ISSUE THREAD

**Issue by orlando-labs** [kahing/goofys#713]
Hi, first of all, thanks for the Goofys.
There's an issue that can be reproduced with the following steps:

1. open file with O_RDWR|O_CREAT|O_TRUNC flags
2. seek 0 bytes with SEEK_END whence
3. write something

sample strace output
```
openat(AT_FDCWD, "/s3_mountpoint/somefile", O_RDWR|O_CREAT|O_TRUNC|O_NONBLOCK, 0777) = 26                                                                                                   
lseek(26, 0, SEEK_END)                  = 8351
write(26, "<?xml version=\"1.0\" encoding=\"ut"..., 512) = -1 EOPNOTSUPP (Operation not supported)
```

But everything works without that seeking.

The software that produces the given sequence is a third party legacy software and can't be changed in any way.

**Comment by dannycjones** [comment]
Hi Yvan,

If I understand correctly, the third-party software is attempting to append to the end of the file? This isn't a use case that Goofys supports today.
