### ISSUE TITLE
constant overflow on arm

### ISSUE THREAD

**Issue by julienval** [kahing/goofys#724]
Hi,

I get the following error when building on arm (raspberry):
# github.com/kahing/goofys/internal
internal/backend_s3.go:509:21: constant 5497558138880 overflows int

Cheers,
Julien

**Comment by dannycjones** [comment]
Hey @julienval,

Can you share the output of `uname -a`? This would probably help anyone debugging this figuring out which ARM.

**Comment by julienval** [comment]
Hi @dannycjones,

Here it is:
`Linux pi 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux`
