### ISSUE TITLE
Support anonymous access

### ISSUE THREAD

**Issue by ssummer3** [kahing/goofys#73]
We use bucket policies to restrict access without credentials.

This allows us to use --no-sign-request to avoid the "NoCredentialProviders: no valid providers in chain" error.

Can goofys support the lack of a profile or credentials?

**Comment by kahing** [comment]
it should just work already. For example try accessing landsat-pds from https://aws.amazon.com/public-data-sets/landsat/ works fine

**Comment by ssummer3** [comment]
```
[ec2-user@ip-172-22-8-237 ~]$ goofys -f libnd-global /tmp/
2016/04/15 14:08:25.030075 s3.ERROR code=NoCredentialProviders msg=no valid providers in chain, err=<nil>

2016/04/15 14:08:25.182001 s3.INFO Switching from region 'us-west-2' to 'us-east-1'
2016/04/15 14:08:25.184156 s3.ERROR code=NoCredentialProviders msg=no valid providers in chain, err=<nil>

2016/04/15 14:08:25.184174 main.ERROR Unable to access 'libnd-global': NoCredentialProviders: no valid providers in chain
2016/04/15 14:08:25.184181 main.FATAL Mounting file system: Mount: initialization failed
[ec2-user@ip-172-22-8-237 ~]$ aws s3 ls s3://libnd-global --no-sign-request
                           PRE CAS/
                           PRE ansible/
                           PRE biographies/
                           PRE cportal/
                           PRE jira/
                           PRE scripts/
                           PRE ssl/
                           PRE suma/
                           PRE sysdocs/
                           PRE tedx/
                           PRE windows/
2016-04-13 11:06:13         17 junk
[ec2-user@ip-172-22-8-237 ~]$

```

**Comment by kahing** [comment]
I think this is working for me because I already have some credentials setup, even though the bucket doesn't require any. @asianchica22 has volunteered to look into this.

**Comment by ssummer3** [comment]
This may be useful: https://github.com/aws/aws-sdk-go/issues/205

**Comment by kahing** [comment]
yup, goofys already does that when we test for the bucket region.

**Comment by asianchica22** [comment]
Almost done with the fix, aiming for Sunday EOD or at the latest early next week :)

**Comment by asianchica22** [comment]
Gimme like another week, took a last minute vacation overseas...unless @ssummer3 you want to take a crack at it, be my guest :)

**Comment by ssummer3** [comment]
I'd love to, but no go dev environment right now, and a few projects behind...

**Comment by asianchica22** [comment]
back to the US but currently submitting an application for a startup idea to a competition, will look into it more next week if @kahing doesn't get to it before then
