### ISSUE TITLE
Failed to compile from source neither on arm64 or x86

### ISSUE THREAD

**Issue by ddynwzh1992** [kahing/goofys#732]
Hi,

I am trying to compile the goofys on Graviton2, as there are no arm64 package available.
However when I follow the steps to build from source, following error messages shown up

# github.com/kahing/goofys/api
api/api.go:124:56: cannot use common.FusePanicLogger{...} (type common.FusePanicLogger) as type fuseutil.FileSystem in argument to fuseutil.NewFileSystemServer:
	common.FusePanicLogger does not implement fuseutil.FileSystem (missing BatchForget method)

Then I try to use x86 instance, but failed as well, with same error message 

I also have tried different go version including 1.17, 1.18, 1.19 but no lucky 

Please help to verify this

Thanks,
Vincent

**Comment by monthonk** [comment]
Hi, this PR https://github.com/kahing/goofys/pull/733 should fix the compiling issue.
At least it works on x86, would you be able to try it on arm64 as well?
thanks

**Comment by ddynwzh1992** [comment]
It works! Both x86 and arm64.
Thanks a lot

**Comment by whls** [comment]
sorry, I forget to change the file api/common/panic_logger.go.
After changed, I compiled successful!
Thanks!
