### ISSUE TITLE
Compatibility w EMC Isilion S3 and load-balancing

### ISSUE THREAD

**Issue by marcinlubojanski** [kahing/goofys#747]
What about compatibility with EMC Isilion S3? It's not listed, meaning nobody tested it or it doesn't work propely?

And another question - with multipart upload is each part a new S3 session? Each get it's own DNS request to resolve the bucket address? I want to use as many Isilion nodes for a single write request as possible and thinking if it will be here possible (with usage of DNS SmartZones).

**Comment by kahing** [comment]
this should be a question for EMC
