### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by martyychang** [kahing/goofys#75]
Trying to `go get` the package gives me a "Segmentation fault" error.

```
ubuntu@mongo-dev-marty:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
$ go version
go version xgcc (Ubuntu 4.9.3-0ubuntu4) 4.9.3 linux/amd6
$ go get github.com/kahing/goofys
Segmentation fault (core dumped)
```

**Comment by martyychang** [comment]
Looks like the fault is generated when trying to get this following package.

```
$ go get golang.org/x/net/context
Segmentation fault (core dumped)
```

**Comment by kahing** [comment]
doesn't look like this is a problem I can do much about

**Comment by martyychang** [comment]
Apparently this was caused by a Go version problem. Even though I had installed the latest version 1.6 the symlink in my PATH was pointing to a 1.2 build. After I fixed the symlink I was able to build goofys without any issues.
