### ISSUE TITLE
Clear-Text Credential

### ISSUE THREAD

**Issue by nirosanss** [kahing/goofys#751]
![image](https://user-images.githubusercontent.com/24637405/230827601-9ccd8471-0215-4232-8ee1-075b726a8bc9.png)

We noticed that our CSPM tool detects as a cleartext key in a text file. Is it possible to keep the secret in Secret Manager instead?

**Comment by kahing** [comment]
if it works with aws-cli, it should work with goofys as well. additionally you can also use IAM roles
