### ISSUE TITLE
goofys logs for IO errors?

### ISSUE THREAD

**Issue by martyychang** [kahing/goofys#76]
On Ubuntu Server 14.04 LTS I sometimes get the following symptom after a server's been running for a while.

```
~$ ls -l .
...
lrwxrwxrwx  1 ubuntu ubuntu   35 Feb  1 06:44 s3 -> /mnt/my-s3-bucket/
~$ ls -l ./s3
ls: reading directory s3: Input/output error
~$ ls -l /mnt/my-s3-bucket/
ls: reading directory /mnt/my-s3-bucket/: Input/output error
```

Rebooting the server makes the symptom disappear. Is there a log file I can check to find out why goofys may have stopped functioning?

**Comment by martyychang** [comment]
From reading another issue it seems there are some debugging options I can enable. I've done this and rebooted my server.

```
$ cat /etc/fstab | grep my-s3-bucket
my-s3-bucket /mnt/my-s3-bucket fuse.goofys _netdev,allow_other,ro,--debug_fuse,--debug_s3 0 0
```

**Comment by martyychang** [comment]
Looks like the [logs go to stderr](https://github.com/kahing/goofys/blob/7627971910443a5a6a1d80e601d132fa019e29a0/internal/logger.go#L93) by default.

**Comment by kahing** [comment]
logs go to syslog if goofys is run in background (default), and stderr if `-f` is used to keep it in foreground.
