### ISSUE TITLE
[Question] About part size for a multipart upload。

### ISSUE THREAD

**Issue by hmuchaku** [kahing/goofys#768]
Hello,

When copying large files to a goofys mount area, I assume goofys automatically uses multipart upload.
What is the part size for a multipart upload?
Is the part size fixed or variable? If variable, how is it calculated?
I need this info for s3 cost calculations.

Thank you.

**Comment by kahing** [comment]
the part size depends on size of the file https://github.com/kahing/goofys/blob/350ff312abaa1abcf21c5a06e143c7edffe9e2f4/internal/file.go#L186

**Comment by hmuchaku** [comment]
Hello,
Sorry, I have an additional question.

I understood that the size is determined by the lastPartId.
But I think that the lastPartId is determined by the number of parts, and the number of parts is determined by the file size and part size.
It is recursive and I am confused.

Is there anything that shows the correspondence between file size and multipart size?

**Comment by hmuchaku** [comment]
@kahing 
Would you check this issue?
I apologize for the misunderstanding. Is it correct to understand that the part size changes incrementally regardless of the total file size, such that the first 500 parts are 5MB, up to 1000 parts are 25MB, and so on ?
