### ISSUE TITLE
Support for CloudFlare R2

### ISSUE THREAD

**Issue by ProfessorManhattan** [kahing/goofys#775]
Hey, I was able to get this working w/ DigitalOcean with the following:

```
goofys -f --endpoint https://nyc3.digitaloceanspaces.com/ --file-mode=0777 --dir-mode=0777 private ~/TestMnt3
```

This mounts the `private` bucket to the `~/TestMnt3` folder. However, I'm unsure if CF R2 has compatibility for goofys because I get the following error when mounting an R2 bucket:

```
goofys -f --endpoint https://84fa0d1b16ff8086dd958c468ce7fd59.r2.cloudflarestorage.com --file-mode=0777 --dir-mode=0777 system ~/TestMnt3
```

Is there anyway to mount CF R2 buckets?

**Comment by joshuataylor** [comment]
Mine ended up working with `--subdomain`.
