### ISSUE TITLE
Error: DEPRECATED Action signature

### ISSUE THREAD

**Issue by pyvotal-cguers** [kahing/goofys#79]
I am trying to setup _goofys_ in a _docker_ container along with a _Python_ app that will call _goofys_ to mount an S3 bucket. However, I keep on getting an error which I cannot fix.

For testing, I am calling _goofys_ from the command line and I am getting the following error (to make sure it works before calling it from the _Python_ app).

```
# goofys my_bucket /mnt/s3
ERROR unknown Action error: Unable to connect to local syslog daemon. See https://github.com/codegangsta/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature
```

However, when I install _syslog-ng_ and run it again, I get
```
# goofys my_bucket /mnt/s3
DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/codegangsta/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature
```
I've tried this using the following as a base images, all with similar results:
- golang:1.6.2-alpine (golfing on alpine)
- Python 2.7.11
- Ubuntu 14.04

Any thoughts or suggestions?

**Comment by pyvotal-cguers** [comment]
Given this error says "This is an error in the application... Please contact the distributor of this application" I am mentioning @kahing

**Comment by lkuza2** [comment]
I believe this breaks the "-o" as well.  Really need this fixed please :)

**Comment by kahing** [comment]
could you provide a test case (either a Dockerfile or a goofys command) that exhibits this problem?

**Comment by pyvotal-cguers** [comment]
@kahing Here is a Dockerfile using Ubuntu 14.04 as a starting image
```
FROM ubuntu:14.04

# installing Python too, for my app that will work with S3 bucket mounted with goofys
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y python python-dev python-pip gcc musl-dev git libffi-dev libssl-dev curl
RUN pip install pyopenssl boto3

# Go language & Goofys
RUN curl -O https://storage.googleapis.com/golang/go1.6.linux-amd64.tar.gz
RUN tar -xvf go1.6.linux-amd64.tar.gz
RUN mv go /usr/local
ENV PATH $PATH:/usr/local/go/bin:/root/.go/bin
RUN mkdir -p /root/.go
ENV GOPATH /root/.go/
ENV GOROOT /usr/local/go
RUN go get github.com/kahing/goofys
RUN go install github.com/kahing/goofys

# copy credentials & ensure mount folder is there
RUN mkdir -p /root/.aws /mnt/s3
COPY creds/aws.credentials /root/.aws/credentials
RUN chmod 700 /root/.aws

# create script to start syslog (required by goofys)
RUN echo "service rsyslog start" > /root/rungoofys.sh
RUN echo "goofys my-bucket /mnt/sr" >> /root/rungoofys.sh
RUN chmod +x /root/rungoofys.sh

ENTRYPOINT ["sh"]
CMD ["/root/rungoofys.sh"]

# docker build -t ubuntu-goofys .
# docker run --rm ubuntu-goofys
# Returns:
# DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/codegangsta/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature
```

**Comment by pyvotal-cguers** [comment]
@kahing Here is another Dockerfile using golang+alpine as a starting point. In this case, the error is a bit different, but I still cannot get it to work.

```
FROM golang:1.6.2-alpine

# installing Python too, for my app that will work with S3 bucket mounted with goofys
RUN apk update && apk add python-dev libffi-dev openssl-dev py-pip gcc ca-certificates openssl musl-dev git fuse
RUN pip install --upgrade pip
RUN pip install PyOpenSSL boto3

# Goofys
RUN go get github.com/kahing/goofys
RUN go install github.com/kahing/goofys

# add syslog-ng (syslog required by Goofys)
RUN apk add syslog-ng
RUN echo "@version: 3.7" > /etc/syslog-ng/syslog-ng.conf
RUN echo "source s_local {internal();network(transport("udp"));unix-dgram("/dev/log");};" >> /etc/syslog-ng/syslog-ng.conf
RUN echo "destination d_local {file("/var/log/messages");};" >> /etc/syslog-ng/syslog-ng.conf
RUN echo "log {source(s_local);destination(d_local);};" >> /etc/syslog-ng/syslog-ng.conf

# copy credentials & ensure mount folder is there
RUN mkdir -p /root/.aws /mnt/s3
COPY creds/aws.credentials /root/.aws/credentials
RUN chmod 700 /root/.aws

# create script to start syslog (required by goofys)
RUN echo "syslog-ng" > /root/rungoofys.sh
RUN echo "goofys my-bucket /mnt/s3" >> /root/rungoofys.sh
RUN chmod +x /root/rungoofys.sh

ENTRYPOINT ["sh"]
CMD ["/root/rungoofys.sh"]

# docker build -t alpine-go-goofys .
# docker run --rm alpine-go-goofys
# Returns:
# [2016-05-17T14:03:36.794580] Error opening control socket, bind() failed; socket='/run/syslog-ng.ctl', error='Address in use (98)'
# DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/codegangsta/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature
```

**Comment by flashmaestro** [comment]
I got same message!
command : goofys -o allow_others wishtrend /var/www/html/img
message : DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/codegangsta/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature

after that mounted s3 bucket.
But, I can't access with web browser...
I think there is no effect -o allow_other flag...

Please fix it...

**Comment by lkuza2** [comment]
I just tested and found that "-o allow_other" does work as expected.  The error might purely be informational.  Also, completely off topic, i added this project as a package for Arch Linux in the AUR https://aur.archlinux.org/packages/goofys/

**Comment by flashmaestro** [comment]
@lkuza2 
I use s3 bucket mounted on ec2 instance.
And ec2 instance is web server.
If -o allow_other doesn work, User can not see images in s3 bucket with web browser screen...
I think -o allow_other option doesn't work... at my instance...
If I use command with -o allow_other, then there is no mount position.

How to I fix this issue?

**Comment by kahing** [comment]
Looks like `DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/codegangsta/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature` happens because that package updated its API but goofys is not updated to reflect that. Go's package management sucks so I've been building with an older version of codegangsta/cli so I wasn't aware.

That said, like @lkuza2 suggests that's just a warning message and should not affect goofys' functionality, and I just verified that -o allow_other does work for me.

```
$ sudo ./goofys -f -o allow_other landsat-pds /tmp/mnt
2016/05/17 22:50:54.913074 main.INFO File system has been successfully mounted.
$ ls /tmp/mnt
index.html  L8  landsat-pds_stats  robots.txt  run_info.json  runs  scene_list.gz  tarq  tarq_corrupt  test
$ sudo ./goofys -f landsat-pds /tmp/mnt
2016/05/17 22:51:30.944398 main.INFO File system has been successfully mounted.
$ ls /tmp/mnt
ls: cannot access /tmp/mnt: Permission denied
```

**Comment by kahing** [comment]
@pyvotal-cguers are you sure syslog in your docker image is functional? I got rid of the warning message, feel free to reopen this if it's still a problem.

@flashmaestro please provide a sequence of commands to reproduce your issue. If users cannot see your images through the web browser, it could be a http server configuration issue and not goofys.

**Comment by lkuza2** [comment]
I can confirm the "warning" issue is fixed and -o allow_other works as expected,

`
[x@xxxxxxxxx ~]$ sudo mkdir /opt/tmp
[x@xxxxxxxxxx ~]$ sudo goofys -o allow_other standard-cloud /opt/tmp/
[x@x ~]$ cd /opt/tmp/
[x@x tmp]$ ls
seafs3ql_data_10  seafs3ql_data_7           seafs3ql_passphrase_bak2
seafs3ql_data_11  seafs3ql_metadata         seafs3ql_passphrase_bak3
seafs3ql_data_12  seafs3ql_metadata_bak_0   seafs3ql_seq_no_1
seafs3ql_data_2   seafs3ql_metadata_new     seafs3ql_seq_no_2
seafs3ql_data_5   seafs3ql_passphrase       seafs3ql_seq_no_3
seafs3ql_data_6   seafs3ql_passphrase_bak1
[x@x tmp]$ cd ~
[x@x ~]$ sudo fusermount -u /opt/tmp/
`

**Comment by kahing** [comment]
```
$ ./goofys -f standard-cloud  /tmp/mnt
2016/05/17 23:08:11.749451 s3.INFO Switching from region 'us-west-2' to 'us-east-1'
2016/05/17 23:08:12.144381 main.ERROR Unable to access 'standard-cloud': permission denied
2016/05/17 23:08:12.144567 main.FATAL Mounting file system: Mount: initialization failed
```

Sigh. I can has your s3ql passphrase?

More serious question, why are you using seql and goofys? ;-)

**Comment by lkuza2** [comment]
Haha, you are going to need my AWS access key AND secret key first, then you are going to need my s3ql encryption key ;) Won't matter because the data on there is client side encrypted again lol. 

I tried using goofys, i really did, but i couldnt get it to work with my use case.  I tried having Seafile use a mounted S3 goofys filey system, but the files kept getting corrupted.  No such corruption occurs with s3ql :(

**Comment by flashmaestro** [comment]
@kahing @lkuza2 
Thx you guys!! I ran goofys command with -f option.
And get these messages.

===========
2016/05/18 12:03:45.138569 s3.INFO Switching from region 'us-west-2' to 'ap-northeast-2'
2016/05/18 12:03:45.171951 main.FATAL Mounting file system: Mount: mount: running fusermount: exit status 1

stderr:
fusermount: option allow_other only allowed if 'user_allow_other' is set in /etc/fuse.conf
===========
That is why I can't use allow_other.
So sorry It just my fault. 
I change fuse option, and get allow_other option.
Thanks again!.

**Comment by kahing** [comment]
@lkuza2 ah, well goofys isn't a general purpose filesystem so it's not surprising that it doesn't work with something like seafile. That said goofys should detect cases that it doesn't handle and fail instead of corrupting files. If you have some steps that I can reproduce easily I am happy to look into making goofys behave better.

**Comment by lkuza2** [comment]
@kahing Hmm, well all i did was on my Arch Linux box was install Seafile.  After, that i used goofys to mount my AWS drive.  I then configured seafile to use this AWS mount as its data directory.  In the data directory it stores user files, but also its main SQLite data base and PIDs.  For one, the system couldn't find the PIDs even though they were being written.  After getting around that problem, i found that simply running the Seafile server, the SQLite file becomes quickly corrupted, and Seafile refuses to run.
