### ISSUE TITLE
public api

### ISSUE THREAD

**Issue by monder** [kahing/goofys#80]
Maybe we should rename the "internal" package to something that could be [imported](https://docs.google.com/document/d/1e8kOo3r51b2BWtTs_1uADIA5djfXhPT36s6eHVRIvaU/edit#!) as library?

My case is simple - I want to use goofys as a docker volume via plugin interface, not the CLI. To do that I have a wrapper for the api - https://github.com/monder/goofys-docker. But right now, goofys added in a very hacky way via submodule + symlink. It would be great if I can reference in as a normal go package.

Or it would be good to add another package with public api, and leave "internal" and "main" packages as is?

**Comment by kahing** [comment]
That's really cool! How well does it work in practice? The goofys "api" came about as a way to test goofys independently without going through fuse, but it wasn't meant to be stably maintained.

I don't think goofys is complicated enough to warrant a public and a private api, but I also don't want to commit to maintain a stable api unless there's a strong reason. Although from the looks of it, you only need mount/umount, which is simple enough to expose.

Feel free to send a PR to expose mount/umount. Or you can also just keep this hackish way and see how well docker likes S3 ;-) Definitely keep me posted.

**Comment by kahing** [comment]
closing for now, not sure if goofys-docker is still being worked on and what the API surface should be
