### ISSUE TITLE
Auto Content-Type doesn't work

### ISSUE THREAD

**Issue by flashmaestro** [kahing/goofys#81]
@kahing 
I just reinstall goofys for auto content-type.
I uploaded any file that has binary/octet-stream.
I need it will be that's own type.

How can I get that? If there is any option flag or [default] option value?

Please let me know.
Thx.

**Comment by kahing** [comment]
`--use-content-type`

**Comment by flashmaestro** [comment]
@kahing Thanks your reply
Like this?
goofys -o allow_other --use-content-type bucketname mnt_position
Right?

**Comment by kahing** [comment]
correct
