### ISSUE TITLE
How does goofys serve files?

### ISSUE THREAD

**Issue by maxxatgit** [kahing/goofys#83]
I'm running an app hosted on a non-aws server. I want to use goofys connected to an aws S3 instance for the media (mostly audio files) filestore. When a user browses to the hosted app and has permission to download the file, I assume goofys sends the file to the hosted app, which then forwards it to the user's browser. Is that correct?
I would like for goofys to send/stream the file directly to the user's browser. That way, I'm only incurring outbound bandwidth from aws. 
So this is both a question (is it possible?) and if not, a feature request.
Thanks in advance!

**Comment by kahing** [comment]
goofys presents a filesystem mount point. It doesn't make any sense to implement what you want to do with goofys.

**Comment by andrewgaul** [comment]
@maxxatgit You want to use S3 signed URLs, not goofys.
