### ISSUE TITLE
Add option to specify non-default path to AWS credentials file

### ISSUE THREAD

**Issue by robparrott** [kahing/goofys#85]
Adding "--credentials-file" command line argument should enable a user to specify an alternative path than `os.Getenv("HOME")+"/.aws/credentials"` for credentials.

**Comment by kahing** [comment]
any reason why this is needed?

**Comment by robparrott** [comment]
Various automation tools like to add creds files into /etc and not a home dir

**Comment by jfwarner** [comment]
The default credentials chain, which #84 will enable, can make use of credentials stored in environment variables. Unfortunately it does not expose a way to change the ~/.aws/credentials path.

**Comment by blampe** [comment]
I have a similar usecase where my credential file is installed in a non-default path.

I was able to fix this with #91. Note that you can already specify a custom credential path with the `AWS_SHARED_CREDENTIALS_FILE` environment variable, but it's not completely compatible with `--profile` (which is really what that PR fixes).
