### ISSUE TITLE
Question: Random reads

### ISSUE THREAD

**Issue by schelhorn** [kahing/goofys#90]
From the readme it has become clear that random _writes_ are a no-go; how is the performance of random _reads_, is that covered by the S3 API and the `goofys` implementation to be approximately as fast as reading from the beginning of the file?

**Comment by kahing** [comment]
Random read is bad, as each read will be translated to a S3 GET request, and S3 doesn't have the best/predictable latency. Your performance will be limited by your read size and latency (which can be 100s of ms but is usually lower). Assuming 4K read and 100ms latency, your throughput would be 40KB/s, more if you issue the reads in parallel (goofys serializes reads from the same fd but you can open the file multiple times).

Sequential read is typically only bounded by your network bandwidth.
