### ISSUE TITLE
S3 mount not accessible by user specified in uid / gid

### ISSUE THREAD

**Issue by pofallon** [kahing/goofys#93]
Hello!  I'm attempting to use goofys on an elastic beanstalk deployment.  I'm running the command in an .ebextensions config file (which is run by "root"), and I set the `-uid` and `-gid` properties to those of the "webapp" user.  However, later in the deployment process, this "webapp" user tries to write to the mounted directory and receives a permission denied error.

If I log in as root, I can see the mounted S3 directory (and it's owned by the "webapp" user).  However, if I change to the "webapp" user and try to view the same directory, I get a permission denied error.

The only way the "webapp" user can view the mounted directory is to run the "goofys" command as that user (which isn't an option in this case).  Am I doing something wrong -- is there a way to run the "goofys" command as root and set the permissions so that the "webapp" user can read/write to the mounted directory?

Thanks in advance!

**Comment by kahing** [comment]
do you have `user_allow_other` in `/etc/fuse.conf`?

**Comment by pofallon** [comment]
Thanks for the reply!  I did not have that, but I tried adding it and it doesn't seem to help.  I also created a "fuse" group and added the webapp user to it, but that didn't seem to help either.

FWIW, I'm using the binary download of goofys v. 0.0.6 and this is the command I'm running:
```
goofys --region us-east-1 --uid $(id -u webapp) --gid $(id -g webapp) mybucket:mypath /opt/mydir
```

**Comment by pofallon** [comment]
It looks like adding the entry to `/etc/fuse.conf` and including `-o allow_other` on the goofys command line solved the problem.  Thanks again for your help, and for providing a great tool!

**Comment by kahing** [comment]
perhaps goofys should automatically add `-o allow_other` if `--uid` is not that of the current user? 

Alternatively, instead of/in addition to `--uid/--gid` goofys can have a `--setuid` which would drop root privilege and switch to the target user.

Patches welcome!

**Comment by cloudkitsch** [comment]
reminds me of the issue with smbfs where you have to delegate a user/group id.... acls ?
