### ISSUE TITLE
0.0.6 Possible Permissions Bug when Switching Regions

### ISSUE THREAD

**Issue by louws** [kahing/goofys#94]
Hi,

Using Goofys 0.0.6 and using the prefix format we encountered an issue when mounting an anonymous bucket in a non-default region. The default region was `us-west-2` and the bucket was hosted in `us-east-1`. While mounting the bucket without any options (`./goofys <bucket:prefix> <mount point>` ) would mount the bucket and allow us to traverse the directory. But it would not allow us to read the files contained therein. Even executing a simple `ls` on a file would yield `permission denied`. When we used `ls` on the directory we saw we had `rw- r-- r--` permissions for all files. The output for mounting the bucket was:
```
2016/07/07 22:40:10.925837 s3.INFO anonymous bucket detected
2016/07/07 22:40:10.925887 s3.INFO Switching from region 'us-west-2' to 'us-east-1
````

The issue was resolved when we explicitly specified the region like so: `./goofys --region us-east-1 <bucket:prefix> <mount point>`

I just wanted to post this here in case others encountered a similar issue.

**Comment by kahing** [comment]
I am not able to reproduce this problem:

```
$ go build && ./goofys -f landsat-pds:L8 /tmp/mnt
2016/07/31 21:05:58.607131 s3.INFO anonymous bucket detected
2016/07/31 21:05:58.607211 s3.INFO Switching from region 'us-west-1' to 'us-west-2'
2016/07/31 21:05:58.953905 main.INFO File system has been successfully mounted.
```
```
$ ls -l /tmp/mnt/index.html
-rw-r--r-- 1 khc khc 9892 Jun  1  2015 /tmp/mnt/index.html
```

What's the exact bucket and prefix were you using? (assuming it's ok to share since it's anonymous bucket)
