### ISSUE TITLE
Installation step like RioFS & S3FS

### ISSUE THREAD

**Issue by hierony94** [kahing/goofys#95]
Hi @kahing ,
I'm a S3FS user. and yes, I'm found s3fs is very slow in my site. When I looking to S3FS alternatives, I found two options that I think is worth it to try, they are **Goofys** & **RioFS**.

When I try to install RioFS, I don't find another obstacle since the installation process is very similar like S3FS (By build it from source). 
Now i want to try Goofys, and I'm not very familiar with installation using Go.

Can I Install it by build it from the source?
If yes, Can you elaborate the ways?

Thanks.

**Comment by hierony94** [comment]
I don't understand why you close it, and referenced it to your commit.
My Question is how to build it from source.

Thank You.

**Comment by kahing** [comment]
I added a reference to `GOPATH` which I believe is the only step missing. It assumes that you already have `go` which you can get from here: https://golang.org/dl/

**Comment by kahing** [comment]
The commands listed under usage is the instruction to build it from source.

**Comment by hierony94** [comment]
@kahing 

Can we install it without setup Go first?

**Comment by kahing** [comment]
you can download the binary without installing go. If you want to compile from source, you need go 1.5 on higher.
